opensafely-core/job-server

- jobserver/models/core.py
- jobserver/templates/sign_off_repo.html
- jobserver/views/projects.py
- jobserver/views/repos.py
- tests/unit/jobserver/models/test_core.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/jobserver/views/test_repos.py
This adds a line to the workspaces checklist for updating the purpose (which nearly everyone will have to do for a while), and links out to the repo's project at the bottom, explaining that they need to update its status.
I'm conditionally linking to the RepoHandler view for repos with >1 project, but as the comment says, this can go away when (if?) we tidy up that data.  For the happy path of 1 Project :: 1 Repo I've redirected to the Project's edit page using `?next=` so it'll redirect back on submit.
Fixes #2288
> Sign off projects section

- staff/templates/staff/workspace_detail.html
The repo link on the WorkspaceDetail page of the staff area linked to the branch of a workspace on GitHub.  This changes that to our internal RepoDetail page but keeps the GitHub link as a button so it's clear where on GitHub it's going to.
> Link to both our repo page and GitHub on the staff's WorkspaceDetail

- jobserver/emails.py
- tests/unit/jobserver/test_emails.py
Mailgun doesn't allow emails to be sent without a to address.  However we don't want to expose email addresses to recipients so we're using the notifications address here for lack of a better option.
Fixes: #2291
> set to address for send_repo_signed_off_notification_to_researchers

- runtime.txt
Full regex:
https://github.com/dependabot/dependabot-core/blob/00f0e52b630af6d55318951e8cb21a9a32eabbb7/python%2Flib%2Fdependabot%2Fpython%2Ffile_parser%2Fpython_requirement_parser.rb#L80-L81
How silly of me to assume the binary name was the correct one.
> Add missing hyphen

- jobserver/templates/job_detail.html
- jobserver/templates/job_request_detail.html
- jobserver/templates/org_detail.html
- jobserver/views/orgs.py
So that we are consistently using the Project name without the project number included. The project number is listed on the Project detail page, underneath the projects status.
> Use project name in breadcrumbs and workspace order

- jobserver/templates/sign_off_repo.html
- jobserver/views/repos.py
This adds a section to the repo sign-off page for researchers explaining that outputs will be made public too.  This is only displayed for repos with outputs on GitHub.
Fixes #2144
> Remind researchers that outputs hosted on GitHub will also be published

- jobserver/templates/sign_off_repo.html
> Always show the repo sign off section of the sign off page

- jobserver/templates/sign_off_repo.html
- jobserver/views/repos.py
Some fixes to the repo sign off page from end-to-end testing of the whole process.
* Purpose is now displayed in each workspace, truncated to a single line with an edit button which takes the user directly to the WorkspaceEdit page.  We can't trivially use the `?next=` trick on that form unfortunately because the repo URL gets unquoted and I don't think we want to handle that in that view.
* Project section now shows the current status of a Project if there is only one project.
**Before:**
**After:**
Fixes: #2325 
Fixes: #2326
> Repo sign off tweaks

- assets/src/scripts/components.js
- assets/src/scripts/highlight.js
- jobserver/templates/_components/index.html
- jobserver/templates/_components/pill.html
- jobserver/urls.py
- jobserver/views/components.py
- package-lock.json
- package.json
- static/robots.txt
- tests/unit/jobserver/views/test_components.py
- vite.config.js
So that devs can preview and understand what each component looks like, then utilise the demo code to add components to pages.
- New page hosted at `/ui-components/`
- Added to robots.txt
- Lists each component in a menu automatically with JS
- **Fix:** Pill component border
Closes #2337
> Add a UI component gallery page

- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
We're planning to [update][1] the job-runner sync protocol such that it syncs the state of all active jobs, where active now means those jobs which job-server thinks are active _and_ those which job-runner thinks are active. This should make the sync process even more robust against "non-standard" things happening (i.e. us fiddling with the state of jobs).
This changes means that it's no longer a protocol violation for job-runner to tell job-server about a job which job-server didn't explicitly ask about. If this happens (which I don't expect it to really) we should log it but not treat it as an error.
[1]: https://github.com/opensafely-core/job-runner/pull/519
> Ignore jobs associated with unknown JobRequests

- assets/src/js/repos-tablesorter.js
- staff/templates/staff/dashboards/copiloting.html
- staff/templates/staff/dashboards/projects.html
- staff/templates/staff/dashboards/repos.html
- staff/urls.py
- staff/views/dashboards/copiloting.py
- staff/views/dashboards/projects.py
- staff/views/dashboards/repos.py
- staff/views/repos.py
- tests/unit/staff/views/dashboards/test_repos.py
- tests/unit/staff/views/test_repos.py
This adds project number to our dashboards so we can easily reference them elsewhere.
The private repos dashboard uses them instead of names when we have them since it's quite a dense UI at this point.
Both the copiloting and projects dashboards have them as parenthesed suffixes since we don't currently have them for most projects so a prefix made the list harder to read.
Fixes: #2362
> Add project number to dashboards

- jobserver/forms.py
- jobserver/views/workspaces.py
- tests/unit/jobserver/test_forms.py
This enforces that a repo picked in the WorkspaceCreate page isn't being used by a workspace in another project.  The caveat here is if the current project is in the list of related projects and others are too then it's still ok to use the repo.
Fixes: #2271
> Restrict new workspaces to using repos in the same project

- jobserver/models/core.py
- templates/project_detail.html
- tests/unit/jobserver/models/test_core.py
This adds a link from ProjectDetail to the approve projects page on opensafely.org, appending the anchor fragment if we have a number to put in there.
Fixes: #2366
> Add link to project purpose

- templates/_components/card/card-footer.html
- templates/_components/index.html
- templates/status.html
So that it makes more sense to users and developers.
> Improve the status page layout and content

- jobserver/views/workspaces.py
- staff/views/dashboards/repos.py
- staff/views/repos.py
- templates/staff/dashboards/repos.html
- tests/unit/staff/views/dashboards/test_repos.py
This means that for a given repo, we have to look at any project connected to it, at least until we can confine all repos to only having one project.
Fixes: #2365
> Scope "first time code was run" to the project level

- applications/form_specs.py
- applications/forms.py
- snippets/9-fieldset0-is_on_cmo_priority_list-label.md
- tests/factories/applications.py
- tests/unit/applications/test_views.py
- tests/unit/applications/test_wizard.py
This is no longer relevant to the application, as the COVID research guidelines have been updated.
Fixes #2386
I'm not sure whether the `CmoPriorityListPage` should be removed or not. I've kept it for now because it seems like we'd want to keep a record in the database about whether previous applications were on the CMO priority list and potentially surface that in a dashboard somewhere.
> Remove CMO priority list question

- .github/workflows/auto-merge.yml
GHA fails a job if a step exits with a code of 1+, so /bin/false fails the whole workflow, but we want to _skip_ the workflow.  This moves the conditional to the final step where we the run section should only execute when it's true.
> use conditional on auto-merge step instead of prior step

- jobserver/honeycomb.py
- jobserver/views/job_requests.py
- jobserver/views/jobs.py
- templates/_components/list-group/list-group-item.html
- tests/unit/jobserver/test_honeycomb.py
- tests/unit/jobserver/views/test_job_requests.py
- tests/unit/jobserver/views/test_jobs.py
Also refactors the honeycomb link code to:
- use the new `scope` filter
- use more generic names, as the data we show at that link will change
- be a bit less verbose naming wise
- more robust and helpful tests
> feat: add Honeycomb live status link

- templates/_components/list-group/list-group-item.html
This is creating an invalid link.
> Fix attrs href

- .github/workflows/main.yml
Adding this, copying from opensafely-core/databuilder#897, because we're seeing more failures than normal
> replace setup-just with manual steps to avoid rate limits

- staff/urls.py
- staff/views/applications.py
- staff/views/orgs.py
- templates/staff/application_approve.html
- templates/staff/org_create.form.html
- templates/staff/org_create.html
- templates/staff/org_create.htmx.html
- tests/unit/staff/views/test_applications.py
- tests/unit/staff/views/test_orgs.py
This gets rid of our custom "I would like to add an org from the application approve page" view handler and converts the OrgCreate view and its templates to handle HTMX requests alongside full page requests.
The form is now in its own template and wrapped by either the HTMX or full-page template.  The HTMX template also handles all the model markup so the calling view only has to care about a div to replace with it.
This came up because I'm building an onboarding form for Interactive users and we want to set them up with an org and project, and copying all the markup and code from the view this removes seemed non-ideal.
> Use one org creation form regardless of full or partial page load

- jobserver/models/core.py
- tests/unit/jobserver/models/test_core.py
We spent nearly 18mo accepting jobs with config that didn't go through validation until it was parsed by job-runner.  Errors were caught there and fed back to the user via our sync mechanism.  Now that we expose the full run command of a job to the user we're parsing configs on page load.  For those older jobs this can sometimes cause an error.  I've found ~16 workspaces where this is an issue so I think we can just not display the run command for those.
Fixes [this sentry event](https://sentry.io/organizations/ebm-datalab/issues/3833851093/?project=5443358).
Fixes [this sentry event](https://sentry.io/organizations/ebm-datalab/issues/3842629873/?project=5443358)
> handle invalid configs

- .github/workflows/main.yml
Switch to using our internal opensafely-core/setup-action to avoid manually curling just in various places.
> use internal setup-action for common actions

- jobserver/views/users.py
- tests/unit/jobserver/views/test_users.py
This mirrors Django's handling of an unsafe next URL, and is a kinder route to take for users who didn't set the URL.
Fixes: #2438
> Don't return a 400 when the login page finds an unsafe next param

- applications/urls.py
- templates/applications/confirmation.html
- templates/staff/application_detail.html
This displays the underlying value for the selected type.  I haven't found how Django pulls that value for labels out of the model, but I'm not sure it's worth hunting for it given how similar the values are.
Fixes: #1861
> Fix application type of phone display

- .github/workflows/main.yml
we're removing this it from setup-action so calling workflows need to call it themselves.
> re-instate checkout action

- staff/views/users.py
- templates/staff/user_detail.html
This adds the 10 most recent jobs to a user's page in the staff area.  This gives a viewer some idea of how active (and when) a user has been on the platform.  The view all button links to the event log page filtered by the user's username.
Fixes: #2484
> List a user's 10 most recent jobs on their UserDetail page

- jobserver/models/core.py
- tests/unit/jobserver/models/test_core.py
This fixes the same issue as #2462 but for invalid YAML, rather than invalid _OpenSAFELY configs_.
Fixes [these](https://sentry.io/organizations/ebm-datalab/issues/3847330930/?project=5443358) [two](https://sentry.io/organizations/ebm-datalab/issues/3847331022/?project=5443358) Sentry errors.
> ignore YAMLErrors when reading the run_command for a job

- jobserver/views/projects.py
- templates/project_detail.html
In #2419 we added some new statuses but forgot to update the UI handling code.
> handle modified project statuses

- applications/management/commands/fix_truncated_data.py
- pyproject.toml
This adds a management command to import the correct versions of the description and purpose data which were truncated when we switched to CharFields.  I've tested this locally with a fresh copy of the prod db and the files in question.
> Import truncated app data

- jobserver/emails.py
- jobserver/forms.py
- jobserver/models/core.py
- jobserver/urls.py
- jobserver/views/users.py
- templates/emails/login_via_github.txt
- templates/emails/reset_password.txt
- templates/reset_password.html
- templates/set_password.html
- tests/unit/jobserver/models/test_core.py
- tests/unit/jobserver/views/test_users.py
This sets up a password reset flow for users, mostly using Django's built-in password reset handlers.
For users who signed up with GitHub I've added a separate email that pops them directly into the PSA auth flow so clicking the link will take them directly to GitHub and then our homepage since there's nothing for them to currently reset.
> Add a password reset flow

- jobserver/emails.py
- staff/views/users.py
- templates/emails/welcome.txt
- templates/staff/user_create.html
- tests/unit/staff/views/test_users.py
This sends a user created in the staff area an email directing them to set their password, reusing the end of the reset password flow from #2469
> Email new email-only users a link to set their password

- jobserver/models/core.py
- staff/views/users.py
- templates/staff/user_create.html
The goal with the user create page is to set up a user so that when they action the welcome email they are ready to go.  We haven't made a decision on how or where we'll create interactive repos yet so I've kept this to just creating the Workspace and Repo instances.
> ensure project has an interactive workspace

- interactive/views.py
- jobserver/authorization/permissions.py
- jobserver/authorization/roles.py
- jobserver/models/core.py
- jobserver/urls.py
- jobserver/views/users.py
- tests/unit/interactive/test_views.py
- tests/unit/jobserver/views/test_users.py
This redirects an interactive user to the appropriate interactive page when they log in.
It assumes that someone using the SetPassword view with only InteractiveRole is an interactive user for now, so we don't annoy staff users or those who start with interactive and expand their usage of the site to the typical flow.
> Redirect interactive users to form

- templates/workspace_detail.html
- Closes #2461 (fixed)
- Closes #2463 (not required)
This button should have different functionality (link vs button), and it does not need to provide a URL to the disabled button. It should also show a tooltip when disabled.
> Disable "Run Jobs" button if workspace is archived

- staff/views/orgs.py
- staff/views/projects.py
- staff/views/users.py
Found while working #2531, these changes mean we should be consistently populating the created_by and updated_by on the relevant models.  I've opted to only fix the existing fields here, rather than add any missing fields to current models to keep the problem space small.  The cost of making sure we populate these types of fields is rising and I don't want to tackle that issue here.
> set missing created_by and updated_by fields

- jobserver/views/index.py
Workspace.repo used to be a string value for the repo URL.  We moved to modelling repos as an object and missed the extra select_related value when doing so.
> Avoid O(N) queries on the homepage from workspace.repo

- templates/staff/project_detail.html
- templates/staff/workspace_detail.html
When copilots go to internally sign off a repo they have to hunt around for these fields, typically jumping to the main site to see them.  Having them on the details page for each object saves a lot of clicking around.
> Surface more repo sign off bits

- jobserver/honeycomb.py
- tests/unit/jobserver/test_honeycomb.py
Also, in order to show job request metrics, switch the job request link
to use tick traces rather than job traces, and add metrics.
> fix: switch to MAX aggregation for honeycomb metrics

- interactive/forms.py
- interactive/opencodelists.py
- interactive/views.py
- justfile
- templates/interactive/analysis_request_create.html
- tests/fakes.py
- tests/unit/interactive/test_opencodelists.py
- tests/unit/interactive/test_views.py
- tests/unit/jobserver/views/test_users.py
- tests/verification/test_github.py
- tests/verification/test_opencodelists.py
- tests/verification/utils.py
This adds an API wrapper for the OpenCodelists API, copying the method we used for GitHub, testing with a Fake and then verifying the fake separately.
The form and the way it's used in the view are a rough version that will almost certainly need to change when we integrate the react app form (eg we're likely going to POST JSON, not form data at the view), but these changes have been focussed on getting the codelists and validating their slugs.  We can address the method of submission when integrating.
Fixes: #2542
> Get codelists for Interactive form

- assets/src/scripts/staff.js
- assets/src/styles/_utilities.scss
- templates/sign_off_repo.html
- templates/staff/base.html
- templates/staff/repo_detail.html
- vite.config.js
Disabled buttons do not allow pointer events, so the tooltip was not showing in Chrome.
Using the [fix from the Bootstrap Docs](https://getbootstrap.com/docs/4.6/components/tooltips/#disabled-elements), this will allow tabbing and display the tooltip.
> Fix disabled button tooltips in staff area

- staff/views/repos.py
- templates/staff/repo_detail.html
- tests/unit/staff/views/test_repos.py
The {% if disabled %} check in the template was incorrect because a dict with any keys is always truthy.  So when the button should have been enabled it was disabled with an empty tooltip because none of the keys were True.
I've switched over to an object with a modified __bool__ implementation that aggregates the boolean values of each instance variable so we can make that check in the templates.
This also fixes a small bug in the template logic which caused both the disabled and enabled buttons to appear.
> fix disabling of the internal repo sign off button

- jobserver/context_processors.py
- jobserver/nav.py
- tests/unit/jobserver/test_nav.py
We have a number of use cases for optional menu items.  To test those out this adds a way to add items to the top level navs with an optional predicate which is checked when outputing the structure for the template.
The staff area nav has been included in this change for consistency, although we currently don't expect to use predicates for that.
> Support optional menu items

- interactive/urls.py
- interactive/views.py
- jobserver/releases.py
- jobserver/utils.py
- jobserver/views/releases.py
- jobserver/views/workspaces.py
- templates/interactive/analysis_request_create.html
- tests/unit/jobserver/test_releases.py
- tests/unit/jobserver/test_utils.py
To allow the interactive SPA to keep its pages in the URL we need to tell it what URL prefix it can ignore since that prefix is already handled by Django.
> Interactive spa base url

- requirements.prod.txt
Upgrading a single package doesn't seem to work, as pip can't resolve
the required deps needed with other pinned version so opentel packages
To do this, I did the following:
- comment out all opentelemetry packages in requirements.prod.in
- `just prodenv` then removes them
- uncomment them
- `just prodenv` then adds them as if they were all new.
Shitty, but it works.
It may be that pips proper dependency resolver works here, might be
worth trying
> chore: manual upgrade of opentelemetry packages

- jobserver/emails.py
- tests/unit/jobserver/test_emails.py
This only affected repos with both outputs on GitHub and related project(s) with numbers assigned.  I've added a test for the email function which was missed when we added this email.
Fixes: #2578
> Fix internal email bug for repos related to projects with numbers

- jobserver/views/workspaces.py
- templates/workspace_detail.html
- tests/unit/jobserver/views/test_workspaces.py
Toggling notifications on a workspace sets the default for notifications about the completion of a JobRequest.  Only a user with the workspace_toggle_notifications permission (via the ProjectDeveloper role) should be to see and use this button.
Fixes: #2522
> only show the notifications button for users who are allowed to use it

- interactive/commands.py
- jobserver/github.py
- jobserver/models/core.py
- staff/views/users.py
- templates/staff/user_create.html
- tests/fakes.py
- tests/unit/interactive/test_commands.py
- tests/unit/staff/views/test_users.py
- tests/verification/test_github.py
This updates the Create interactive user page to also create a repo on GitHub if it doesn't already exist.
I was struggling to find nice patterns to create methods on Project/User which match those in `interactive/commands.py`.  I felt like the wrong layer to have a Model know about an API, so in the end I tried pulling all the functionality into "commands", as per [CQRS terminology](https://martinfowler.com/bliki/CommandQuerySeparation.html).  I'm not sold on following CQRS strictly but I've been [curious to see how useful it would be in job-server for a while](https://github.com/opensafely-core/job-server/issues/827) and this feels like a reasonable place to give it a go, being fairly separate from the rest of the system, and tasks which require more than one Model or API call.
Fixes: …
> Create interactive repo when creating a user

- .github/workflows/main.yml
- docker/docker-compose.yaml
- jobserver/settings.py
- pyproject.toml
Now we have the template repo up and running we should be able to rely on it by default.
> Set a default for the interactive template repo

- jobserver/views/projects.py
- staff/views/repos.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/staff/views/test_repos.py
It's so rare for objects to not have jobs that we've not hit errors with this before.  However when @lucyb was running through the OSI walking skeleton with a brand new Project the ProjectDetail and staff area's RepoDetail pages had errors, which are corrected by these changes.
> Fixes for pages expecting objects to have related jobs

- .dockerignore
By default, the checkout action caches credentials in .git/config.
This allows subsequent workflow steps to use git commands w/o having to
manually specify GITHUB_TOKEN as auth.
However, when building job-server docker images, we include the .git
dir, including the credentials, cached in .git/config.
So we add .git/ to `.dockerignore` to avoid exposing these credentials,
and in general avoid adding uneccesary stuff to the docker image.
> fix: ensure credentials are not included in docker image

- interactive/opencodelists.py
This was working fine in dev and tests because requests presumably casts URLs to strings.  However in production, where we have opentelemetry enabled, this raised an error because the passed furl object has no decode method.
> Explicitly call `.url` on furl object

- interactive/models.py
We generate AnalysisRequest titles from the form the user submits, which means there are only so many titles we can ever generate.  Slugs also suffer from this, being generated from titles.  Suffixing the slug with the pk retains the read-ability of the slug but keeps it unique.
> Make AnalysisRequest.slug unique

- interactive/__init__.py
- interactive/views.py
- tests/unit/interactive/test_submit.py
This reverts commit c9ad061586f1e7893d72050d8dfa4e64125ce4da.
We need to pass in the codelist type it turns out because the dm+d codelists are still defined with snomed codes so the analysis code needs to know if a codelist is a medication or event since it can't infer it from the coding system.
> Revert "Remove codelist type"

- jobserver/models/core.py
- jobserver/views/projects.py
- jobserver/views/workspaces.py
- templates/project_detail.html
- templates/workspace_detail.html
- tests/unit/jobserver/models/test_workspace.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/jobserver/views/test_workspaces.py
We expect the happy path for Interactive users to be login -> redirect to the interactive form.  However it's possible they will end up on the appropriate Project/Workspace page, these buttons will give them a route to get to the form.
It will also benefit us while testing and debugging where we, as staff, won't be following the same path as the typical user, so having a clear route to get to the interactive form will be useful.
**Project page**
**Workspace page**
Fix: #2704
> Add buttons linking to the interactive form

- interactive/__init__.py
- interactive/views.py
- tests/unit/interactive/test_submit.py
This switches us from passing in system to type (as defined in the form) since system isn't meaningful to the study (it's always snomed), fixing the input values for https://github.com/opensafely-core/interactive-templates/pull/20
> replace system with type when templating an analysis

- jobserver/github.py
This path only exists so the method doesn't raise an exception when the repo doesn't exist.  This covers the verification tests trying to tear down a repo that has gone away or never existed for some reason.  We don't want it to fail in that situation because this is used in teardown code, not test cases themselves.
> ignore delete_repo not failing in coverage

- interactive/__init__.py
The analysis template still needs these keys and values for rendering the code, however we're not exposing them to the users so using defaults here.
> Re-add frequency and time_event with defaults

- pyproject.toml
Does not specify any dependencies, just enough metadata for pip to be
able to install it into a venv.
This is useful for downstream projects that want to use job-server as
a dependency for integration tests.
> chore: add the minimal pyproject.yaml to make pip installable

- dotenv-sample
- justfile
- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/integration/event.csv
- tests/integration/medication.csv
- tests/integration/test_interactive.py
This test is best described as an integration test but takes over a minute to run due to the study being executed.  It's been marked with the new "slow_test" marker (mirroring what job-runner uses for consistency across repos), which is being ignored in the test-dev just target, so we keep our faster feedback loop locally (the test takes >1m to run) but still have it run in CI.
> test the interactive form can template and execute a study

- jobserver/github.py
This repo is only called as part of test setup/teardown to give us a consistent state on GitHub for our tests.  We expect there to be situations where lines of it won't run and don't want those missing lines to fail the test suite.
> ignore coverage for GitHubAPI.delete_repo

- tests/verification/test_github.py
It's difficult to confirm this will work because the failure it fixes is intermittent and only happens when we have a few PRs in flight.
I couldn't use pytest's `request.node.name` because the test name is also static across the CI runs and I couldn't see anything from pytest that would give me a unique value otherwise.
Fix: #2705
> use a unique repo name for verification create_repo test

- interactive/__init__.py
- interactive/submit.py
This makes it easier for interactive-templates to import the code to use
in tests
> chore: refactor interactive templating to be importable

- interactive/submit.py
- interactive/views.py
- tests/unit/interactive/test_submit.py
Move the github url parsing out of the view and insert the secure token at the point of use instead.
> Stop github token from being persisted in db

- .github/workflows/main.yml
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
I'm hoping this fixes our problem dependabot PRs not running checks in the merge queue but we won't know until it's merged and those PRs have been rebased by dependabot.
Ref: #2751
> Run checks on merge group to enable checks for PRs in the merge queue

- assets/src/scripts/analysis-request-detail.js
- assets/src/scripts/staff.js
- package-lock.json
- package.json
- templates/_components/button.html
- templates/_components/footer.html
- templates/_components/link.html
- templates/_icons/custom/spinner.svg
- templates/components.yaml
- templates/interactive/analysis_request_detail.html
- templates/project_detail.html
- templates/staff/analysis_request_detail.html
- templates/workspace_detail.html
- vite.config.js
Starter files for downloading reports. This PR adds the dependencies and scaffolding code to enable downloads – but as we don't have formatted and outputted reports yet, it will only download the "empty" state.
- Move debug information to the Staff Area (and syntax highlight the JSON)
- Add [html2pdf](url) dependency
- Load dependency on "Download" button click
- Add a watermark to the download
- Disable buttons until the report is generated
- Add an empty/loading state whilst the report is generating
- **Fix:** A fix for links that require a character straight after a link (`append_after`)
Linked to https://github.com/opensafely-core/job-server/issues/2670
> Allow users to download Interactive reports

- interactive/commands.py
- staff/forms.py
- staff/views/projects.py
- staff/views/users.py
- templates/staff/project_create.form.html
- templates/staff/project_create.html
- templates/staff/project_list.html
- templates/staff/user_create.html
- tests/unit/interactive/test_commands.py
- tests/unit/staff/test_forms.py
- tests/unit/staff/views/test_projects.py
- tests/unit/staff/views/test_users.py
This shifts the boundary of where we create interactive workspaces (and their connected repo-on-GitHub and Repo instance) from the create user form to the project one.
For OSIv2 we're sticking with one interactive workspace per project and we're planning to use a different application process for those projects so we can't use our typical approval flow to create them.  Since we need to create projects in the staff area anyway it makes sense to create the workspace and related repo bits at the same time.  This also means we can add multiple users to an interactive project from the same create user form.
Ref: #2760
> Rework creating interactive projects and users

- jobserver/models/core.py
- jobserver/views/users.py
- tests/unit/jobserver/models/test_user.py
- tests/unit/jobserver/views/test_users.py
`has_role` looks at the "global" roles of a user, optionally searching any extra context we give it.  Rather than look up all the possible org and project memberships of the user in the view this adds a property to the User model which grabs them as a set so we can have simple membership checks.
> Check all roles for magic link login access

- jobserver/views/users.py
- tests/unit/jobserver/views/test_users.py
This assumes that interactive users will have been correctly set up when they login but since they _should_ have been created using the staff area this should be good enough for now.
> Redirect all magic link users to their interactive page

- staff/forms.py
- staff/views/projects.py
- templates/staff/project_create.form.html
This ensures we get a protocol, meaning when we display the URL it's not interpreted as a relative URL.
Fix: #2803
> Use a URLField for application URL

- jobserver/views/users.py
- tests/unit/jobserver/views/test_users.py
This was incorrectly redirecting to the workspace previously.
> Redirect interactive users to the interactive form after login

- staff/views/users.py
- templates/staff/user_detail_with_email.html
- templates/staff/user_detail_with_oauth.html
- tests/unit/staff/views/test_users.py
Our email-only users don't get access to various related objects or fields, so the staff area's UserDetail page was a little confusing for those users.
This splits the page into two views, one for users who sign in with OAuth and one for users who sign in with email.  Rather than splitting up the URLs and causing confusion with which type to use these views both work with a single URL deferring to each other in their dispatch() methods when the user type calls for it.
Fix: #2808
> Remove unrelated fields from user page for email-only users

- interactive/notifications.py
- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
This replicates the functionality from OSIv1 with a few differences:
* the ticket is created when the JobRequest finishes since we already have a hook for those sorts of notifications
* the body has been updated to match the layout of the current issue template the output checkers use
* it creates the ticket in the output checkers tracker instead of the interactive one
Fix: #2809
> Notify output checkers when the jobs for an AnalysisRequest finish

- .pre-commit-config.yaml
- justfile
pre-commit passes the paths of staged files to hooks so this splits up the checks into separate targets in the justfile (still grouped under the `check` target), with default args where necessary.
> Call our checks from the local venv in pre-commit

- pyproject.toml
- tests/unit/redirects/test_models.py
The `redirects` app was missed from the coverage config when it was added.  This adds it to the config and fixes the missing coverage lines.
> Fix redirects coverage

- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
We only want to create a ticket for output checkers when the JobRequest enters the successful state, rather than any single job entering a completed state.
We have to do some leg work to look up the status both before and after the Job updates because we're dealing with JobRequests which come from a group_by generator, rather than a QuerySet.
> Only notify output checkers when the JobRequest has succeeded

- interactive/commands.py
- interactive/emails.py
- jobserver/emails.py
- templates/staff/user_detail_with_email.html
- templates/staff/user_detail_with_oauth.html
- tests/unit/interactive/test_commands.py
- tests/unit/interactive/test_emails.py
This covers the two facets to this:
* send the email to the address in `notifications_email` so users have control over where they get their notifications.
* create interactive users with `notifications_email` set, to mirror how GitHub-based users are created.
> Fix OSI report-is-done email

- interactive/notifications.py
Updates the template used to generate output checking issues for OSI, as outlined in https://github.com/opensafely-core/interactive-templates/issues/61.
> update issue body for osi output checking template

- jobserver/models/core.py
This property makes two queries each time it is accessed.  This caches the result, to the lifetime of the User instance, avoiding the extra queries.
> Cache User.all_roles

- staff/forms.py
- staff/views/projects.py
- tests/unit/staff/views/test_projects.py
When a constraint fails a ModelForm puts the error into the non_field_errors, which we display at the top of our form.  The IntegrityError is also raised somewhere in the ModelForm's clean stack (originally coming from the link model's clean stack).
Since this failure is specifically for the number field that feels quite confusing in the UI.
This change moves ProjectCreateForm to a plain Form so we can handle the validation of the model where we create it (sticking to the principle of locality of behaviour), and thus attach the error to the correct field on our form instance allowing our error handling to display it next to the number field.
> Link Project.number uniqueness failures to their form field

- templates/project_detail.html
We're expecting that staff members will want to edit projects quite frequently, so we're adding a convenient button to take them from viewing a project to the related staff area page.
Fixes #2890
> Add "view in staff area" button

- jobserver/authorization/fields.py
- tests/unit/jobserver/authorization/test_fields.py
We typically only access roles fields via the helper functions provided in the authorizations package so querying them directly hasn't come up much before.  However, when one is trying to filter for models with a particular role using __contains and passing in the given role we still want that to work.  The RolesField implementation expects an iterable when preparing values so we cast that when we only get one now.
> Fix queries on roles fields

- interactive/notifications.py
This should make it easier for output checkers to release the Interactive report correctly, as the process is slightly different to the standard releasing of outputs.
> Add releasing instructions into issue template

- assets/src/scripts/interactive/components/ComboboxItem.jsx
- interactive/opencodelists.py
Opencodelists doesn't return a user field from their API so we're setting it to N/A for now, pending something better TBD.
Fix: #2909
> Include codelists from users in the interactive codelist search

- staff/views/repos.py
- templates/staff/repo_detail.html
This improves the render time of the staff area's RepoDetail page.  Locally it goes from ~16800ms (43 queries in ~15900ms) to ~875ms (43 queries in ~127ms).  As the final commit details it's double filtering of the users which created a more complex query plan which added the extra time.
We're still doing some O(N) queries when we look up the users for a workspace but I've yet to find a way around those.  Given our data model (arrows are the many side of the relationships):
┌─────────┐
│         │
│ Project │
│         │
└────┬────┘
│
│
│
│
│
┌──────┐      ┌─────▼─────┐
│      │      │           │
│ Repo ├──────► Workspace │
│      │      │           │
└──────┘      └─────┬─────┘
│
│
│
│
│
┌─────▼──────┐     ┌──────┐
│            │     │      │
│ JobRequest ◄─────┤ User │
│            │ …
> Fix RepoDetail pages with many workspaces

- assets/src/scripts/interactive/pages/glossary.jsx
These are minor changes based on Brian's feedback in Friday's user testing session.
I appreciate we'll probably want to make some larger changes around where the wording sits within the form, but this seemed like an easy start.
Before
After
> Clarified wording

- jobserver/management/commands/list_missing_repos.py
- pyproject.toml
The goal of this command is to help Liam know which rows in the audit spreadsheet need to be talked through with the tech team.  I've run it on a local copy of job-server to ensure it works, but it will need running against a recent copy of the production data (or just in production) once Liam has finished the audit.
> Add a command to search for missing repos

- jobserver/views/releases.py
- jobserver/views/workspaces.py
- templates/workspace_detail.html
- templates/workspace_output_list.html
- templates/workspace_release_list.html
- tests/unit/jobserver/views/test_workspaces.py
Matching how we handle buttons that a user doesn't have access to this disables the outputs links when a user doesn't have access to them.
As part of this I've reworked how we expose the aggregated permissions checks to the template so they're easier to work with there.
Fix: #2799
> Always show the outputs links on WorkspaceDetail pages

- templates/interactive/analysis_request_detail.html
We show the creator of analyses on their detail page, but linking to that user in the staff area gives a 404 for non-staff.  This switches the link to just the user's name when the viewer is not a member of staff.
> Only link to a user for staff

- applications/emails.py
- interactive/emails.py
- jobserver/emails.py
- templates/applications/emails/submission_confirmation.html
- templates/applications/emails/submission_confirmation.txt
- templates/emails/base.html
- templates/emails/base.txt
- templates/emails/login.html
- templates/emails/login.txt
- templates/emails/login_token_generated.html
- templates/emails/login_token_generated.txt
- templates/emails/login_token_used.html
- templates/emails/login_token_used.txt
- templates/emails/login_via_github.html
- templates/emails/login_via_github.txt
- templates/emails/notify_finished.html
- templates/emails/notify_finished.txt
- templates/emails/notify_report_uploaded.html
- templates/emails/notify_report_uploaded.txt
- templates/emails/notify_researcher_repo_signed_off.html
- templates/emails/notify_researcher_repo_signed_off.txt
- templates/emails/notify_staff_repo_signed_off.html
- templates/emails/project_invite.txt
- templates/emails/reset_password.txt
- templates/emails/welcome.html
- templates/emails/welcome.txt
This both adds HTML versions of all emails and a base template for the text emails to help them match the HTML emails.
A few things to check during review:
* Do the base templates' footers make sense/could they contain more information
* Have I typo'd anything in the HTML emails?  I coverted the text emails into HTML but have modified various link sections to use hyperlinks to better suit the medium.
I've tested this locally with my datalab email, do we think that's enough?
Fix: #2786
> Add HTML emails

- jobserver/models/core.py
- staff/views/users.py
- tests/unit/jobserver/models/test_user.py
This method existed to wrap converting a role to its dotted path notation and to do a `contains` lookup.  There doesn't seem much utility to this when it requires a custom Manager and QuerySet.
Fix: #2957
> Remove User.objects.filter_by_role

- interactive/submit.py
- interactive/views.py
- requirements.prod.in
- requirements.prod.txt
- tests/unit/interactive/test_submit.py
It's not used in the research template so there's no need to pass it into that system.
Ref: opensafely-core/interactive-templates#100
> Stop passing purpose into AnalysisRequest

- staff/forms.py
- staff/views/projects.py
- templates/staff/project_edit.html
- tests/unit/staff/test_forms.py
This adds the application URL field to a Project's edit page in the staff area if it's not already linked to an application, including a note on what to do if a user is looking to link the project to an application:
There's several housekeeping changes here to make the form a little more useable with so many fields, handle duplicate numbers, etc.
Fix: #2888
> Add application URL to staff area's ProjectEdit

- assets/src/scripts/interactive/pages/build-query.jsx
So that you can check two items in the same month.
Part of https://github.com/opensafely-core/job-server/issues/3035
> Add option for 0 weeks to OSI form

- justfile
Locally, changes to the interactive_templates package are not picked up automatically because we are usng a zipfile rather than providing an explicit version. This means we need to uninstall and reinstall the package to pick up any changes.
This is not a problem in CI because it is building from a fresh environment each time.
Note: this change should be removed when the package has proper versions that pip can handle appropriately. This is not intended to be a long term fix.
> Forceably reinstall interactive templates package

- interactive/forms.py
This is so that we can allow for Analysis Requests that are looking at the two codelists occuring in the same month only.
> Allow zero values for the time period

- interactive/dates.py
- interactive/views.py
- tests/unit/interactive/test_dates.py
This calculates the Monday of the week with the most recent complete extract of
data from TPP. This is passed into the Analysis and used to calculate the
number of people with matching events in that week. This number is then shown
on the report (with low number redaction).
Fixes https://github.com/opensafely-core/interactive-templates/issues/17
> Week of latest extract

- assets/src/scripts/interactive/components/CharCount.jsx
- assets/src/scripts/interactive/components/Textarea.jsx
There is currently issues where the state is being updated twice. This causes a users cursor to jump to the end of the text area when they try to edit somewhere in the text area not at the end.
This removes the double-update, and simplifies the character count logic.
> Fix state handling of values in TextArea component

- staff/views/repos.py
This was [explained][1] in the team manual, but it would have helped resolve the uncertainty on my part if it was explicit in the issue text itself.
Incidentally, the ability to do an org-wide Github search for the text I wanted to change without having any idea what system generated it felt like a super-power.
[1]: https://bennettinstitute-team-manual.pages.dev/tech-group/tech-support/#making-research-repos-public
> Make next action explicit in issue text

- interactive/commands.py
- interactive/models.py
- interactive/urls.py
- interactive/views.py
- templates/interactive/analysis_request_detail.html
- templates/interactive/report_update.html
- tests/unit/interactive/test_views.py
- tests/unit/jobserver/api/test_releases.py
* Stores the values in the already existing `Report.title` and
`Report.description` fields
* Fix: set `Report.title` to be `AnalysisRequest.report_title` that was
captured via the create form.
* Displays the user supplied title and description at the top of the
report, and provides new button to edit
> Add ability to edit Report title and description.

- interactive/issues.py
- interactive/slacks.py
- jobserver/api/jobs.py
- jobserver/api/releases.py
- jobserver/github.py
- jobserver/issues.py
- jobserver/releases.py
- jobserver/slacks.py
- jobserver/utils.py
- jobserver/views/reports.py
- services/slack.py
- staff/views/repos.py
- tests/conftest.py
- tests/unit/interactive/test_issues.py
- tests/unit/jobserver/api/test_jobs.py
- tests/unit/jobserver/test_issues.py
- tests/unit/jobserver/test_releases.py
- tests/unit/jobserver/test_utils.py
- tests/unit/jobserver/views/test_reports.py
This creates a GitHub issue and related Slack message when a user requests a report is published.
There are several code improvements that sprung up as part of this:
* Organise the functions which create GitHub issues into `issues.py` modules, matching how we handle emails and slacks.
* Add a `github_api` fixture for capturing calls to an API instance for use in tests, similar to how the `slack_messages` fixture works (h/t to @bloodearnest for this one!)
* Fix and refactor the whitespace removal code we use for GitHub issues and slacks into a utility function.
* Print issue contents when working locally (DEBUG=True)
Fix: #3011
> Notify copilots of publish request

- .gitignore
- DEVELOPERS.md
- jobserver/api/releases.py
- jobserver/management/commands/osi_release.py
- jobserver/management/commands/osi_run.py
- jobserver/management/commands/osi_run_and_release.py
- tests/unit/jobserver/api/test_releases.py
This is still a work in progress, but happy to get feedback at this point.
A few questions still outstanding
* I couldn't see a way to get reports from osi_run into osi_release without copying them into a local directory. I don't know if there's a better way? If not, then the directory probably needs renaming to something more sensible.
* Is the sample report, `outputs/interactive_report.html`, still needed if we're keeping reports from osi_run around? I think I need to understand more about people's current development process..
> Detect OSI Reports created via management command

- services/slack.py
- tests/unit/services/test_slack.py
When we fail to send a slack message Sentry picks up on the exception log we emit, but it doesn't currently have any useful context around what triggered the message or any config.  We expect knowing which channel it was trying to post to will solve that.
> Add channel to the log context of failed slack messages

- templates/org_detail.html
We added some extra statuses at the end of the signing off repos initiative to very loosely handle some new states we identified as part of moving project state into job-server.
Fix: #3139
> Handle extra statuses when listing projects on an org page

- jobserver/api/releases.py
- jobserver/views/releases.py
- templates/workspace_output_list.html
- tests/integration/test_release_api_access.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/views/test_releases.py
When moving the existing snapshots/outputs-viewer bits of the codebase over to publish requests a few places were missed.  This moves the remaining uses of Snapshot's published fields to publish requests and the is_published property.
Fix: #3136
> Fix various snapshot views

- jobserver/management/commands/osi_run_and_release.py
We're expecting the report path to be a Path instance so when invoking directly we need to pass it in as one.
Fix: #3084
> Pass report path as a Path object

- templates/interactive/analysis_request_detail.html
> Remove the yellow highlighting from text in the PDF download modal

- jobserver/api/releases.py
- jobserver/models/outputs.py
- jobserver/models/reports.py
- jobserver/views/reports.py
- templates/interactive/analysis_request_detail.html
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/models/test_outputs.py
- tests/unit/jobserver/models/test_reports.py
- tests/unit/jobserver/views/test_reports.py
This updates the UI to allow for having multiple publish requests (missed in #3108) and then limits the UI based on the state of the latest publish request, exposing why to the user with our typical use of hover state.
Things to look out for:
Instead of raising an error when we get a duplicate Snapshot this is now returning that Snapshot.  I couldn't think of a good reason where we'd want to commuicate that back to the user instead of just picking the Snapshot they've asked for.  
The code to do that lookup has changed slightly in an attempt to do a bit more of the lookup in the db, see [this range](https://github.com/opensafely-core/job-server/commit/8529a2c0fa9d432537d35732a66bc9ee90480a1b#diff-5729bca3c56ffaa3482b819ac344adad1e4bb425671e924321b62c5ed2d5c6d8L501-L507).
---
You will …
> Limit report publish requests

- interactive/views.py
- templates/interactive/analysis_request_detail.html
- tests/unit/interactive/test_views.py
I've switch from overriding `get_object` to `get` because we now need to return respones or redirects based on the user being logged in/out.
The redirect logic has been pulled straight from [Django's `login_required` implementation](https://github.com/django/django/blob/4.1.9/django/contrib/auth/decorators.py#L24-L34) (which is technically a wrapper of `user_passes_test`).  Do the comments on the code and test adequately explain why I've done that?
Fix: #3152
> Allow anyone to look at a published report

- templates/interactive/analysis_request_detail.html
Users can only set this when filling in the new AnalysisRequest form so if they don't understand what they're filling in they're then stuck with their response.  Rather than leave them stuck in this position we're removing the field from this page to avoid confusion.
Fix: #3133
> Remove AnalysisRequest.purpose from report page

- assets/src/js/copiloting-tablesorter.js
- jobserver/github.py
- staff/views/dashboards/copiloting.py
- templates/staff/dashboards/copiloting.html
- tests/fakes.py
- tests/unit/staff/views/dashboards/test_copiloting.py
- tests/verification/test_github.py
This is more complex than it might seem is necessary because we have to get the status for each repo from GitHub so it does all the processing up front to avoid extra HTTP and DB calls.
Fix: #3138
> Expose repo status(es) on the copiloting dashboard

- tests/unit/staff/views/test_orgs.py
- tests/unit/staff/views/test_projects.py
Add the missing test for the ProjectCreate view and check the template names in the non-HTMX tests.
> Normalise HTMX template tests

- .github/workflows/main.yml
- assets/src/scripts/interactive/components/ComboboxItem.jsx
- assets/src/scripts/interactive/props/index.js
- assets/src/scripts/interactive/utils/index.js
- interactive/opencodelists.py
- justfile
Fix: #2978
I've also added the `assets-test` recipe to make testing assets more obvious.  ~I didn't upgrade the GHA workflow because the install there has some extra options.~  Just's `*args` to the rescue, I've updated the GHA workflow to install and test the assets via the justfile too.
> Fallback to user if a codelist has not organisation

- jobserver/views/reports.py
- templates/interactive/publish_request_create_locked.html
- tests/integration/test_interactive.py
- tests/unit/jobserver/views/test_reports.py
Now that publishing is just about considered done and we've documented it, this adds an integration test to codify the flow.
While adding this test I discovered the PublishRequestCreate page doesn't handle a report being locked.  I've mirrored the ReportEdit page's flow, showing a locked template in that situation:
> Test the publishing flow

- jobserver/models/core.py
- jobserver/models/reports.py
- jobserver/urls.py
- jobserver/views/projects.py
- templates/project_detail.html
- templates/project_report_list.html
- tests/unit/jobserver/models/test_project.py
- tests/unit/jobserver/models/test_reports.py
- tests/unit/jobserver/views/test_projects.py
We have reports on the relevant workspace pages, so this bubbles them up to the relevant project pages.
I've copied the "latest 5 with link to all of them when total>5" paradigm from the new homepage design.  To test locally it's probably easier to replace the `all_reports` variable with `project.reports.all()` to see the link and second page in action.
**Card**
**Page**
> Add a reports card and page under projects

- jobserver/issues.py
- jobserver/views/reports.py
- templates/staff/project_edit.html
- tests/unit/jobserver/views/test_reports.py
Makes some small updates to the OSI issue template content following a mock publish request.
- Removes redundant steps
- Adds explainer around COPI compliance
- Adds a bit more signposting to where/how to complete some steps. There is one empty link that needs populating here and we could potentially provide more.
> Update issue template content

- tests/unit/jobserver/test_icons.py
We don't test every template fully renders because of the time penalty rendering templates imposes on the test suite.  The downside of this approach is sometimes there are template-only things which need testing. Typically one of those failures results in a test case where the rendered template is checked.  However, for icons this would place an overhead on frontend/UI development which we don't think is useful.
This test finds every icon tag definition across all our templates, and checks those names are defined in the components configuration file. This is intended to catch spelling mistakes or icon renames.
Tom hit this problem when renaming an icon in #3223 but we didn't want to hold that PR up while I created this test.
---
Something to consider when reviewing: I've not parsed the …
> Test all icon tags in our templates are valid tags

- jobserver/github.py
I can't replicate the GraphQL failures we've been seeing in CI so I'm adding this for when they next happen in the hope that the response from GitHub tells us something (anything!) about the situation.
Ref: #3179
> Print response details when a request fails

- tests/verification/test_github.py
We've been building up testing repos in opensafely-testing over time.  It's unclear exactly where these have come from, but this PR adds some changes to hopefully avoid creating them:
The `testing_repo` fixture now suffixes its repos with a unique ID to match the `test_create_repo` test but also changes the repo prefix to `testing-repo` so should we still have this problem we can at least track it to a code path.
`test_create_repo` now deletes its repo when done and doesn't create an extra repo via the `testing_repo` fixture.
> Try to avoid dangling repos from verification tests

- templates/interactive/analysis_request_detail.html
When a report has been published we don't want the PDF download modal talking about restrictions to sharing.  h/t @CLStables for the updated text.
Ref: #3224
> Change the download PDF text for reports once report has been published

- services/sentry.py
Declaring an empty env var means the value of `value` is an empty string when we hit this check, and we also want to skip on that.
> Skip any falsey value in Sentry parser

- jobserver/api/releases.py
- jobserver/management/commands/publish_files.py
- jobserver/models/outputs.py
- pyproject.toml
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/models/test_outputs.py
This adds a check to ensure that Snapshots are made with files from the same workspace.  We're creating all Snapshots via the PublishRequest.create_from_files method so we can rely on the check there.
Fix: #3276
> Script publishing a list of files

- redirects/models.py
- staff/views/redirects.py
- templates/staff/redirect_list.html
- tests/unit/redirects/test_models.py
This fixes Redirect.obj by looking up target FKs dynamically, and adds a couple of small fixes to the RedirectList page along the way since I was testing some of these changes there.
Fix: #3314
> More redirect fixes

- jobserver/models/core.py
- jobserver/views/job_requests.py
- staff/urls.py
- staff/views/job_requests.py
- staff/views/workspaces.py
- templates/job_request_detail.html
- templates/staff/index.html
- templates/staff/job_request_detail.html
- templates/staff/job_request_list.html
- templates/staff/workspace_detail.html
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/staff/views/test_job_requests.py
We can't lean on our typical filtering UI for JobRequests since we'd had to list nearly every User, Project, and Workspace.  I suspect we can add those in later with searchable dropdowns, however I didn't want this change to be bogged down by working out how to get those working in the staff area.
Fix: #3322
> Add JobRequests to the staff area

- jobserver/settings.py
- pyproject.toml
The argon2 hasher is more expensive to use and we don't need extra password security in tests, so lets optimise for speed in that context.
This currently affects 21 tests, which you can check by setting `PASSWORD_HASHERS=` in pyproject.toml and counting how many tests break (at least one password hasher is required).  Locally I'm seeing this shave a handful (2-3) of seconds off the test runtime, but I would expect to see a little more in CI.
> Use the MD5 password hasher in tests

- jobserver/views/job_requests.py
- tests/unit/jobserver/views/test_job_requests.py
This was missed in #3323 because of the missing check on the context data of this view.
> Annotate started_at to the latest JobRequest when creating a job

- staff/views/job_requests.py
- templates/staff/job_request_list.html
- tests/unit/staff/views/test_job_requests.py
To use select2, or any dropbox element, we need to wrap the entire page in a form so we're also capturing the search box in the right-hand column.  This allows us to keep the ability increase/reduce filters without them overriding each other, and to search within any given set of filters.
Fix: #3327
> Add searchable filters to the JobRequestList page

- static/robots.txt
* they've stopped scraping us, so have definitely read our most recent robots.txt (which told them not to scrape us at all)
* permit them to scrape us, but now with Crawl-delay set. We should have sufficient capacity to support this - and if we don't we should increase Crawl-delay
* fix https://github.com/opensafely-core/job-server/issues/3306
> chore: permit access for Amazonbot

- staff/views/analysis_requests.py
- staff/views/job_requests.py
- staff/views/orgs.py
- staff/views/projects.py
- staff/views/qwargs_tools.py
- staff/views/redirects.py
- staff/views/reports.py
- staff/views/repos.py
- staff/views/users.py
- staff/views/workspaces.py
- templates/staff/analysis_request_list.html
- templates/staff/application_list.html
- templates/staff/job_request_list.html
- templates/staff/org_list.html
- templates/staff/project_list.html
- templates/staff/redirect_list.html
- templates/staff/repo_list.html
- templates/staff/report_list.html
- templates/staff/user_list.html
- templates/staff/workspace_list.html
- tests/unit/staff/views/test_redirects.py
This adds the current search query for a staff area list page into the sidebar above any possible filters.
Along the way I've added any missing bits to various list pages to try and bring them in line with each other.
Fix: #3326
> Display search query in the filters sidebar of staff area list pages

- jobserver/management/commands/publish_files.py
- jobserver/models/outputs.py
- tests/unit/jobserver/models/test_outputs.py
Louis has asked us to publish two sets of paths.  Rather than attempt to convert those to the relevant primary keys it seems more useful to have this command take paths instead.
> Switch publishing to paths

- staff/urls.py
- staff/views/sentry.py
- templates/staff/index.html
- templates/staff/sentry/index.html
- templates/staff/sentry/message.html
- tests/unit/staff/views/test_sentry.py
In #2667 we silently stopped Sentry events being sent.  Since it's tricky to test for the absense of a signal this adds some tools that let us manually fire those signals.
> Add views to trigger sentry error and message events

- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
We encode a JobRequest failing to produce any jobs as a Job with the action "__error__", but it doesn't have a run_command.
> Allow blank Job.run_command to handle __error__ jobs

- jobserver/api/jobs.py
With a recent copy of the database this dropped the page locally from 247 queries to 4.
> Select some related models to avoid many extra queries

- jobserver/views/projects.py
Locally this ~halves the execution time for this query, the most expensive on the page.
Ref: #3393
> Only select needed columns for the first run job query

- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
job-runner's default for fields is always None, but job-server's Job.run_command doesn't allow NULLS (we treat empty strings as the empty value).  Rather than change the default on a single field in job-runner (or mess with all the other fields) we've opted to coerce nulls to empty strings in the API in job-server.
I also noticed a slight correction to how we get the data out of a serializer.
> Allow run_command to be None

- .github/workflows/main.yml
Sometimes we get coverage failures in CI, and it can be useful to have a quick pointer as to why without running the test suite locally.  This uploads the HTML output from coverage.py to GitHub if any has been generated.  It only runs if the previous step has failed, which <100% coverage will do.  It's ignoring a missing htmlcov directory because we know that will happen when coverage is 100% or doesn't run because a test failed.
This would have been useful a handful of times previously so I'm adding it now in case it ever comes up again.
> Upload the HTML coverage report when coverage fails

- jobserver/models/core.py
- tests/unit/jobserver/models/test_job_request.py
with_started_at was previously overriding the default QuerySet for JobRequests, hence super().get_queryset() in the method.  However, with this left in it had the unexpected side-effect of removing any previous filtering.
So a QuerySet in the form
some_workspace.job_requests.with_start_at()
ended up with all JobRequests instead of just those for some_workspace.
Fix: #3346
> Fix JobRequest.objects.with_started_at

- templates/job_request_detail.html
Previously, the href attribute used the project title. However, I think it should use the project slug.
> Fix link to project

- jobserver/models/core.py
- jobserver/views/job_requests.py
A couple of small fixes I found while working on something else.
We don't use anything from the Manager -> QuerySet change yet, but it removes a footgun for anyone coming along later.  It allows us do make calls in the forms:
* `JobRequest.objects.with_started_at().some_other_method().filter(blah="foo")`
* JobRequest.objects.filter(blah="foo").with_started_at()`
Currently neither of these will work.
> Job request fixes

- assets/src/scripts/staff-tw.js
- assets/src/styles/staff-tw.css
- templates/_components/article/header.html
- templates/_components/card/card.html
- templates/_components/form/input.html
- templates/_components/header.html
- templates/base-tw.html
- templates/staff/base-tw.html
- templates/staff/index.html
- vite.config.mjs
So that we can create Tailwind templates for Staff Area pages.
> Set up Staff Area template using new styles

- templates/partials/latest-jobs-tw.html
- templates/workspace_log.html
JobRequests can have no started_at when all jobs have been cancelled, before any get started, so we can't use "Pending" here.
Fix: #3407
> Use a more generic pending state

- jobserver/settings.py
- scripts/collect-me-maybe.sh
This had been previously fixed, but was broken again in
6832a34e41b3ac5db021bd25a56d398bbc67f3b6, for 2+ months.
The collect-me-maybe.sh script relies on strings being output by
`manage.py print_settings`. If they are path objects, it outputs the
repr for them, which is not valid path.
To prevent this regressing again, I have added comment and a validation
check to the script.
> Fix the collect-me-maybe script regression.

- templates/job_request_create.html
will_notify is a BooleanField under the hood, instead of a choices-supporting Field, so it doesn't provide the usual .choices() method from which to get some values from.  In moving this use of the component to use the BoundField instance I unwittingly used the static field.value (always either True/False depending on context the page was loaded in).
This reverts that change, explicitly using the strings True/False.
Fix: #3454
> Switch will_notify back to the custom form of form_radio component

- jobserver/models/core.py
- jobserver/views/job_requests.py
- requirements.prod.in
- requirements.prod.txt
- templates/job_request_detail.html
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/jobserver/views/test_job_requests.py
This is an initial attempt to pull queries out of template rendering and into the view.  It uses [django-zen-queries](https://github.com/dabapps/django-zen-queries), from the ever wonderful folks over at dabapps, a nice set of utilities built around Django's [database instrumentation hooks](https://docs.djangoproject.com/en/4.2/topics/db/instrumentation/).
zen-queries provides a great toolbox for opting in or out of render-time querying.  Getting clear errors from Django when we unexpectedly do it was our goal here and this gives it to us, with the offending query in the exception.
Some parts of zen-queries that I liked in particular:
* TemplateResponse is a drop-in replacement for Django's own response, allowing us to configure our CBVs ore return it directly.
* There are opt-outs …
> Pull queries for JobRequestDetail from template

- jobserver/context_processors.py
These run at render by their nature, so not much we can do here.
> Allow queries in context processors

- .gitignore
- docker/Dockerfile
- docker/docker-compose.yaml
- docker/justfile
- scripts/collect-me-maybe.sh
This user switch built in to the image, and thus decided at *build
time*. This means we can't accidentally misconfigure dokku and run it as
root again.
In dev, it uses the developers local uid:gid. Because we run
collectstatic in the dev entrypoint, that meant the dev volume set up
needed a slight tweak. Rather than a docker volume, it's now a bind
mount volume. This just ensures that the user has the correct
permissions to write collectstatic output there. It also means we can
easily poke around in the docker-built assets if needed.
In prod, this is an arbitrary uid:gid, currently 10001.
This uid:gid should be set up in the production environment and given
ownership/perimssions to appropriate directories. This is not for
collectstatic (which is built into the image) but instead for …
> Run docker image as non-root user

- .gitignore
- docker/justfile
- justfile
- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/unit/redirects/test_models.py
This setups up the test suite for running in parallel, but doesn't run that way by default.  Users can opt into using it by suffixing test commands with `-n <number|auto>`.
Locally this takes a full test run from ~59 to ~26s.
I've not configured this for CI because we only have one vCPU there so we get no improvement.  There's also a bug where running inside of docker seems to lose 92% of our coverage.
> Run tests in parallel with pytest-xdist

- jobserver/models/core.py
- jobserver/urls.py
- jobserver/utils.py
- jobserver/views/users.py
- templates/user_detail.html
- templates/user_list.html
- tests/integration/views/test_users.py
- tests/unit/jobserver/models/test_user.py
- tests/unit/jobserver/test_urls.py
- tests/unit/jobserver/views/test_users.py
In preparation for adding a user-centric event log (#3433) this adds a list of detail page for users, leaning heavily on the design and layout of the relevant Org pages.
Note: mirroring the org pages the breadcrumbs for the detail page don't include the list page, is that desired here?
> Add user list and detail pages

- jobserver/github.py
We're still getting intermittent failures when deleting a repo, but the plain 403 in the logs isn't very useful for debugging.
> Show the headers and content of failed repo deletions

- templates/job_request_detail.html
This slipped in when the template was rebuilt and we have so few invalid JobRequests that it rarely ever gets exercised.
Fix: #3475
> Only show the first jobs status message when the job request is invalid

- templates/job_request_detail.html
With the addition of the stale updates warning this pushes the main content area after the sidebar when there is no warning.
> Don't set a static row start

- .github/dependabot.yml
* opentelemetry packages should be updated together
* see https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/ for more info
> chore: configure dependabot group for opentelemetry

- templates/job_detail.html
Seb has pointed out that the title og job pages with the `__error__` action are not very informative to the user.
This adds a static title in those cases.
> Use a clearer job name for broken job requests

- templates/interactive/analysis_request_detail.html
- templates/user_detail.html
Staff area button needs moving over to the right at some point.
> Update user detail link

- staff/views/job_requests.py
- templates/staff/job_request_list.html
- tests/unit/staff/views/test_job_requests.py
Now that the new event log is live we've realised that we can't filter JobRequest's by backend, so adding them here.
> Add backend filter to staff area's JobRequestList page

- jobserver/models/core.py
- tests/unit/jobserver/models/test_project.py
We're moving Project.org from an FK to an M2M and this is one of the bits I'm pulling out along the way.
Ref: #2827
> Remove Org from Project's __str__

- staff/views/projects.py
- tests/unit/staff/views/test_projects.py
Orgs are no longer part of a Project's URL structure so we don't need to build redirects for them anymore.
Ref: #2827
> Stop building redirects when a Project's Org is changed

- staff/views/projects.py
- templates/staff/project/list.html
- tests/unit/staff/views/test_projects.py
In preparation for moving to Projects having multiple Orgs setting up this view to handle filtering the list of Projects by more than one.
Ref: #2827
> Enable filtering by multiple orgs in the backend of ProjectList

- templates/_components/list-group/list-group-item.html
If the link is disabled, we should render an anchor element, as there is potential it could be clicked (and lead to a 404).
Instead we should make a list element with the required classes.
> Fix disabled links in list_group_item component

- jobserver/github.py
- requirements.dev.in
- requirements.dev.txt
- tests/verification/test_github.py
We're still seeing intermittent errors from GitHub when trying to delete a repo.  Instead of a single fixed pause before retry the stamina library lets us do multiple attempts with an exponential backoff and jitter.  This uses the defaults with the expectation that we'll modify them if we still see problems.
> Retry deleting repos with backoff and jitter

- jobserver/views/workspaces.py
- templates/workspace_event_log.html
Ref: #3406
- Allow searching the workspace logs by request ID
- Not sure if users use this, but it seems like missing functionality
- Full width container to match the other event log pages
- View button seems superfluous when users could click the request ID
- Using `details` to show all job actions
- From a UX perspective it's not beautiful, but it requires no JS or additional SQL queries and helps until we do the HTMX solution
> Various workspace log fixes

- .github/dependabot.yml
* add some dependencies of opentelemetry* in the hopes of getting dependabot to bump the whole group correctly
> fix: add more packages to the otel-dependencies group

- templates/staff/project_membership_edit.html
This page's breadcrumbs and jumbotron matched the old site styles, not the old staff area styles.  Fixed here is::
* Match breadcrumbs of the staff area
* Use staff area URLs
* add big red jumbotron
> normalise staff area's edit memberhip page

- templates/staff/user/detail_with_oauth.html
This means that anyone seeing this message will know what to do.
**Old**
**New**
> Add extra detail to "No projects" banner

- requirements.prod.txt
* manual update with the same process as https://github.com/opensafely-core/job-server/pull/2577
> chore: update opentelemetry-* to 1.20.0

- .github/dependabot.yml
* doesn't appear to work as hoped
* does: try to update each dependency in turn, each one failing because of conflicts with the others
* does not: update all dependencies together
> chore: remove dependabot group

- templates/staff/analysis_request/list.html
- templates/staff/application/list.html
- templates/staff/index.html
- templates/staff/project/list.html
- templates/staff/repo/list.html
- templates/staff/report/list.html
- templates/staff/user/list.html
- templates/staff/workspace/list.html
By not setting a base grid column with a minimum size, the cards can overflow the grid on mobile screen sizes.
> Fix grid overflow issues on mobile screens

- staff/views/job_requests.py
- staff/views/redirects.py
- staff/views/users.py
We recently added a call to `user.all_roles` in the template, which increased the number of queries from 7 to 57. This change reduces the number of queries down to 9. The same approach has been applied to a couple of other views that had a similar issue.
> Reduce number of queries in staff area

- jobserver/views/index.py
This gives us an order of magnitude speed improvement over ordering by a datetime column.
> Order by pk instead of created_by

- staff/views/orgs.py
- staff/views/users.py
- staff/views/workspaces.py
- tests/unit/staff/views/test_users.py
Catherine noticed we had some duplicate users on the user list page and what looked like a simple fix turned into a mildly-sisyphean task.
Duplicate users was because we were missing a `distinct()` call, an easy fix! The other bug will be just as easy! Dear reader, let me assure you, it was not.
Note: I checked for and fixed the other staff area list pages missing the `distinct()` call.
The "has any roles: y/n" filter was giving some rather confusing results, some users were being included when filtering on `no` when they clealry had roles.  After more time than I'd like to admit, and a full repro with raw SQL, I tracked this down to users who had any membership with `roles=[]`.  So even when they had other memberships of the same type with roles they were still getting included.
> Staff area list page improvements

- snippets/start_page.md
Link to our DAA located at the bottom of the PDF of the application form needed correcting, as pathway had been deleted.
> Correcting link to DAA

- requirements.prod.txt
More prep for #3617 
This isn't being updated by dependabot, but hasn't been a problem so far.  This bump covers some more deprecations in the datetime module.
> Update structlog to 23.2.0

- .github/dependabot.yml
I've picked `all` here on the working theory that `production` will stop development updates being picked which is not the desired outcome, but ideally (I think?) we would have sub-deps of production dependencies updated where possible.
Related to #3655 where I was surprised to find we were using a 2yo structlog, because django-structlog has a very wide range for structlog.
> Enable updates for sub-dependencies

- requirements.prod.in
- requirements.prod.txt
Related to #3655 and #3656 
Structlog feels like an obvious win here, we're using it in `services/logging.py` to configure our formatter so it's effectively used everywhere.
social-auth-core feels slightly dubious though.  social-auth-django should, assuming no major architcture changes to it, always depend on social-auth-core and pull in the correct version.  However, we do directly import from the package which is why I've added it here.  Dearest reviewer, please have an opinion on this!
> Specify missing direct deps

- jobserver/models/core.py
- jobserver/permissions/t1oo.py
- tests/unit/jobserver/api/test_jobs.py
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/jobserver/test_forms.py
We've taken the deliberate decision here to use a hardcoded list of project numbers committed to the codebase, rather than storing a new set of permissions in the database. In the short-term we don't anticipate needing to add to this list. We can revist the implementation as and when that proves necessary.
As well as simplicity this approach has the advantage of creating a natural public audit trail in the form of the commit history, where changes to the database would be opaque.
> Set `database_name` based on project permissions

- templates/job_request_list.html
- templates/status.html
Closes #3517
For non-staff logged-in users, and anonymous users
> Point users to OpenSAFELY Status on Status and Event Log pages

- assets/src/scripts/outputs-viewer/__tests__/App.test.jsx
- assets/src/scripts/outputs-viewer/__tests__/components/Button/PrepareButton.test.jsx
- assets/src/scripts/outputs-viewer/__tests__/components/Button/PublishButton.test.jsx
- assets/src/scripts/outputs-viewer/components/Button/PrepareButton.jsx
- assets/src/scripts/outputs-viewer/components/Button/PublishButton.jsx
So that it is clearer what the button does.
- "Publish" changed to "Create a draft publication"
- "Confirm Publish?" changed to "Create a public published output"
> Change text on output viewer app buttons

- staff/forms.py
- staff/views/orgs.py
- staff/views/projects.py
- staff/views/repos.py
We don't have full names for all users yet so we can't consistently order by them, so we added order_by_name() in the interim to order users by fullname and fall back to username.  This uses that function consistently across the staff area.
> Consistently order lists of users in the staff area

- tests/unit/staff/views/test_job_requests.py
This test failed because it was doing a search on the first name, which was very short, and happened to return back more than one result. This changes it to search for the fullname instead, which should only ever return back a single result.
> Make flaky test more specific

- jobserver/api/jobs.py
- requirements.dev.in
- requirements.dev.txt
- tests/unit/jobserver/api/test_jobs.py
With a db dump from earlier today this takes the number of JobRequests served by the API locally from 100+ to 2.
Fix: #3770
> Remove cancelled JobRequests from API

- justfile
We moved the `opencodelists` module in a68ea25ef3d115ce9f2698278bcdce30e8f1c869, but missed the `--omit` path for `test-dev`.  We don't use this in CI so it's hard to get feedback that it happened.
> Fix coverage with `just test-dev`

- templates/applications/application_list.html
This was accidentally removed as part of fa2bb9c.
I've mirrored the styles used in the application list above this section, but added in `justify-between` for the div wrapping the name&button row, rather than using `ml-auto`, since there's no status pill to account for.
Fix: #3650
> Restore the application restore button

- jobserver/views/job_requests.py
- templates/job_request_detail.html
- tests/unit/jobserver/views/test_job_requests.py
After a certain size it takes too long to render with pygments and for the particularly large examples (2.43MB) they crash the browser locally.
I've handled the too large outcome in the template so we can make use of our `link` component.
Fix: #3704
> Don't render large project.yamls

- jobserver/models/core.py
Previously this was doing O(N) queries, which we accepted when the API was addede because we did not, at the time, have workspaces with more than low-10s of jobs.  We now have workspaces with hundreds of jobs defined.  On a particularly large workspace (long-covid-symptoms) this endpoint could take as long as 5s (and ~300 queries) to calculate.
This change uses raw SQL so we can make use of a GROUP BY in the CTE to get the latest actions and then JOIN to it in the outer query to match those up with their statuses.
Found while investigating #3781.  This isn't the cause of the slow down mentioned in that ticket, but it's running at least once on every page load, and eating away at our resources needlessly.
> Remove O(N) queries from workspace status API

- jobserver/api/releases.py
Should the creation of a report fail we want to avoid sending out notifications about the analysis request.
create_report() is also wrapped in a transaction since it touches more than one DB object.  This change leaves that transaction alone so any caller of it does not need to worry about it happening correctly, and Django will handle the stacked transactions for us.
Fix: #3708
> Only send report notifications if we create one successfully

- jobserver/releases.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/test_releases.py
- tests/unit/jobserver/views/test_releases.py
Well, this was an absolute doozy.
To recap, we have two views of the same file:
- Reports: quotes are mangled
- outputs-viewer: quotes are fine
Viewing the endpoint directly also rendered mangled quotes.  I'm still not sure why outputs-viewer was displaying them correctly, possibly something to do with the iframe? @tomodwyer – any ideas? (not relevant to this PR as all three contexts still work after this change).
I've kept FileResponse here since it sets a few values for us and recreating that, accurately, with HttpResponse wasn't worth the effort, so instead I've updated the Content-Type header to include an explicit charset.
Interestingly, `response.charset` was already correctly set to utf-8 before this change.
Fix: opensafely-core/reports#550
> Fix smart quotes in reports

- justfile
This check failed on the [audit-trail branch](https://github.com/opensafely-core/job-server/actions/runs/7251262874/job/19753252846?pr=3607) and it took me a few minutes to realise what was going on.  The check is certainly useful, and once I realised what was going on I realised what needed fixing.
This error message will hopefully point future users at the problem a little faster.
> Explain what a user should do when just check-migrations fails

- jobserver/authorization/roles.py
The name is misleading and the original description incorrect. This fixes the description, but renaming the role is more work and will have to come later.
> Update description for `CoreDeveloper` role

- templates/job_request_create.html
As they were overflowing the container.
> Fix truncation for job actions with long names

- jobserver/releases.py
- tests/unit/jobserver/test_releases.py
We've been using the new style path in production for the best part of a year at this point, so osrelease is fully moved over.
Fix: #3876
> Remove the previous code path for releasing files

- jobserver/views/releases.py
- templates/project_release_list.html
- templates/workspace_release_list.html
Similar to when a file has been deleted this hides the delete button, and adds an explanatory message next to the filename:
Fix: #3875
> Disable delete buttons for files which haven't been uploaded

- .github/workflows/auto-merge.yml
We're seeing failures [1] with the error
GraphQL: Resource not accessible by integration (mergePullRequest)
I couldn't find any resources on the permissions necessary for GraphQL mutations, however the docs for auto-merging dependabot PRs [2] use `contents: write` in their example.  Looking at the permissions docs for jobs [3] they have a section on permissions for contents [4] which lists merging [5] as covered by that permission.
1: https://github.com/opensafely-core/job-server/actions/runs/7377983549/job/20097209870#step:2:11
2: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
3: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
4: …
> Fix auto-merging of dependabot PRs

- .github/dependabot.yml
- .github/workflows/auto-merge.yml
We're reverting grouping of updates here because it's so much harder to debug errors in the groups, back to the drawing board with this one 😞
> Revert grouping of dependabot dependencies

- jobserver/views/jobs.py
- templates/job_detail.html
- templates/job_request_detail.html
This adds info alerts to the JobRequestDetail and JobDetail pages when a Job[Request] is still running but a user has requested they are cancelled, and sets the cancel buttons to disabled.
Fix: #3701 
Fix: #3702
> Show alerts when a job or job request has been cancelled

- jobserver/models/core.py
- jobserver/views/job_requests.py
- staff/urls.py
- staff/views/job_requests.py
- templates/staff/job_request/detail.html
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/staff/views/test_job_requests.py
This pulls the cancelling logic out to a method on the JobRequest model, and adds a view to the staff area to call it.
We don't have jobs in the staff area so no cancel button there.
Fix: #3700
> Add a cancel button to the staff area's JobRequestDetail page

- templates/_partials/card-pagination.html
- templates/staff/analysis_request/list.html
- templates/staff/application/list.html
- templates/staff/backend/list.html
- templates/staff/job_request/list.html
- templates/staff/org/list.html
- templates/staff/project/list.html
- templates/staff/redirect/list.html
- templates/staff/repo/list.html
- templates/staff/report/list.html
- templates/staff/user/list.html
- templates/staff/workspace/list.html
- templates/user/list.html
- templates/yours/org_list.html
- templates/yours/project_list.html
- templates/yours/workspace_list.html
Add first and last buttons to our card_pagination component.  In a view where I have 3 pages of content, this looks like so:
**First page**
**Second page**
**Third page**
Fix: #3804 
---
This also reworks the card_pagination component so we compute the various page URLs inside the component, from the given `page_obj`, so save each calling template having to care about it.  Unfortunately, we also have to pass in the `request` so we can build the URLs, but that's a small price to pay for all the centralised config we've gained IMO.
> Add First and Last buttons to the pagination component

- .gitignore
- docker/justfile
- justfile
This makes it match `just run`
> Remove default argument of bash for docker/run

- jobserver/issues.py
- jobserver/settings.py
- staff/views/dashboards/copiloting.py
- tests/unit/jobserver/test_issues.py
This removes references to the "datalab" org, selecting this org with the PK rather than the slug. For consistency, it does the same for two other orgs: "lshtm" and "university-of-bristol".
Closes #3946
> Remove references to "datalab" org

- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/integration/test_interactive.py
Now that the creation of the git commit has moved into interactive_templates, we no longer need to test the commit creation here. The interactive_templates tests are also checking run_all. We just need to confirm that we're constructing everything correctly and that we're triggering the commit to be created with the right information.
This should take around 40s off the test time and remove a fairly significant dependency.
> Simplify interactive integration test

- pyproject.toml
We're no longer using freezegun, so we don't need to ignore any warnings about it in tests.
> Remove ignore freezegun warning

- sqlite.load
It's been 3 years, we don't need to hang on to this anymore.
> Remove load file from sqlite migration

- scripts/test-coverage.sh
We can safely remove them at the end of a run to prevent the build up of lots of local temp files.
> Remove temporary coverage files

- .gitignore
- DEVELOPERS.md
- justfile
- scripts/collect-me-maybe.sh
- scripts/dev-env.sh
- scripts/dump-co-pilot-reporting-data.sh
- scripts/local-release-hatch.sh
- scripts/test-coverage.sh
After completing #3958, Millie asked for a dump of co-pilot reporting data. Whilst the snippet in `DEVELOPERS.md` is almost complete, I realized I needed to remove a pre-existing dump before running the snippet and zip the dump before sharing it. For convenience, then, I decided to move the snippet into a script.
> Add `dump-co-pilot-reporting-data.sh`

- templates/_components/header.html
- templates/base.html
Logout link now must be a POST request:
> Support for logging out via GET requests in the django.contrib.auth.views.LogoutView and django.contrib.auth.views.logout_then_login() is removed
**Source:** [docs.djangoproject.com/en/5.0/releases/5.0/](https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0)
> Fix logout link

- justfile
This adds a couple of updates from opensafely-core/repo-template. We can avoid shelling out for an environment variable, and we can better support developers who use Windows.
> Updates from opensafely-core/repo-template

- .github/workflows/main.yml
GitHub have announced that they've made 4-vCPU runners available for free for open source projects. This means we no longer need to use the paid-for larger runners to get the same benefit.
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
I've run this twice and if anything it's slightly faster than the paid-for larger runners...
First run: 4m8s
Second run: 3m58s
> Use free 4-vCPU runner

- assets/src/scripts/_plausible.js
- jobserver/middleware.py
- jobserver/settings.py
- templates/base.html
Add the response's `template_name` to the template context.
We can't do this on every invocation because we're [making use of the `template_name` context variable in applications' `page` view](https://github.com/opensafely-core/job-server/blob/caaf4f8c330714f5e0be3b3a7d6f65232cc0c5db/applications/form_spec_helpers.py#L35).
This happens to only be used for the Researcher page so could potentially be changed to something else if necessary.
Fix: #3984
> Add template_name to responses

- docker/justfile
- justfile
* rename _env just target to _dotenv
* to reduce the naming collision with arguments named env and programs called env
* refactor the .env dependency for docker targets
* some docker/justfile targets require an .env file, a better place to specify this dependency is in /docker/justfile rather than /justfile
> chore: refactor justfile dotenv for docker

- tests/unit/staff/views/test_job_requests.py
`test_jobrequestlist_search_using_username` is a flaky test (it can either pass or fail without the code under test, or the test code itself, changing). This flakiness is caused by factories that occasionally create instances with values that match the query string. Most values are obviously not going to match the query string (e.g. values of `Workspace.name` will be `workspace-0`, `workspace-1`, `workspace-2`, etc.). However, `JobRequest.identifier` might match the query string, because by default it contains a string of random, lower case, alphanumeric characters. Instead, we use a string of non-random characters with the same characteristics.
As well as `test_jobrequestlist_search_using_username`, this fixes a couple of other flaky tests.[^1] However, it doesn't fix all tests that call …
> Fix flaky test

- templates/job/detail.html
This adds a "Job metrics" card to the Job Detail page for users with one or more roles. This card displays CPU and memory usage statistics, when available (see below).
In addition to mean and peak, which are displayed here, Job Runner collects sample and cumsum for both CPU and memory usage statistics (opensafely-core/job-runner#686). However, I don't think sample and cumsum usage statistics are useful to users: sample, because we (and so they) don't know when the sample was taken; cumsum, because we (and so they) don't know how many samples were taken (and if we did, then all we would be able to compute would be the mean, which Job Runner has computed for us).
As #3998 states, usage statistics are not available for historic jobs (i.e. prior to 17/01/2024). In this case, `job.metrics == …
> Display per-job metrics on Job Detail page

- jobserver/api/releases.py
- tests/unit/jobserver/api/test_releases.py
This matches what we do for most the rest of the API endpoints here. It's only for requests that come direct from the user that we have to resort to checking the IP.
> Use backend token rather than API for auth endpoint

- staff/forms.py
Now that Projects can have more than one Org this doesn't make a lot of sense to order by them.  Elsewhere around the site we also order orgs by number then name, so this makes the drop-down for new users consistent with that.
This was missed when rebasing #2208 over the changes from #3571
> Order projects when creating interactive users by just name

- .github/workflows/main.yml
To make this clearer and aid debugging, should we need to do so.
> Label the Sentry release action with version

- docker/justfile
It now properly maps ports when used, which sometimes caught people out.
Now we've fixed that, we can drop the old `docker/serve` command
(keeping an alias) which was a bit awkward to use, as `docker compose
up` is really intended for production services.
Also added some clean ups using the parameterised dependency syntax
`(build env)`, which is much nicer than explicit `just_executable()`
calls.
> Tweak `just docker/run` command

- jobserver/views/workspaces.py
- templates/workspace/detail.html
- tests/unit/jobserver/views/test_workspaces.py
(Partially) fixes #3989 
* displays a disabled run job button if user has inadequate permissions to run jobs in this workspace (with explanatory hover text) instead of not displaying button at all
* displays a disabled run job button if user has permissions but has not been assigned backend permissions (with explanatory hover text)
> Disable Run Jobs button on workspace detail if user unable to run jobs

- templates/staff/user/detail_with_email.html
Fixes #4042.
These were broken in the staff "user with detail" view.
> Correct orgs and projects URLs in user detail area

- scripts/dev-env.sh
So that we have the latest passwords.
This scripts is only run occasionally, so is ok that it adds a couple of
seconds
> Ensure bw sync is run in dev-env.sh

- jobserver/management/commands/create_backend.py
- scripts/local-release-hatch.sh
- tests/unit/jobserver/management/commands/test_create_backend.py
It prints the auth token. Motivating use case was to set up a test
backend from cli for local tests.
Replaced the janky scripot in the local release-hatch setup.
We want to use to automate setting up a local job-server in airlock.
> Add create_backend command

- applications/emails.py
- templates/applications/emails/submission_confirmation.html
- templates/applications/emails/submission_confirmation.txt
- tests/unit/applications/test_emails.py
We're not currently open to research projects, although we will be soon, and we are accepting applications. So this change updates the information emailed to applicants when they submit an application to use OpenSAFELY.
I'm also curious to find out if there's a better way to write the assertions. I couldn't think of one at the time, but would welcome opinions.
Fixes #4060
> Update application email text

- tests/unit/interactive/test_emails.py
- tests/unit/jobserver/test_emails.py
- tests/unit/staff/views/test_reports.py
As part of working on another [ticket](https://github.com/opensafely-core/job-server/pull/4084), I noticed that we weren't testing the html content of email templates, only the plain text version. I updated those tests while working on that ticket, but now I've gone back and changed the remaining tests too.
In one case, I also moved the email test out of the test for the Reports View and into its own `test_send_report_published_email` test.
> Add assertions for the html content of emails

- jobserver/middleware.py
- jobserver/settings.py
- tests/integration/test_middleware.py
In development, this causes the single-use token page to be unexpectedly reloaded, thus generating a new token and causing confusion.
This is a (hopefully) temporary workaround in advance of this being a configurable option in `django-browser-reload`:
https://github.com/adamchainz/django-browser-reload/issues/243
> Disable auto-reload middleware on POST

- staff/views/applications.py
- templates/staff/application/detail.html
Add both `submitted_by` and `submitted_at` to the application detail page, just as we have approved, created, and deleted fields.
> Add submitted fields to application detail page

- justfile
- tests/paired_fields_utils.py
- tests/unit/jobserver/models/test_paired_fields.py
As well as testing that all paired fields' `CheckConstraint`s are working correctly, we also test that fields that look like they are paired, are indeed paired. In all cases, we maintain lists of excludes as a fail-safe.
We don't, at this stage, remove duplicated tests, or address any of the models/fields that are excluded. For example, it looks as though `CmoPriorityListPage` and `LegalBasisPage` are no longer used; and `ProjectMembership` would benefit from a factory.
Closes #3996
> Test all paired fields' `CheckConstraint`s

- jobserver/commands/__init__.py
- jobserver/commands/org_members.py
- jobserver/commands/users.py
- jobserver/models/project_membership.py
- jobserver/models/user.py
- staff/views/users.py
- tests/unit/jobserver/commands/test_org_members.py
- tests/unit/jobserver/commands/test_users.py
- tests/unit/jobserver/models/test_project_membership.py
- tests/unit/jobserver/models/test_user.py
This PR replaces the `User.clear_all_roles` method with the `users.clear_all_roles` command in the `UserClearRoles` view. It also removes the method, which is no longer used. Along the way, it introduces a couple of additional commands. Because the `users.clear_all_roles` command calls the existing `project_members.update_roles` command, we can be confident that clearing a user's roles is -- for project-membership roles -- audited.
Fixes #4093
> Replace `clear_all_roles` method with command

- scripts/local-release-hatch.sh
Unlike Ubuntu, macOS env doesn't accept the -C argument (chdir). Instead, we cd and env in a subshell.
> Fix for macOS

- assets/src/scripts/outputs-viewer/hooks/use-file-list.js
On initial load, the visible state was not being set to true. This meant files would not show up in the file list sidebar component, until the file filter was triggered.
[Link to source](https://jobs.opensafely.org/opensafely-internal/test-age-distribution/releases/01HP7ESXTT0PJ0776XFV2QF2CF/output/count_by_age.csv)
> Fix missing file from Outputs Viewer file list

- jobserver/models/user.py
- tests/unit/jobserver/models/test_user.py
Fixes #4076 
django uses `User.USERNAME_FIELD` to derive what fields are required for `manage.py createsuperuser` but not for the built-in `UserManager.create_superuser()` which expects a `username` regardless, so if this is changed to not include `username` then one will encounter a missing argument error.
Since we set the username field to `email` to support OSI user creation we can/must set the username to email for superusers created with the createsuperuser management command.
This also allows us to set the staff and superuser boolean flags (which may soon be retired) and also assign the `CoreDeveloper` role to ensure an adequately permissioned "staff" user is created by this command.
> Custom create_superuser

- templates/staff/project/membership_edit.html
In the "edit member of project" form, in the staff area.
Fixes #4043.
This commit:
* displays both email address and GitHub username, for users with a GitHub-backed login
* only displays email address for users without a GitHub-backed login (currently, Interactive users), and corrects the text to refer to "email" instead of "GitHub username"
> Change username and email display

- CHECKS
- jobserver/urls.py
- jobserver/views/health_check.py
- tests/unit/jobserver/test_urls.py
- tests/unit/jobserver/views/test_health_check.py
When we deploy Job Server, Dokku starts each container and performs a health check to ensure the container has come up properly before routing traffic to it. These health checks are customisable (see
[docs](https://dokku.com/docs/deployment/zero-downtime-deploys/)). Dokku only uses this health check when deploying new containers, it does not use it once the container has been deployed (we do have Freshping checking the site every few minutes though to make sure it's still working okay).
This change moves away from using the homepage as the health check endpoint and to a specific endpoint that will return 200 when the app starts and nothing else. Using the homepage as a health check is slower and makes a number of database connections, whereas this in theory decouples the app health check …
> Custom endpoint for dokku health checks

- templates/staff/project/edit.html
The staff area project edit screen had multiple issues:
- The org multiselect was not set up correctly, this meant the form did not validate
- The error messages were not showing at the top of the screen, or for the muliselect element
- The project status field was receiving incorrect values
This PR changes that so:
- The org select is instead a single selection option which will display an error as it is required
- The error messages for each field show at the top of the form
- The values passed to the status field is now correct
This should resolve https://github.com/opensafely-core/job-server/issues/4144 but we should confirm after deployment.
> Fix staff area project edit screen

- staff/views/projects.py
- templates/project/edit.html
- templates/staff/project/detail.html
- templates/staff/project/edit.html
- Show the Markdown-ified version of the status in the staff area
- Tell users and staff they can use Markdown when entering a status description
> Fixes for Markdown project status description field

- jobserver/models/project.py
- tests/unit/jobserver/models/test_project.py
`Project.org` was replaced by `Project.orgs` when we moved from a one-to-many to a many-to-many relationship between orgs and projects. However, we need `Project.org` in several locations. For convenience, it makes sense to show the lead org in these locations.
We expose `Project.org` as a property, meaning that an extra query is executed each time a project's lead org is requested. Hooking properties into [`prefetch_related`][1], which would reduce the number of extra queries, is non-trivial. Should we bother?
The answer depends on how many extra queries we expect. Let's take the `yours.ProjectList` view as an example
(https://jobs.opensafely.org/projects/). At present, the maximum number of projects per user is 20 - held jointly by @alexwalkerepi and @LFISHER7. For these users, this …
> Show lead org as default for projects

- tests/unit/jobserver/commands/test_project_members.py
The commands in `jobserver.commands.project_members` are decorated with `atomic` to ensure that writing to the DB results in either complete success or complete failure. Generally, we'd rely on Django to test `atomic`. However, because these commands are also adding entries to the audit log, and because the semantics of the audit log are especially important to us, we also test their atomicity.
We use `monkeypatch.context()` to be very specific about when we raise `IntegrityError`s. We don't, for example, want to interfere with the factories. Whilst we could locate `raise_integrity_error` in a utils module, we don't because we still need to import `IntegrityError` wherever the function is called.
Closes #4127
> Test atomicity of project-members commands

- templates/staff/project/audit_log.html
- templates/staff/user/audit_log.html
This provides explanatory text to users with context about what the audit log is and how it's expected to be used I've also included the date that the audit log went fully live, as I expect that will be useful to people in future.
Fixes #4109
> Explain what the audit log is to users

- jobserver/forms.py
- jobserver/views/components.py
- templates/_components/button.html
- templates/_components/form/radio_list.html
- templates/_components/index.html
3 updates to UI components that have come up while using these in Airlock:
1) Pass through id for a button component that is a link type
It was surprising that the docs said `id` was an available attribute, but i couldn't get it to appear (because my button was of type=link)
2) There were a couple of places in the docs for form components where a component was documenting using a django form field, but didn't quite work with a real django form. The main one was using `choices=<field>.choices` for a `form_select` component, whereas with a real django form field it should be `choices=<field>.field.choices`.  I've replaced the dicts that pretended to be django form fields with an actual django form.
3) Updated `form_radios` - only did this one because there was a heading for it in the docs …
> Update some UI components

- jobserver/commands/project_members.py
- jobserver/model_utils.py
- jobserver/models/project_membership.py
- tests/paired_fields_utils.py
- tests/unit/jobserver/models/test_mutability.py
- tests/unit/jobserver/models/test_paired_fields.py
This is part one of a two-part attempt to rationalize logging event-types (#4128). Here, we add `ImmutableModelMixin` and `ImmutableManager` to prevent us from accidentally mutating `ProjectMembership` outside `jobserver.commands.project_members` and, hence, outside an audited workflow.
Adding these models has already highlighted one location where we mutated `ProjectMembership` in this way. This location was removed in #4178.
The tests should help us add, delete, and update existing models safely. It is for this reason that we add `ImmutableError`: it's hard to test that an existing model has been updated from a mutable to an immutable model without it. `ImmutableError` is a child of `TypeError` because
> This exception may be raised by user code to indicate that an attempted operation …
> Rationalize logging event-types

- jobserver/api/releases.py
- jobserver/urls.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/test_urls.py
This is a slew of small changes needed for the releases authentication/authorisation API.
We needed some more information, and also the ability to refresh authorisation w/o re-authenticating.
Also added a quick fix to expose a little more information about failed logins, as it is hard to diagnose failures with out it.
> Releases authn/z api improvments

- docker/docker-compose.yaml
- requirements.prod.txt
This is a substitute for #4191, which fails due to the database not being accessible in the Docker tests.
> Upgrade Django to 5.0.3

- INSTALL.md
- jobserver/settings.py
This PR allows the use of Django's `SECRET_KEY_FALLBACKS` by configuring the `OLD_SECRET_KEY` environment variable to use the previous key.
This avoids users all getting logged out at once. Instead, we can:
1. Leave the previous secret key active, side-by-side with the new key.
1. Give some time for active users to access the site running the new secret key which updates their sessions.
1. Remove the previous secret key entirely.
> Allow `OLD_SECRET_KEY` for secret key rotation

- templates/staff/project/audit_log.html
- templates/staff/user/audit_log.html
The project view and user view of the audit log use a (possibly) outdated form of the card_pagination UI component. This updates these pages to use the form of this component that we use elsewhere.
Before:
After:
> Fix audit log card pagination

- jobserver/commands/project_members.py
- jobserver/commands/users.py
- staff/views/projects.py
- tests/unit/jobserver/commands/test_project_members.py
- tests/unit/staff/views/test_projects.py
- tests/unit/staff/views/test_users.py
The substantive commit in this PR is 04a5069. Previously, removing a membership resulted in an entry like this in the audit log:
Notice that because the user (Alex) was added to the project (TNCC Vaccine Efficacy) before the audit log existed, there isn't an entry in the audit log that describes the user's roles.
Now, removing a membership results in entries like this in the audit log:
The remaining commits do some light refactoring (7d88878 and d0c4482) and prepare the ground (1a1f93b).
> Remove roles before removing membership

- templates/applications/confirmation.html
Closes #2380
The checklist appears at the bottom of the "Check your answers" page, above the "Submit for approval" button.
> Add a checklist at the end of the application form

- applications/views.py
- interactive/views.py
- jobserver/api/releases.py
- jobserver/views/job_requests.py
- jobserver/views/jobs.py
- jobserver/views/projects.py
- jobserver/views/releases.py
- jobserver/views/reports.py
- jobserver/views/workspaces.py
- staff/views/orgs.py
- staff/views/repos.py
- staff/views/users.py
This PR replaces permissions encoded as strings with their corresponding symbols. (I hope that's the right word for them; if not, then sorry computer scientists 🙁.) For example, it replaces `"workspace_toggle_notifications"` with `permissions.workspace_toggle_notifications`. Doing so makes it much easier to look up where, and how, permissions are used.
I've not replaced strings with symbols when the strings are expected values in the test suite. This gives me greater confidence that I've not made an error, and also avoids having to come up with another name for the concept of permissions, as a variable with that name often clobbers the module with that name.
One permission is unused. For more information, see #4255.
> Strings to symbols

- templates/index-unauthenticated.html
1. Using Firefox, go to the home page as a logged out user
2. Click around in the hero header section of the home page
3. Weird background blocks show up
Move the blur on the SVG background to the content element using [Backdrop Blur](https://tailwindcss.com/docs/backdrop-blur).
> Fix backdrop blur causing outlines in Firefox

- jobserver/api/releases.py
- tests/unit/jobserver/api/test_releases.py
If available, use the Airlock release request ID when creating a new release.
> Use airlock ID as the release id

- tests/conftest.py
- tests/unit/applications/test_views.py
- tests/unit/interactive/test_views.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/models/test_user.py
- tests/unit/jobserver/views/test_job_requests.py
- tests/unit/jobserver/views/test_jobs.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/jobserver/views/test_releases.py
- tests/unit/jobserver/views/test_reports.py
- tests/unit/jobserver/views/test_workspaces.py
Rather than associating a role with zero or many permissions, this associates a role with zero or one permission, making the implementation less error-prone. In the handful of cases where a function/method under test requires a user to have two permissions, we now assign the user two roles with one permission each. Previously, we would have assigned them one role with two permissions.
Thank you, @lucyb for suggesting this change when reviewing #4277.
> Simplify the `role_factory` fixture

- jobserver/github.py
If we're running a local jobserver in docker (e.g. for airlock developement) the debugging print statements in github.py aren't shown in the docker logs. Adding some logging here too for debugging purposes.
> Add some debug logging for github issues

- justfile
We exclude several tests that use these fakes from `just test-dev`, which causes coverage to fail. This doesn't affect CI, which calls `just test`.
> Exclude fakes from `just test-dev`

- airlock/issues.py
- airlock/views.py
- jobserver/github.py
- tests/unit/airlock/test_issues.py
- tests/unit/airlock/test_views.py
Fixes https://github.com/opensafely-core/job-server/issues/4316
(along with Airlock PR https://github.com/opensafely-core/airlock/pull/306)
Also fixed a bug in the formatting for github that I found now that I was able to test real opening/updating/closing issues on the [test repo](https://github.com/ebmdatalab/output-checking-test/issues)
> Read output checking org and repo for airlock notifications from received payload

- templates/_components/table/table-header.html
As per docs:
https://fiduswriter.github.io/simple-datatables/documentation/Getting-Started
> Expose datatable attributes in table-header component

- airlock/views.py
- tests/unit/airlock/test_views.py
Airlock posts to the events endpoint for a change in status to REQUEST_APPROVED. Currently we don't send any notifications or action any github issues for this status, but we weren't handling it; now it accepts a REQUEST_APPROVED status, but doesn't action any notifications; for now we'll keep this no-action path as it's inexpensive and might be required later.
We also now catch an unknown event type received from Airlock and return an error response.
> Handle unknown airlock event types

- .github/workflows/main.yml
It was too noisy across all datasets
> Only add job-server deploy markers to job-server dataset

- jobserver/authorization/roles.py
`ProjectDeveloper.description` stated that a project developer can publish released outputs. The ability to publish released outputs is governed by the `snapshot_publish` permission. However, `ProjectDeveloper.permissions` didn't include that permission.
We will assume that `ProjectDeveloper.permissions` is correct and `ProjectDeveloper.description` is incorrect, and remove the statement that a project developer can publish released outputs from `ProjectDeveloper.description`.
Closes #4331
> Clarify `ProjectDeveloper` permissions

- airlock/config.py
- airlock/views.py
- tests/unit/airlock/test_views.py
This allows  output-checking issues to be opened in custom repos, depending on organisation. Airlock can also send configuration to use, which allows an entire backend to use a different repo (e.g. the test backend, which we don't want to use a real output checking repo).
Note: the opensafely-readonly user will need to be added as a collaborator on Bristol's output checking repo so it has permissions to open/edit issues.
> Allow configuration of org/repo for airlock issues by organisation

- airlock/emails.py
- airlock/views.py
- templates/airlock/emails/request_returned.html
- templates/airlock/emails/request_returned.txt
- tests/unit/airlock/test_views.py
Airlock requests can now be returned and re-submitted. Notifications are sent accordingly:
- returned request: email author, update issue (add a comment to existing issue)
- resubmitted request:  update issue (add a comment to existing issue)
Note that we'll probably get rid of the UPDATED event type soon, and only send these notifications from Airlock on status changes (not on context/control editing or file adding/withdrawing), and the signature of the update_issue function might change, but leaving it as is for now.
> Update output-checking issues for Airlock returned and resubmitted events

- .github/workflows/main.yml
Replace gzip with ZStandard in fast mode.
Pass compressed file directly to `docker image load` removing a redundant separate decompression and pipe.
Fixes #4354
> Speed up file compression and decompression in CI

- applications/form_specs.py
- snippets/description-help_text.md
Increase the character limit for the "Study purpose" > "Simple description" field. We use characters as a proxy for words, as it's far easier to set a character limit than a word limit.
Changed elements highlighted in red, below.
Co-authored-by: JulietUnderdown1 <162142133+JulietUnderdown1@users.noreply.github.com>
Closes #4374
> Increase "Simple description" character limit

- airlock/config.py
- airlock/issues.py
- airlock/slack.py
- airlock/views.py
- pyproject.toml
- tests/unit/airlock/test_issues.py
- tests/unit/airlock/test_views.py
Fixes https://github.com/opensafely-core/airlock/issues/402
The following release request changes need to notify output checkers, and don't automatically post in slack (they update an existing github issue by adding a comment, which doesn't get posted into slack by the github integration):
- partially reviewed (i.e. reviewed by the first output-checker) in a round
- fully reviewed (i.e. reviewed by the second output-checker) in a round
- resubmitted (after a request was previously reviewed and returned)
> Slack notifications for Airlock events

- jobserver/settings.py
django-permissions-policy was added by #495 to disable Google's [Federated Learning of Cohorts](https://privacysandbox.com/proposals/floc/) (FLoC). FLoC was replaced by [Topics](https://privacysandbox.com/proposals/topics/) in May 2023, so we update the Permissions-Policy header to disable Topics.
Closes #4390
> Update Permissions-Policy to disable Topics

- staff/views/projects.py
7ba76cf refactored project editing into a command
and in the process the `old` Project instance in
this edit method was changed from `form.get_object()`
to `form.object`.
The latter is the same as the `new` Project instance
and so redirects were being created with the same URL
for both old and new.
fixes #4158
> Fix project redirect regression

- jobserver/api/releases.py
- tests/unit/jobserver/api/test_releases.py
Airlock needs information about whether a user's workspaces are archived, so it can allow browsing of those workspaces, but restrict release requests for them.
> Return info about workspace archived status in releases auth endpoint

- airlock/config.py
- dotenv-sample
- interactive/issues.py
- jobserver/issues.py
- jobserver/settings.py
- jobserver/slacks.py
Instead of hard-coding slack channels and github org/repos in multiple places, move them to settings and allow them to be overridden by environment variables. This makes it much easier to  set up local testing that includes testing slack/github integrations without posting to production channels/repos.
> Move hard-coded slack channels and github repos to settings

- justfile
Previously coverage was being started every time a just command was run. This resulted in commands being slower than they needed to be.
This change also means that the temporary coverage files are actually removed at the end of a test run.
> Start coverage only on just commands using coverage

- .github/workflows/main.yml
- DEVELOPERS.md
- TESTING.md
- justfile
Coverage is currently very slow to run, causing the unit tests to go from taking 20 secs to 2 mins on my machine. This change means the default test command only runs the fast tests directly, without running coverage. This gives us much faster feedback during development, but still gives us the benefit of coverage in CI.
This also uses xdist with its default settings to run the tests in parallel locally.
> Skip coverage locally

- tests/unit/staff/views/test_projects.py
#4407  was missing a suitable test for the reported bug condition that a editing a project's slug resulted in creation of a redirect where the old and new URLs were the same.
This PR adds such a test in, and also checks that redirects are not created where projects are edited without changing the slug.
> Improve testing of redirects following project edit

- requirements.dev.txt
- requirements.prod.txt
Closes:
* https://github.com/opensafely-core/job-server/security/dependabot/81
* https://github.com/opensafely-core/job-server/security/dependabot/82
> Bump certifi from 2023.11.17 to 2024.7.4

- jobserver/context_processors.py
- jobserver/settings.py
- tests/unit/jobserver/test_context_processors.py
As part of [#4391](https://github.com/opensafely-core/job-server/issues/4391) to remove the use of zen-queries, I noticed that the only use of this function was removed in 4dd6c3 and so it's no longer needed.
> Remove staff_nav function

- justfile
Without this commit, what happens when you have multiple tags in the
`interactive-templates` repository is that:
1. The `tag` value contains each of those tags, separated by newlines.
2. The subsequent `sed` (not the one in the changed line) that edits the
requirements fails.
We only want to replace the text with the single version tag that we
want to upgrade to.
Other notes:
* This change also explicitly uses `--sort` for `ls-remote` so that we
can be assured of the position of the latest version. It's not clear
from the `ls-remote` documentation that results are sorted or not
otherwise. We take the latest version.
* We use `END` with `awk` to use the last line of the `ls-remote`
output. We could use `tail` but that means adding an extra pipeline
command, whereas we can use `awk` …
> Make `update-interactive-templates` select one tag

- docs/adr/0020-replace-zen-queries.md
- jobserver/context_processors.py
- tests/unit/jobserver/test_context_processors.py
The call to zen-queries has been replaced with some unit tests instead. I'm in two minds about keeping these unit tests and would appreciate feedback. They were useful for convincing myself that no db calls were being made and the intent is certainly clear, but if it's already obvious that no DB calls are being made then we should remove them.
I've added an ADR because this change is the first step to removing zen-queries and that seemed like the sort of thing we should document.
Refs: #4391
> Remove zen-queries from context processors

- airlock/emails.py
- airlock/views.py
- templates/airlock/emails/includes/updates.html
- templates/airlock/emails/includes/updates.txt
- templates/airlock/emails/request_rejected.html
- templates/airlock/emails/request_rejected.txt
- templates/airlock/emails/request_released.html
- templates/airlock/emails/request_released.txt
- templates/airlock/emails/request_returned.html
- templates/airlock/emails/request_returned.txt
- templates/airlock/emails/request_updated.html
- templates/airlock/emails/request_updated.txt
- tests/unit/airlock/test_emails.py
- tests/unit/airlock/test_views.py
Airlock now sends notifications for status changes only, with potential optional update messages that are now included in emails.
> Airlock notification updates

- requirements.dev.txt
- requirements.prod.txt
A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.
Fixes https://github.com/opensafely-core/job-server/security/dependabot/89
> Bump setuptools from 69.0.3 to 70.3.0

- staff/views/applications.py
- templates/staff/application/detail.html
- tests/unit/staff/views/test_applications.py
This follows on from PR #4436. It removes zen queries from applications in the staff area and replaces it with some tests that explicitly count the number of DB queries that are made.
I expect to use the same approach here for the remaining parts of the codebase that use zen queries. So I would particularly appreciate any feedback that gives some thought to the same kind of code being used in multiple other places (now is a good time to be pernickety about test names, etc).
Refs: https://github.com/opensafely-core/job-server/issues/4391
> Remove Zen Queries in staff area "applications" section

- .github/workflows/update-interactive-templates.yml
This is a proposal to move the [interactive-templates update workflow](https://github.com/opensafely-core/interactive-templates/blob/b8f742c2ecea2de223aa74ec8c8773f953e5a2d9/.github/workflows/create-job-server-pr.yml) from the interactive-templates repository to here.
The workflow was added in the interactive-templates repository to run on a new release of interactive-templates, and then open a pull request to job-server. The workflow is run daily and can be run manually on request.
This is based on the version of the workflow from opensafely-core/interactive-templates#377 which has fixes necessary for the workflow to work. The workflow operates like the "check resource for update and create a PR if so" [workflows in ehrQL](https://github.com/opensafely-core/ehrql/blob/5f36cc0c99397ab07e1b …
> Add interactive-templates update workflow

- staff/views/applications.py
4371e7e modified `ApplicationList.get_queryset` to return a list, rather than an evaluated query set (the result of passing an unevaluated query set to django-zen-queries' `fetch` function). Doing so meant that `ApplicationList.context_object_name` was not set, which meant that the corresponding template no longer had `application_list` in its context, which meant that the list of applications was empty.
Thanks, @LiamHart-hub for reporting this issue.
> Fix `ApplicationList` view

- staff/views/projects.py
- staff/views/users.py
- tests/unit/staff/views/test_projects.py
- tests/unit/staff/views/test_users.py
This removes zen queries from the remaining places that it's used in the staff area.
Refs #4391.
> Replace zen queries in the staff area

- assets/src/scripts/_datatable.js
- templates/_components/index.html
- templates/_components/table/table.html
Reverting the previous commit and adding custom per-page pagination in the right way.
window.initCustomTable is exposed, so we can just pass a custom
per-page value into it, rather than depending on a data attribute.
This way it will also work with htmx.
> Custom per-page datatables

- package-lock.json
- package.json
- vite.config.mjs
Add [vite-plugin-live-reload](https://github.com/arnoson/vite-plugin-live-reload/) to Vite config. This allows the page to reload when the template HTML files are changed, for example when HTML classes are changed for Tailwind styling.
This is required as [django-browser-reload has been removed](https://github.com/opensafely-core/job-server/pull/4472).
> Add Vite plugin for automatic browser reloads

- jobserver/settings.py
- jobserver/urls.py
- justfile
- requirements.dev.in
- requirements.dev.txt
- requirements.prod.in
- requirements.prod.txt
Although making django-debug-toolbar (DDT) a development dependency introduces branches in `settings.py` and `urls.py`, which we have tried to avoid in the past (e.g. bfdc66f), it nevertheless makes our production deployment more secure. Depending on DDT only in development is also clearer than depending on it in production and in development, but indirectly disabling it in production via `settings.INTERNAL_IPS`.
This commit takes inspiration from opensafely-core/airlock#131 and isolates specific DDT-related settings from general debug-related settings. It does this with the `DJANGO_DEBUG_TOOLBAR` environment variable and the `DEBUG_TOOLBAR` setting (the `DJANGO_` prefix is dropped from the setting, as it's unnecessary). For safety, the setting is `False` by default. Because seeing DDT is …
> Make django-debug-toolbar a development dependency

- jobserver/jobs/daily/clearsessions.py
- jobserver/jobs/daily/update_repo_has_github_outputs.py
- jobserver/jobs/hourly/dump_db.py
- jobserver/jobs/weekly/notify_impending_copilot_support_windows.py
- services/sentry.py
- tests/unit/services/test_sentry.py
> Monitor cron jobs with Sentry

- jobserver/views/job_requests.py
- tests/unit/jobserver/views/test_job_requests.py
Here I've removed Zen Queries from JobRequests.
I couldn't find a sensible way to avoid the extra query in the template, but I'd be open to ideas if anyone can see anything obvious. I could add the line: `jobs = list(jobs)` and that does work, but it seems messy for very little gain. There's no performance impact that I can see to having the extra query in the template at the moment.
> Remove zen queries in the Job Request View

- services/sentry.py
- tests/unit/services/sentry_event_cron_error.json
- tests/unit/services/sentry_event_cron_in_progress.json
- tests/unit/services/test_sentry.py
Sentry cron check-in events (#4421) contain float-typed fields which the `parse()` method would try to iterate whilst searching for sensitive tokens, causing an error.
The tokens listed in this method are all strings so safe to exclude floats for now.
> Exclude floats from sensitive token checking

- templates/applications/page.html
But only when the application is ongoing. This preserves existing data. The first commit doesn't indent the `<fieldset>`, such that the diff highlights the change. The second commit does so.
Closes #4486
> Remove checkbox from "Service evaluation or audit"

- jobserver/models/job_request.py
This was removed in #4484 from the View and replaced with a unit test using Django's assert_num_queries fixture, so it's no longer needed in the model.
Refs https://github.com/opensafely-core/job-server/issues/4391
> Remove use of zen queries

- jobserver/models/project.py
- jobserver/views/projects.py
- tests/unit/jobserver/views/test_projects.py
I've removed zen-queries from anything related to Projects. Only Users are left now!
Refs [#4391](https://github.com/opensafely-core/job-server/issues/4391)
> Remove zen queries projects

- CHECKS
- app.json
Fixes #4489.
`WAIT` was originally the time to wait before running the first check as explained, for example, in this old Dokku documentation page:
https://dokku.com/docs~v0.3.26/checks-examples/
This now corresponds to `initialDelay` in the `app.json` health check:
> Number of seconds to wait after a container has started before triggering the healthcheck.
(`wait` in `app.json` corresponds to the time between check attempts, which doesn't, from my reading, seem to have been configurable in the old `CHECKS` configuration. That is, a subsequent check would occur immediately after a failed check.)
> Move health check to `app.json`

- jobserver/authorization/__init__.py
- jobserver/authorization/roles.py
- staff/views/users.py
- templates/staff/user/role_list.html
- tests/unit/jobserver/api/test_jobs.py
- tests/unit/jobserver/authorization/test_mappers.py
- tests/unit/staff/views/test_users.py
This removes the unused OrgCoordinator role and the one remaining reference of org roles in the UI.
This does not remove the role field from the OrgMembership class, which is a bigger change involving a migration and will be done separately.
Refs #4198
> Remove unused OrgCoordinator role

- jobserver/auth_pipeline.py
- tests/unit/jobserver/test_auth_pipeline.py
We don't subsequently use these tokens and their unnecessary storage in the database represents a potential security risk.
Fixes #4222
> Don't store user GitHub access-tokens in db

- jobserver/views/workspaces.py
- tests/unit/jobserver/views/test_workspaces.py
bug: workspaces with private repos will show the "admin section" to all users regardless of their permissions.
cause: the display logic is to check that the repo is private OR the user has one of two relevant permissions.
fix: this changes the display logic to check that the repo is private AND the user has one of two relevant permissions.
> Only show repo sign off button to permissioned users

- DEVELOPERS.md
Fixes #4339.
In #4339, it was proposed to remove this package, but it was decided that it was better to retain `django-upgrade` and provide some documentation for developers.
> Document use of `django-upgrade`

- justfile
The advised command `python manage.py migrations` doesn't exist.
It should be `python manage.py migrate`
> Fix migrations command advice in justfile

- docs/adr/0023-deployment-administrator-role.md
- jobserver/authorization/roles.py
- jobserver/migrations/0003_remove_global_projectdeveloper.py
- tests/unit/staff/views/test_users.py
Remove global assignment of the `ProjectDeveloper` role and replace with a dedicated Deployment Administrator role.
> Remove ProjectDeveloper global role

- .pre-commit-config.yaml
- applications/migrations/0002_add_short_data_report.py
- applications/migrations/0003_add_read_analytic_methods_policy.py
- jobserver/management/commands/create_workspace.py
- jobserver/migrations/0001_squashed_2024_06.py
- jobserver/settings.py
- jobserver/views/components.py
- justfile
- manage.py
- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/unit/airlock/test_issues.py
- tests/unit/airlock/test_views.py
Fixes #4542.
`ruff format` is considerably faster than `black`, while maintaining almost entirely the same formatting output. After deleting the cache for both and running against job-server commit 241415f7c70a1b6b8b1327ab047b5f5fd646f3b6:
```
$ time ruff format .
warning: The following rules may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding them to the `ignore` configuration.
9 files reformatted, 402 files left unchanged
real	0m0.073s
…
$ time black .
All done! ✨ 🍰 ✨
411 files left unchanged.
real	0m1.345s
…
```
(Note: the Ruff warning is fixed in this PR; it's because the configuration's not updated on the `main` branch where I …
> Switch from `black` to `ruff format`

- jobserver/forms.py
- tests/unit/jobserver/test_forms.py
For much, but not all, of job-server's life, one repo could be associated with one project. However, there are now a small number of repos that should be associated with two projects: these repos have "legacy" and "transitional" projects. To accommodate these repos, we change the repo-project relationship from one-to-one to one-to-many.
Are you expecting to see changes to a model? And not expecting to see changes to a form? The repo-project relationship was actually one-to-many early in job-server's life, so the database already contains several repos that are associated with two projects. For this reason, the one-to-one repo-project relationship was enforced within a form and not within a model.
Are you concerned that we may no longer be supporting an important use-case? The original …
> Change repo-project from one-one to one-many

- jobserver/auditing/presenters/base.py
- jobserver/management/commands/list_missing_repos.py
- jobserver/nav.py
- staff/views/repos.py
- tests/conftest.py
See #4532.
This goes a little bit towards removing `attrs` as a direct dependency. Apart from the two cases mentioned in the commit message, we're not using it in any exotic way.
It also makes the code clearer as using the standard Python dataclasses. It means there's less question on a code reader's part as to why `attrs` is being used.
> Reduce use of `attrs`

- DEVELOPERS.md
- applications/migrations/0001_initial.py
- applications/models.py
- interactive/migrations/0001_initial.py
- interactive/models.py
- jobserver/migrations/0001_squashed_2024_06.py
- jobserver/models/job_request.py
- jobserver/models/project.py
- jobserver/models/publish_request.py
- jobserver/models/release.py
- jobserver/models/release_file.py
- jobserver/models/release_file_review.py
- jobserver/models/repo.py
- jobserver/models/report.py
- jobserver/models/snapshot.py
- jobserver/models/user.py
- jobserver/models/workspace.py
- pyproject.toml
- redirects/migrations/0001_initial.py
- redirects/migrations/0002_ensure_old_url_has_leading_and_trailing_slashes.py
- redirects/models.py
`CheckConstraint.check` was deprecated in favour of `CheckConstraint.condition` in 5.1. It will be removed in 6.0. 9c6329b temporarily ignored the deprecation warning, as it prevented us from bumping Django. We fix it here.
> Fix deprecation warning

- jobserver/views/jobs.py
- templates/job/detail.html
- templates/workspace/detail.html
- tests/unit/jobserver/views/test_jobs.py
There's no point linking directly to the relevant Airlock URL because we don't expect users to be accessing Job Server from within Level 4 going forward, and even you have Airlock open in a VM you can't copy/paste URLs across.
Instead we link to the Airlock docs and describe the location of the file. This replaces both the link the output viewer and the reference to the old "Level 4 file sync" directory.
Example:
Previously we restricted these links to only show for the TPP backend, but on the assumption that we will be running an instance of Airlock for every backend I have removed this restriction.
There's now a significant chunk of redundant code in Job Server relating to the "Level 4 files viewer". I'll make a separate ticket to track what needs removing here, and will tackle this in …
> Point to Airlock for viewing log outputs

- templates/_components/form/input.html
- templates/_components/form/select.html
- templates/_components/form/textarea.html
- templates/_components/index.html
- templates/applications/page.html
- templates/login.html
- templates/staff/application/list.html
- templates/staff/org/detail.html
- templates/staff/project/list.html
- templates/staff/redirect/list.html
- templates/staff/repo/list.html
- templates/staff/report/list.html
- templates/staff/user/list.html
- templates/staff/workspace/list.html
- templates/workspace/create.html
Closes #4290
Previously we were using a combination of properties to show the invalid states to users when the information they entered into a textarea or input was not valid. This included using a hidden placeholder to find if the user had entered content.
The [new `:user-invalid` pseudo-class solves this very issue](https://www.bram.us/2021/01/28/form-validation-you-want-notfocusinvalid-not-invalid/#v5) and means that hack is no longer required.
Whilst browser support for this pseudo-class is recent, this is an additive feature, so users will still be alerted if they have not filled in a required field, but the browser will highlight this for them on form submit.
> Remove requirement for blank placeholder

- templates/job/detail.html
This has only just been created, hence why we didn't link to it earlier.
> Link to more appropriate Airlock docs page

- pyproject.toml
- services/logging.py
- templates/project/detail.html
- templates/project/event_log.html
- templates/staff/application/approve.html
- templates/staff/application/list.html
- templates/staff/project/membership_create.html
- templates/user/event_log.html
- tests/factories/project.py
- tests/integration/test_interactive.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/jobserver/views/test_workspaces.py
- tests/unit/services/test_logging.py
- tests/unit/staff/views/test_projects.py
Previously, messages about missing context variables were ignored. This was because the `django.template` logger logged them as `DEBUG` messages ([1][]), but the `django` logger (the parent of the `django.template` logger) sent only `INFO` messages (or higher) to the console.
Now, the `django.template` logger sends `DEBUG` messages (or higher) to the `missing_variable_error` filter. This filter always returns `False`, meaning that messages are (still) not sent to the console. However, it also converts messages about missing context variables to warnings.
pytest catches warnings during, and displays them at the end of, test sessions ([2][]). So, if a template is missing a context variable, and the template response associated with the template is tested, then pytest should tell us, …
> Warn if templates are missing variables

- jobserver/forms.py
- jobserver/middleware.py
- tests/unit/jobserver/test_forms.py
Fixes #4562.
This removes most uses of `pragma: no branch` from production code.
We decided to leave one exemption in the code, as it makes sense in context: we never expect that alternate execution branch to happen. See [the discussion](https://github.com/opensafely-core/job-server/pull/4603#discussion_r1757340223).
> Remove most uses of `pragma: no branch`

- templates/staff/project/membership_create.html
- templates/staff/project/membership_edit.html
- templates/staff/user/role_list.html
Making it clearer what the checkbox value is, versus the description.
> Update role and permissions checkbox styles

- jobserver/views/projects.py
- tests/unit/jobserver/views/test_projects.py
Fixes #4534 
I don't believe retrying in case of a `TimeoutError` here is necessary for this feature, but am happy to be convinced otherwise. For now, this just handles it and provides a "Github API unavailable" placeholder `Repo` for the relevant bit of the template
> Project page doesnt load when GitHub api is unreachable

- .github/workflows/deploy.yml
- .github/workflows/main.yml
This fixes a problem identified in #4607.
It was possible to have multiple `main` workflow runs simultaneously. GitHub's `concurrency` option was set on the actual `deploy` job in that workflow. However, it's possible that for runs started close in time, that a later run actually gets to the `deploy` job before the earlier one.
Instead, we lock the entire deploy workflow, separating out the tests into a reusable workflow to avoid duplication.
> Set `concurrency` on entire deploy

- redirects/middleware.py
- tests/unit/redirects/test_middleware.py
> Fix circular redirects caused by wildcards in paths

- .pre-commit-config.yaml
pre-commit's `default_language_version` should have been bumped from 3.11 to 3.12 almost exactly a year ago (c1759e89), but it was missed. Those with a python3.11 binary won't have noticed, but those without, like @KatieB5, would. Thank you for spotting this, Katie!
> Fix `default_language_version`

- docs/0024-grant-projectdevelopers-view-released-files.md
- jobserver/authorization/roles.py
- tests/unit/jobserver/api/test_jobs.py
People assigned the ProjectDeveloper role have permission to view unreleased files, they therefore have permission to view the less-sensitive released files
This change removes the need to assign both of these roles to researchers working on a project.
Closes #4519
> Permit ProjectDeveloper to view released files

- tests/unit/jobserver/test_forms.py
In this PR, we make a couple of small changes to two tests. These small changes help us see that the two tests are basically the same, save for two parameters. We then parameterise one test and remove the other, meaning we have the same tests for 14 fewer lines of code.
We use the [`pytest.mark.parametrize`](https://docs.pytest.org/en/latest/how-to/parametrize.html#pytest-mark-parametrize) decorator to parameterise the test, also using [`pytest.param`](https://docs.pytest.org/en/latest/reference/reference.html#pytest.param) to assign a more descriptive ID to each parameter set. Doing so also makes it easier to run the test with either parameter set:
```sh
pytest tests/unit/jobserver/test_forms.py::test_workspacecreateform_success[lower_case_name]
pytest …
```
> Parametrize `test_workspacecreateform_success`

- jobserver/management/commands/create_user.py
- tests/conftest.py
- tests/unit/applications/test_views.py
- tests/unit/interactive/test_models.py
- tests/unit/jobserver/authorization/test_decorators.py
- tests/unit/jobserver/management/commands/test_create_user.py
- tests/unit/jobserver/test_context_processors.py
- tests/unit/jobserver/views/test_job_requests.py
- tests/unit/jobserver/views/test_jobs.py
- tests/unit/staff/views/dashboards/test_copiloting.py
- tests/unit/staff/views/dashboards/test_index.py
- tests/unit/staff/views/dashboards/test_projects.py
- tests/unit/staff/views/dashboards/test_repos.py
- tests/unit/staff/views/test_analysis_requests.py
- tests/unit/staff/views/test_applications.py
- tests/unit/staff/views/test_backends.py
- tests/unit/staff/views/test_index.py
- tests/unit/staff/views/test_job_requests.py
- tests/unit/staff/views/test_orgs.py
- tests/unit/staff/views/test_projects.py
- tests/unit/staff/views/test_redirects.py
- tests/unit/staff/views/test_reports.py
- tests/unit/staff/views/test_repos.py
- tests/unit/staff/views/test_researchers.py
- tests/unit/staff/views/test_sentry.py
- tests/unit/staff/views/test_users.py
- tests/unit/staff/views/test_workspaces.py
Resolves #4604.
#4639 re-named the CoreDeveloper role to StaffAreaAdministrator. Direct references were updated. There are a couple of places with vestigial indirect references. In the management command `create_user` `--core-developer` flag and the `pytest`  fixture `core_developer` and therefore throughout `tests/`. Let's tidy these up as the vestigial references are potentially confusing and unclear. Better to reference the new role name.
> Tidy CoreDeveloper vestigial indirect references.

- DEVELOPERS.md
Inspired by #4668. There I changed a management command's parameters. It was used in Airlock. The change was breaking for their CI. Document that devs may want to think about this kind of knock-on effect.
> Add note that management command changes may affect other repos

- jobserver/views/job_requests.py
- tests/unit/jobserver/views/test_job_requests.py
Fixes #3704.
The `job-request-detail` template doesn't display the rendered project YAML if the context flags `project_yaml` sub-key `is_too_large` (from #3870, which was also towards #3704). Therefore the view code doesn't need to render the definition in that case. Doing so was slowing down page rendering by 5 or more seconds in some cases.
The extant code arbitrarily defined "large" as longer than 10,000 characters, but the comments mentioned ~1MB , which doesn't match. I've updated the comment. I've not considered updating the arbitrary value used.
As well as a unit test for the "too large" case, I added one for the rendering actually taking effect, as it was missing. And added checks that the `project_yaml` `is_too_large` or `is_empty` are as they should be in the other "happy path" …
> Don't render large YAML in JobRequestDetail view.

- jobserver/management/commands/create_user.py
The docstring was referring to `Workspace`, which is incorrect. Correct it to mention `User` instead.
Add a help text briefly explaining the purpose of the command.
Update the username argument help text to mention this `User` will be EITHER created OR updated.
> Fix `create_user` management command docstring and help text.

- .github/dependabot.yml
- Group npm dependabot updates in to development and production PRs
- Set the update interval to daily to test this process
- Set the time to check for updates to 1pm for testing purposes
> Use group for dependabot npm updates

- .github/dependabot.yml
https://github.com/opensafely-core/job-server/pull/4694 and https://github.com/opensafely-core/job-server/pull/4695 proved to be a success, therefore we can now return to weekly dependency checks.
> Switch to weekly dependabot checks for npm dependencies

- jobserver/forms.py
`ResetPasswordForm` has not been referenced since #2750 / commit [5ff6e215527236fd3ac30ed664f15d8995808206](https://github.com/opensafely-core/job-server/pull/2750/commits/5ff6e215527236fd3ac30ed664f15d8995808206#diff-5ed5b91c7902cf27c8ac19b378638c4de79c0d87140fb789faaf073599590413L27) removed the `ResetPassword` view. It appears that not removing the form was an oversight.
> Remove unused `ResetPasswordForm`

- jobserver/views/workspaces.py
- staff/views/dashboards/repos.py
- templates/staff/dashboards/index.html
- templates/staff/dashboards/repos.html
- templates/workspace/detail.html
We display warnings to the user when they are viewing a workspace attached to a private repo nearing their public release date. Provide a link to the policy documentation in these messages.
Explain the related policy and process on the private repo dashboard, and add explanations in the relevant code sections with links to the policy document. Existing information did not make this clear.
Here is [the policy](https://docs.opensafely.org/repositories/#when-you-need-to-make-your-code-public) and a (Bennett internal) [Slack thread](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1730106471692929) discussing this and other dashboards. 
The template changes can be tested locally by visiting the [dashboard](http://localhost:8000/staff/dashboards/) and by editing the `WorkspaceDetail` view …
> Document and link to private repo policy

- airlock/views.py
- jobserver/github.py
- jobserver/views/projects.py
- jobserver/views/repos.py
- jobserver/views/workspaces.py
- staff/views/dashboards/copiloting.py
- tests/fakes.py
- tests/unit/airlock/test_views.py
- tests/unit/jobserver/views/test_projects.py
- tests/unit/jobserver/views/test_repos.py
- tests/unit/jobserver/views/test_workspaces.py
- tests/unit/staff/views/dashboards/test_copiloting.py
- tests/verification/test_github.py
- tests/verification/test_opencodelists.py
- tests/verification/test_utils.py
- tests/verification/utils.py
Fixes #4635.
This standardizes error handling across views that use the GitHub API by transforming common connection/request-related exceptions into subclasses of `GitHubError`. As a result, views can now catch these exceptions consistently without depending on the internal details of `github.py`.
Views previously catching various `requests` exceptions are now updated to handle `GitHubError`, providing the same improvement applied in #4591 to one particular case.
Updating all API clients is substantial and should likely be tracked as a separate issue.
I introduced an additional fake API that raises such errors and changed tests to use it instead of each test ad-hoc defining their own. This is more consistent and less duplication.
I would further like to:
* Make the fakes into fixtures …
> Handle GitHub api problems consistently

- jobserver/forms.py
- tests/unit/jobserver/test_forms.py
`WorkspaceCreateForm.branch` is a `ChoiceField`, meaning that its `validate` method, which validates that the input is in its `choices` property, is called before its `clean` method. Consequently, unless its `clean` method is called directly, the `ValidationError` is inaccessible.
To put that another way, the `ValidationError` is inaccessible because it's raised by `Form.clean()`, but validation failed at `Field.validate()`. Django's [Form and field validation](https://docs.djangoproject.com/en/5.1/ref/forms/validation/) page would benefit from a diagram. Essentially:
1. `Field.clean()`
1. `Field.to_python()`
1. `Field.validate()`
1. `Field.run_validators()`
1. `Form.clean_<fieldname>()`
2. `Form.clean()`
I'd suggest working backwards through this PRs commits.
> Remove inaccessible `ValidationError`

- jobserver/authorization/global_roles.py
- staff/views/users.py
- tests/unit/jobserver/authorization/test_global_roles.py
Fixes #4632
Previously the Users page in the Staff Area had a "Filter by global roles" option which displayed all roles rather than just globally assignable roles. This commit adds a `global_roles` module so that the view does not need to know the details of the implementation.
> Filter by global roles

- TESTING.md
- tests/fakes.py
- tests/verification/test_github.py
- tests/verification/test_opencodelists.py
- tests/verification/test_utils.py
Fix some issues in verification tests due to #4717.
Verification tests aren't run on branch/merge CI as the ones that hit the remote APIs are costly. I must have overlooked some issues locally (coverage) and/or introduced the error manually between locally testing and committing in #4717.
> Fix `GitHubAPI` fakes verification tests

- DEVELOPERS.md
This command is simpler than a DB shell and helps new developers get familiar with a useful tool. I’ve used the -s switch instead of --staff-area-administrator for ease of typing and memorability. Once familiar with the short form, developers may not need to refer back to these docs.
> Document use of management command for initial admin user setup

- jobserver/forms.py
- tests/unit/jobserver/test_forms.py
Inspired by #4725, this PR removes more unreachable validation code in `WorkspaceCreateForm`.
The validation in question is already covered by identical checks in `__init__`, making it redundant and unreachable during the form’s normal lifecycle.
The previous test accessed it by creating an unbound form (without a `data` parameter) and then manually altering `cleaned_data` before calling `clean` directly. That's not a reasonable form lifecycle. An unbound form shouldn't invoke `clean`, nor should it be 'converted' to bound by adjusting variables post-instantiation. `cleaned_data` is public for reading purposes, not writing. Code that uses this form would not be able to reach these lines of code without being unreasonable.
> Remove unreachable `WorkspaceCreateForm` validation

- TESTING.md
It's not completely obvious that the database is enabled by default and tests that don't require it should declare that. Document this so test authors are more likely to be aware.
For an example of where I didn't get this right initially, see #4717 / f12a356c757910f537bec323caaedc4dab2c96e8.
> Document testing use of `@pytest.mark.disable_db`

- jobserver/forms.py
PRs #4725 and #4730 have made this method redundant. Let's remove it.
Closes #4593
> Remove `WorkspaceCreateForm.clean`

- jobserver/github.py
- tests/verification/test_github.py
This fixes a failing verification test.
> Handle `None` gracefully in repository topics

- requirements.prod.in
- requirements.prod.txt
We suspect [whitenoise PR #612](https://github.com/evansd/whitenoise/pull/612) may resolve an issue with the database connection intermittently and randomly closing during [requests observed in production](https://ebm-datalab.sentry.io/issues/?project=5443358&query=%22the%20connection%20is%20closed%22&referrer=issue-list&statsPeriod=90d).
For some reason, Dependabot did not automatically make this upgrade, but it appears to work without issue in local testing.
Investigation done:
- I didn't see anything obvious in requirements*.txt or pyproject.toml or dependabot.yaml explicitly limiting the version update. I don't see a *.lock file.
- Dependabot seemingly did manage to raise this PR to update Airlock from 6.6 to 6.7 but the change was made manually along with many others in Upgrade all …
> Upgrade `whitenoise` from 6.3.0 to 6.8.2

- docker/dependencies.txt
The distutils module has been deprecated for some time and was removed in Python3.12[^1]. A recent update to deadsnakes means that the package is no longer available at all and is breaking the build. Removing the package doesn't appear to break anything and it's likely that everything has already been moved over to setup tools.
[^1]: https://peps.python.org/pep-0632/#migration-advice
> Remove Python distutils

- jobserver/settings.py
First attempt to stop Django throwing a `TooManyFieldsSent` error when a job request has a very large number of jobs to be submitted.
Closes #4752
> Increase number of request parameters to 2000

- static/robots.txt
Tell bots to hit our site no more than one every two seconds.
We're currently seeing higher than normal traffic on the website and we think that may be due to a high number of bots. This should reduce the impact of any bot traffic and reduce the load on our server.
> Increase bot crawl delay

- requirements.prod.in
- requirements.prod.txt
Related to #4715 — by updating the OpenTelemetry dependencies, it might be possible to have the latest urllib3 without error.
> Update OpenTelemetry dependency subtree

- jobserver/releases.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/test_releases.py
Reuploads of the same release file (with same filename and same content) are prohibited. However, a file  with the same name/content may legitimately be reuploaded to a different workspace. Update the check for already uploaded files to check for the same filename/content within the target workspace only.
See [slack thread](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1736855700176509)
> Allow release file reuploads to different workspaces

- requirements.prod.in
- requirements.prod.txt
This is the latest v1 release.
See #4715. Hopefully this stops the Sentry issue described there from appearing again. This is a short-to-medium term sticking plaster as at some point we'll have to switch to v2.
> Revert urllib3 back to v1

- jobserver/api/releases.py
- jobserver/releases.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/test_releases.py
Airlock prevents users from adding an already released (via Airlock) file to a release request. This avoids unnecessary output-checking work re-reviewing files that have already been released. We may want to revisit that on Airlock later, but not just now.
However, currently Airlock only knows about files released via Airlock. If a file has been released pre-Airlock, Airlock will allow it to be added to the release request, and the job-server's check for already uploaded files prevents the release from being created.
This PR removes the check for already uploaded files, and also changes the `create_request` to a `get_or_create_request`, so we return an existing release with the same data if one matches.  It allows for the endpoint to be called by a different user (in the event that a …
> Allow release reuploads

- jobserver/releases.py
- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/test_releases.py
Releases should always be created by Airlock now, with an airlock id which is used as the release ID. We can filter for existing releases on release ID, and avoid filtering with requested_files, which is a json field and filtering works differently.
If we find an existing release with the airlock ID, we check the shas of the requested_files match.
> Check existing releases by ID

- requirements.dev.txt
- requirements.prod.in
- requirements.prod.txt
Fixes #4715.
We reverted to urllib v1 in #4806 to try and stop errors originating from OpenTelemetry's use of `urllib3`, via `requests`.
Apparently these errors did not occur with `urllib3` v1 previously, but that is no longer the case, and we'll have to find another solution to stop the errors, as in #4839.
> Use `urllib3` v2

- .github/workflows/update-dependencies.yml
- justfile
- scripts/upgrade-pipeline.sh
The internal pipeline library is not published to PyPI, and not tracked by dependabot.
Have been adding tooling to all repos that consume the pipeline library to automate bumping to new versions, as it's tedious and out of date version have caused issues in the past.
> Auto upgrade pipeline

- jobserver/api/releases.py
- tests/unit/jobserver/api/test_releases.py
It is currently unclear how we are going to configure this, but it is definitely not related to StaffAreaAdministrator.
Removing it to avoid potential footguns.
> Remove staff information from level 4 auth API

- airlock/emails.py
- airlock/views.py
- templates/airlock/emails/request_approved.html
- templates/airlock/emails/request_approved.txt
- templates/airlock/emails/request_released.txt
- tests/unit/airlock/test_emails.py
- tests/unit/airlock/test_views.py
Fixes #4855 
Airlock now releases files asynchronously, so an Approved request means that the release request has been approved and files will be uploaded in due course. Only when the last file is uploaded will the request change to Released. It therefore makes sense to send users notifications of the change of status to Approved.
This sends an email to the request author, adds a comment to the GitHub issue, and posts a notification to slack about the status change.
> Send notifications for Airlock approved events

- airlock/views.py
- tests/unit/airlock/test_views.py
Some updates to airlock notifications:
1) updates slack when a request is returned. 
Previously we didn't notifiy slack for returned requests, on the basis that the author gets emailed anyway, and the output-checker
already know that they returned it. However, it's useful to see the progress of a request if all notifications come to slack, either via issue creation/close or via an explicit post to slack. Currently the returned request is the only status change that doesn't update slack, so other output checkers would need to go to the issue or to L4 in order to check if someone else has returned it. This is more important now that a request can be returned before it's been fully approved.
2) Add tests for custom updates to come with the approved notification events from Airlock. We …
> Notify slack for returned release requests

- jobserver/views/index.py
- templates/index-authenticated.html
- tests/unit/jobserver/views/test_index.py
Closes #4871.
Confirmed that previous interactive analysis requests can still be seen in the event log.
> Remove homepage analysis requests card

- justfile
These tasks need to run fairly often -- whenever making model changes or pulling migrations.
> Add `justfile` recipes to make and apply migrations

- justfile
I regularly find myself wanting to run a Django management command with the devenv's environment with something like `.venv/bin/python3.12 manage.py command`. Let's add a recipe to make that slightly easier.  I was going to add a `dbshell` management command, then realized a general-purpose `manage` command is probably more useful than adding separate recipes.
> Add `justfile` recipe: run Django management command

- .github/ISSUE_TEMPLATE/default.md
This is intended to make it easier for us to create issues that are inline with the delivery tasks guidance and to help ensure we have the information we need when picking up the issue.
> Create a default issue template

- services/sentry.py
- tests/unit/services/test_sentry.py
Relates to #4858.
This has now been removed entirely from the code, the token removed from the deployment environment and the token deleted (was already expired).
> Replace use of `INTERACTIVE_GITHUB_TOKEN`

- tests/unit/jobserver/views/test_job_requests.py
The outputs of `generate-dataset` must always be marked `highly_sensitive` and the pipeline library now enforces this.
> Fix invalid test data

- airlock/issues.py
- airlock/slack.py
- airlock/views.py
- tests/unit/airlock/test_views.py
This improves the airlock notifications so that when there are multiple notification actions (github/email/slack), an error in one action doesn't prevent others happening.
> Better airlock notification error handling

- jobserver/settings.py
The use of this was removed in 02a266da9db799bfec3e6eb8031d76008be6352d, but removing the setting was missed.
> Remove unused `LOCAL_GIT_REPOS` setting

- DEVELOPERS.md
- interactive/models.py
- tests/unit/interactive/test_models.py
We can no longer publish an Interactive report or view its content, so these methods are unused and can be removed.
> Remove some Interactive report functionality

- jobserver/models/project.py
- tests/unit/jobserver/models/test_project.py
This is no longer used following
69515eb6284ca77f019f8f266239dfc7d37597bd, but was overlooked.
This also removes the `interactive_slug` property which was only used in `interactive_workspace`.
> Remove vestigial `interactive_workspace` property

- services/sentry.py
We get sporadic single failures of the dump_db job.
This generates a lot of noise of new issues in Sentry.
They tend to be singular failures (i.e. followed by a successful run), by making the failure threshold 2 we will only get notified if two in a row fail.
> Increase sentry cron failure threshold

- jobserver/forms.py
- jobserver/urls.py
- jobserver/views/users.py
- tests/unit/jobserver/views/test_users.py
Fixes #4939.
This removes the `LoginWithToken` view and `TokenLoginForm`. These are no longer needed since users now login to Airlock with tokens.
> Remove `LoginWithToken`

- jobserver/authorization/permissions.py
- jobserver/authorization/roles.py
All interactive-related code that relied on this permission has now been removed.
> Remove un-used analysis_request_view

- jobserver/templatetags/querystring_tools.py
- tests/unit/jobserver/templatetags/test_querystring_tools.py
This isn't used anywhere.
Looks like the last/only client was removed in:
- pull https://github.com/opensafely-core/job-server/pull/199
- commit 13858142d117a3d3e3ee1b39f121f45e1b61e7f7
> Remove unused templatetag `redirect_with_querystring`

- tests/unit/jobserver/api/test_releases.py
- tests/unit/jobserver/models/test_paired_fields.py
We removed that model in #4962. See commit messages for specifics.
Partially fixes #4873.
> Tidy up two bits of test code that referred to Interactive `AnalysisRequest`

- jobserver/models/workspace.py
- tests/unit/jobserver/models/test_workspace.py
There are no remaining clients of this.
It looks like #4905 removed the last client: `show_interactive_button = is_interactive_user and workspace.is_interactive` in `WorkspaceDetail.get`.
Partially fixes #4873.
> Remove `Workspace.is_interactive`

- tests/unit/jobserver/commands/test_projects.py
The difference between these tests is that one of them passes the optional `copilot` and `application_url` parameters to the command and one of them doesn't. Change the names to reflect that.
I don't see how these differences should lead to a project being called "interactive" or "standard". And in any case, we're sunsetting Interactive (docs/adr/0029-sunset-osi-interactive.md), but it's still valid for a `Project` to have these attributes, or not; and the command still has those options. We will still want this for testing projects, for example.
Part of  #4873.
> Re-name tests

- tests/integration/test_applications.py
- tests/unit/applications/test_models.py
- tests/unit/jobserver/models/test_project.py
- tests/unit/jobserver/models/test_release_file.py
- tests/unit/jobserver/models/test_repo.py
- tests/unit/jobserver/models/test_user.py
- tests/unit/jobserver/models/test_workspace.py
- tests/unit/redirects/test_models.py
Marking the dozen slowest test cases not already marked as `slow_test` speeds `just test` from about 20-25s to 12-16s for me locally (six workers). This shortens some feedback loops when doing local development. Delaying these tests to CI (or `just test-ci`) has low cost because they are testing isolated bits of code we're not actively developing.
Related to #4972.
> Mark some `slow_tests`

- DEVELOPERS.md
This change updates the docs to list the current state of setting up Job Server from scratch for local installs. There are still issues that need to be resolved, but are outside the scope of this PR.
> Update the developer documentation for fresh installs

- airlock/emails.py
- applications/emails.py
- jobserver/emails.py
- requirements.prod.in
- requirements.prod.txt
- tests/unit/airlock/test_views.py
The only thing we use the `incuna_mail` dependency for is wrapping creating and sending `EmailMultiAlternatives`. This is just a few lines of code we can write ourselves, so let's do that instead. The version added here is simpler than the `incuna_mail` wrapper and handles all our present use cases.
Resolves #4977.
> Remove `incuna_mail` dependency

- jobserver/slacks.py
This was used in the format message, as in:
4cfbec4bf32338c994bd9cc16f7d7ee914bea186.
but later replaced with use of the format specifier in:
475e00adfbdf326fe92e276a0a4962c6346b608c.
However, the vestigial code was not removed.
As a bonus, this eliminates a use of `no cover`.
> Remove unused `size` variable

- jobserver/models/user.py
- services/logging.py
- templates/job/detail.html
- templates/staff/user/list.html
- tests/unit/jobserver/models/test_user.py
This replaces the `user.all_roles` property with a `user.has_any_roles` property. It's effectively a rename because there should be no functional difference in practice.
Looking at the individual commits might be easier than the whole diff. I used an expand and contract strategy to add the new property and replace all usages of it, before removing the old one.
Fixes #4986.
> Refactor user.all_roles

- jobserver/commands/projects.py
- staff/forms.py
- staff/views/projects.py
- templates/staff/project/detail.html
- templates/staff/project/edit.html
- tests/unit/jobserver/commands/test_projects.py
This was never used so we should remove it.
As part of the Sunsetting OSI initiative (see `docs/adr/0029-sunset-osi-interactive.md`), we removed all OpenSAFELY
Interactive functionality from Job Server. The `application_url` field on a `Project` was added specifically for Interactive project applications. However, the standard application process was actually used, so this field was never
populated. We have no intention of using it in future.
See #5008. The model property and data migration will be in a separate commit/PR (https://github.com/opensafely-core/job-server/pull/5038), to reduce the risk of code relying on them being live while the migration has been deployed.
Note that the following instances of the string `application_url` do not need to be removed:
``` …
```
> Remove references to `Project.application url`

- .github/dependabot.yml
- .github/workflows/update-dependencies.yml
- justfile
- tests/test_requirements.py
Fixes #4412.
This switches from Dependabot to opensafely-core/update-dependencies-action for updating Python dependencies.
It reuses the existing workflow that was updating the `pipeline` dependency, and switches to updating weekly.
While looking at how this works for Airlock, it also borrow an improvements from Airlock with respect to updating dependencies. Specifically:
* the two `requirements.*.txt` files are checked for consistency of package versions, where packages are listed in both requirements files
> Switch from Dependabot to update-dependencies-action

- templates/_components/header.html
> Fix header logo outline ring

- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/conftest.py
- tests/test_network.py
- tests/test_requirements.py
- tests/verification/test_github.py
- tests/verification/test_opencodelists.py
Fixes #4989.
The two packages do broadly the same thing -- ensure tests don't access the network. `pytest-network` is not being actively developed, `pytest-socket` is. We probably benefit only marginally from updates to this package, but we may as well.
We could have instead written our own code to disable socket access to remove the dependency, but it's just tricky enough to get this right that it seems worth a development dependency (which has a lower cost-benefit barrier than a production dependency).
> Replace `pytest-network` with `pytest-socket`

- templates/applications/emails/submission_confirmation.html
A previous PR updated the text part but not the html part. This brings them back in line.
> Updated email template to remove references to COVID > non-COVID transition

- jobserver/honeycomb.py
- jobserver/views/jobs.py
- tests/unit/jobserver/test_honeycomb.py
- tests/unit/jobserver/views/test_jobs.py
We have changed the way cpu/memory telemetry is emitted in jobrunner, which breaks a couple of the current honeycomb links.
This change adds a new metrics link that uses the new metrics, and deprecates the old one.
These links are only shown to staff users, and typically only used by tech team members on tech-support or similar duties, as they require honeycomb access to work.
Related discussion: https://bennettoxford.slack.com/archives/C069YDR4NCA/p1747305282116539
> Update Honeycomb links for new telemetry

- airlock/issues.py
- jobserver/github.py
- tests/conftest.py
- tests/fakes.py
- tests/unit/airlock/test_issues.py
When a new release request is submitted on Airlock, we create a new issue for it. By default, this has either the "internal" or "external" label applied. However, non-opensafely output-checking repos may not have these labels, and if we try to create an issue with a non-existent label, we get a 403 from the github API.  We now check for labels on the relevant repo, and ignore any that don't already exist.
This was [reported](https://bennettoxford.slack.com/archives/C01UJLWNZJT/p1748510923798329) by a Bristol user (the only other org that currently do their own output checking)
> Ignore labels for airlock issues if they don't exist for the repo

- jobserver/api/jobs.py
This endpoint is having some performance issues when called with very large numbers of jobs and so reducing unnecessary work seems like a good idea. There's not an easy way to determine the production impact here ahead of time but:
* this is obviously safe because if we don't take the `newly_completed` branch then the `job` object is immediately discarded;
* it can't _hurt_ performance to not call `refresh_from_db()`.
So overall this seems worth trying.
Also worth noting that this call was only [introduced][1] to deal with problems with the notifications, so it's only ever been needed for this branch.
Slack discussion at:
https://bennettoxford.slack.com/archives/C069SADHP1Q/p1750839710327239?thread_ts=1750768496.173799&cid=C069SADHP1Q
[1]: …
> Only call `refresh_from_db()` when actually needed

- jobserver/settings.py
We set `X_FRAME_OPTIONS = "SAMEORIGIN"` to allow Job Server to iframe files on the Outputs Viewer application ([source](https://github.com/opensafely-core/job-server/blob/1d18a366aa4b78d048505b5bd7b3324d19c2f500/assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx)) – therefore changing that setting to deny is not right for us.
> Ignore security warning security.W019

- templates/job_request/detail.html
So that the job list can be used to debug the issue, rather than needing to click in to each job from the request to see the errors.
> For failed jobs add status and message to request

- jobserver/api/jobs.py
- tests/unit/jobserver/api/test_jobs.py
The last reference to this in the view code was removed in commit ddd62303f82d38347c88ccbc295dbf6186b16d8d when removing OpenSafely Interactive notifications. So it's no longer required.
> Remove unused GitHub API from `JobAPIUpdate` view

- TESTING.md
- pyproject.toml
- tests/conftest.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/verification/test_github.py
- tests/verification/test_opencodelists.py
- tests/verification/test_utils.py
The `enable_db_access_for_all_tests` fixture in `tests/conftest.py` wasn't working when tests were run in isolation. Change the approach to instead put `autouse=True` `db` fixtures in `tests/unit/conftest.py` and `test/integration/conftest.py` where they are needed.
Remove `disable_db` marker that disallowed test scopes from accessing the DB. There were no tests other than the verification ones that were marked up. They can get the same effect more simply by not being affected by the new `conftest.py`. They won't spin up a test database when run separately from the unit/integration tests.
> Enable `db` for unit/integration tests. Remove `disable_db`.

- jobserver/github.py
- tests/verification/test_github.py
We were seeing failures for job-server's verification tests more frequently recently.
It's easy when reading the logs to think that this is a rate limit issue on unauthenticated requests.
It *is*. But it also isn't.
This test specifically doesn't use the PAT that we use for testing. That means we're:
* subject to GitHub's low rate limits for unauthenticated users
* and running in GitHub Actions runners that probably often end up using GitHub's API frequently
Those two issues combined mean we often exceed the rate limit.
Our test in fact is supposed to handle the case where we're rate limited by GitHub, and pass successfully instead.
The problem is that our code doesn't quite handle the wrapping of the exception properly. It treats our custom `HTTPError` exception as the `requests` …
> Handle rate limit for unauthenticated request test

- jobserver/github.py
- tests/verification/test_github.py
[8aadbd4](https://github.com/opensafely-core/job-server/pull/5184/commits/8aadbd4d8a49d134427734ec016043551c6d2b53) sensibly moved the point at which an IssueNotFound error was raised, however, it needed to also update the check that should raise it. Fetching issue numbers by issue title returns a 200 with a count of 0 if the issue does not exist.
Verification tests are now [passing](https://github.com/opensafely-core/job-server/actions/runs/16720526450)
> Fix github verification tests

- jobserver/management/commands/cancel_jobs.py
- jobserver/management/commands/check_rap_api_status.py
- jobserver/rap_api.py
- tests/conftest.py
- tests/unit/jobserver/management/commands/test_cancel_jobs.py
- tests/unit/jobserver/management/commands/test_check_rap_api_status.py
- tests/unit/jobserver/test_rap_api.py
Fixes #5206.
Also adds `jobserver/rap_api.py` to centralize the code that actually makes the different API calls and their shared functionality.
> Add `jobserver/rap_api.py` and `cancel_jobs` management command.

- jobserver/views/index.py
- templates/_partials/latest-job-requests-table.html
- tests/unit/jobserver/views/test_index.py
This fixes #5183 which prevents `JobRequest` that come from inactive backends from appearing on the homepage.
1. _We've communicated our intent to do this to the service team so they're aware and can let us know if they think this damages transparency/publicity_ - Discussed this on [nod channel](https://bennettoxford.slack.com/archives/C068NDYALSF/p1756458662888819) and the team is happy with this change.
2. _We've decided how/which backends to exclude._ - We have decided to only display jobs run against backends that are marked as `is_active`. For now, tpp is the only one marked as active. More info on [this](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1755689793592179) and [this](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1756303389720579?thread_ts=1754379227.101509& …
> Exclude test backend job Requests on homepage

- jobserver/rap_api.py
- tests/unit/jobserver/test_rap_api.py
`cancel` needs to send a POST request to the RAP API.
Add tests that the endpoints actually use the right parameters, as well as how they handle the different status codes.
> Fix `cancel` API wrapper method and improve tests

- pyproject.toml
- tests/unit/jobserver/management/commands/test_unpublish_snapshot.py
46c67c7 added the `unpublish_snapshot` management command. For expediency, however, it did not add any tests. This commit adds them, and no longer omits `unpublish_snapshot` from coverage.
> Test the `unpublish_snapshot` management command

- jobserver/models/job_request.py
- jobserver/rap_api.py
- jobserver/views/job_requests.py
- jobserver/views/jobs.py
- staff/views/job_requests.py
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/jobserver/views/test_job_requests.py
Fixes #5216.
Currently the controller finds cancelled actions by looking at `JobRequest.cancelled_actions` via the `job-requests` API.
I searched for `cancelled_actions` and found that Jobs can be added to it from `JobCancel` and `JobRequestCancel` views. There are two versions of the latter, one in the staff area. All three are very similar. `JobCancel` directly edits `job.job_request.cancelled_actions` and `JobRequestCancel` calls `JobRequest.request_cancellation`.
The pages that use them (`Job` and `JobRequest` `DetailViews`) show a link to the `Cancel` views and accessing it does the work (if allowed) and redirects back to the same page, with messages.success and updated UI due to the changed DB state communicating the change to the user.
- make `request_cancellation` accept an …
> Cancel endpoint: use in UI for `Test` backend

- docker/justfile
`just docker/stop-db`
Closes https://github.com/opensafely-core/job-server/issues/5201
> Add a just command to stop the local dev database

- services/sentry.py
Fixes #5290, in conjunction with actually ensuring the variables are removed from Dokku.
This ensured they don't get sent to Sentry, but is not required when the variables no longer exist in Dokku.
> Remove old environment variables from Sentry

- jobserver/rap_api.py
On enter/exit main function. `json` is `DEBUG` level as may be large. And one log per error condition.
Simple enough automated tests don't seem worth it.
Success:
```
[debug    ] [jobserver.rap_api] endpoint_path=rap/cancel/ ip=127.0.0.1 json={'rap_id': 'upkadceiseprucwz', 'actions': ['generate_dataset']} request_id=017737a3-a9cf-446b-b709-e010ed0b0054 request_method=post user_id=348
[info     ] Success - exiting              [jobserver.rap_api] endpoint_path=rap/cancel/ ip=127.0.0.1 request_id=017737a3-a9cf-446b-b709-e010ed0b0054 request_method=post user_id=348
```
Error (webapp not available):
```
[debug    ] [jobserver.rap_api] endpoint_path=rap/cancel/ ip=127.0.0.1 json={'rap_id': 'upkadceiseprucwz', 'actions': ['generate_dataset']} request_id=10f9cb35-a4eb-4dd2-95d7-aa882a7c7e7d …
```
> Add `rap_api` logging

- jobserver/models/backend.py
- tests/integration/test_context_processors.py
- tests/unit/jobserver/models/test_backend.py
- tests/unit/jobserver/test_context_processors.py
We are updating the jobserver codebase so its database is updated with information provided by the RAP API (see [API docs](https://controller.opensafely.org/controller/v1/docs/#tag/backends) for the new structure of the backend status data). A new database field was added in #5324 and its data can now be used to render maintenance mode status information in the templates. As such, the `jobrunner_state` field in the database will soon become redundant.
Following the work done in #5285, this PR updates BackendManager and associated tests so that queries are now using the `is_in_maintenance_mode` field instead.
> Switch BackendManager and tests to use new database field

- services/logging.py
- tests/conftest.py
- tests/unit/jobserver/management/commands/test_cancel_jobs.py
- tests/unit/jobserver/management/commands/test_check_rap_api_status.py
- tests/unit/jobserver/models/test_job_request.py
- tests/unit/jobserver/test_copiloting.py
- tests/unit/services/test_slack.py
The `log_output` fixture uses `LoggingCapture()` with doesn't merge in local context vars by default. In order to do so, we need to configure it with `merge_contexvars` as the first processor
https://www.structlog.org/en/stable/api.html#structlog.contextvars.merge_contextvars
> Ensure logging context is captured in tests
