opensafely-core/job-server

jobserver/api/models.py
jobserver/forms.py
jobserver/settings.py
jobserver/templates/workspace_create.html
jobserver/templates/workspace_list.html
jobserver/urls.py
jobserver/views.py
requirements.in
requirements.txt

This adds a page with a form to create Workspaces. It's linked to from the Workspace list page.
Fixes #17

Add Workspace Page

---

jobserver/api/models.py
jobserver/forms.py
jobserver/templates/job_create.html
jobserver/templates/job_list.html
jobserver/urls.py
jobserver/views.py

This adds a page with a form to create Jobs. It's linked to from the Job list page.
Fixes #18

Add Job Page

---

jobserver/settings.py

This is a grab bag of general maintenance changes, all to settings.py:
* Group Django and third party settings
* Document where settings come from
* Turn debug off by default

Tidy Settings

---

.github/workflows/main.yml
.gitignore
Makefile
jobserver/forms.py
jobserver/settings.py
jobserver/templates/base.html
jobserver/templates/login.html
jobserver/urls.py
jobserver/views.py
pyproject.toml
requirements.in
requirements.txt
tests/factories.py
tests/jobserver/test_views.py

This improves a Users flow after logging in.  They are redirected to the workspace list page after logging in which will redirect them to the workspace create page if there are no workspaces to show.
However, an unauthenticated user visiting an empty workspaces list page will see an empty list instead.

Login Flow

---

jobserver/models.py

This removes the post-save signal for Job.
Signals can be tricky to debug.  Since this signal was only for one object it makes sense to make it generally availabe to the model and call it from the save.

Remove Signal

---

jobserver/management/commands/local_data.py

This adds a simple command to generate some dummy data for local testing.

Add command to generate dummy data

---

.gitignore
jobserver/models.py
jobserver/templatetags/status_tools.py
requirements.in
requirements.txt
tests/factories.py
tests/jobserver/templatetags/test_selected_filter.py
tests/jobserver/templatetags/test_status_tools.py
tests/jobserver/test_context_processors.py
tests/jobserver/test_models.py
tests/jobserver/test_runtime.py
tests/jobserver/test_views.py

This adds tests for all the low-hanging untested code.

Add More Tests

---

Dockerfile
requirements.in
requirements.txt

This adds SQLite tooling for dev and production SQLite access.

Add SQLite Tooling

---

jobserver/models.py
tests/jobserver/test_models.py

This adds tests for JobRequets custom methods.

Add JobRequest Tests

---

jobserver/templatetags/status_tools.py
static/css/main.css

Make the In Progress Icon Spin

---

pyproject.toml
tests/jobserver/templatetags/test_runtime.py
tests/jobserver/templatetags/test_status_tools.py
tests/jobserver/test_views.py

This is a grab bag of tests after I noticed coverage had dipped after some previous PRs failed to test code they added (oops!).
Each commit addresses a roughly single feature but I suspect viewing the entire diff should be fine since shouldn't be any overlapping chunks between commits.

More Tests

---

jobserver/templates/job_detail.html
tests/jobserver/test_views.py

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1952687026/?project=5443358&query=is%3Aunresolved)
This fixes JobDetail so it can render older style Jobs which are linked directly to Workspaces.

Fix JobDetail

---

jobserver/management/commands/local_data.py
jobserver/models.py
jobserver/templatetags/status_tools.py
jobserver/views.py
tests/jobserver/templatetags/test_status_tools.py
tests/jobserver/test_models.py
tests/jobserver/test_views.py

This rebuilds the `Job.is_*` and `Job.status` properties to correctly report the state of a Job.  A new `.is_finished` status has been added, with `.is_completed` and `.is_failed` building on top of it.
The JobRequest.is_*` and `JobRequst.status` properties have been updated to reflect changes in their relevant Job counterparts.

Fix Statuses

---

jobserver/context_processors.py
jobserver/templates/index.html

This wraps up the changes need for #185 after most of it was implemented in the work done in #216 
Fixes #185

Landing Page Tweaks

---

jobserver/models.py
requirements.in
requirements.txt
tests/jobserver/test_models.py

This handles v2 Job statuses at the JobRequest level, fixing the icons for JobRequests.
I _think_ I've covered all the possible status combinations, but some double checking would be much appreciated!
Fix #243

Aggregate Statuses to JobRequest

---

jobserver/views.py
tests/jobserver/test_views.py

Assign filtered queryset to variable

---

jobserver/models.py
tests/jobserver/test_models.py

This filters the jobs we look up when getting most recent status for a given action.
Fixes #295

Fix Action Statuses

---

jobserver/github.py
tests/jobserver/test_github.py

This enables us to consume more than 100 repos from the Researchers team (which has grown to 79 since the issue was filed!) using GraphQL's cursor-based pagination to walk the pages once we have over 100 repos in that team.
Tested with `first: 10` to make sure it does actually pull more than 10 repos!
Fixes #149

Consume GraphQL Pages

---

jobserver/models.py
jobserver/templates/workspace_detail.html
jobserver/views.py
static/css/main.css
tests/jobserver/test_models.py

This adds the latest JobRequest (if there is one _and_ it has Jobs) to the Workspace detail page, showing the requested actions, total runtime, and listing it's Jobs.
Ref #251

Add Latest Run JobRequest

---

jobserver/models.py

Fix the import removed by #315 
(subsequent work in #304 made use of it but #315 was applied without rebasing 🤦‍♂️)

Fix Missing Import

---

jobserver/templates/workspace_detail.html

_Sigh._
Fixes this lovely bit of UI:

Close Workspace's Details "row" div

---

jobserver/templates/job_request_detail.html

This adds Creator and Identifier to the JobRequestDetail page.
Fixes #337 
Fixes #336

Display More JobRequest Fields

---

jobserver/api.py
jobserver/emails.py
jobserver/models.py
jobserver/runtime.py
jobserver/templates/emails/notify_finished.txt
tests/jobserver/test_emails.py
tests/jobserver/test_runtime.py

This is a collection of small, self-contained, fixes to notifications as per #330

Notification Fixes

---

jobserver/templates/job_detail.html
jobserver/templates/job_request_list.html
jobserver/templates/workspace_log.html
jobserver/urls.py
jobserver/views.py
tests/jobserver/test_views.py

This is a list of small improvements I fixed while implementing #375.  Each commit is self contained so should be easy to review in isolation.

JobRequest List Improvements

---

jobserver/models.py

Simplify and further document how we bubble up status from a JobRequest's Jobs for use in the UI and other calculations.
The commits hopefully make this simpler to understand!

Simplify JobRequest.status Aggregation

---

README.md

* based on migration from dokku to dokku2

Create simple deployment instructions

---

.github/workflows/main.yml
Dockerfile

This pins the hadolint action and fixes the warnings raised in the latest version.
Fixes #464

Hadolint fixups

---

requirements.dev.in
requirements.dev.txt
requirements.in
requirements.txt

This moves litecli back into the production requirements since it's so useful on the server.

Install litecli in Production

---

jobserver/templates/base.html

This allows us to track usage of the site in a privacy-friendly way.

Add Plausible Analytics code

---

jobserver/templates/workspace_detail.html

This sets the value of each Backend's label/input for/id attributes using Django's `forloop.counter` templatetag.

Fix input/label IDs on WorkspaceDetail

---

jobserver/models.py

This adds docstrings to each model to show their intended use.

Add Model Docstrings

---

.github/workflows/main.yml
.pre-commit-config.yaml
Makefile
jobserver/authorization/admins.py
jobserver/authorization/fields.py
jobserver/views/projects.py
requirements.dev.in
requirements.dev.txt

This adds pyupgrade to catch syntax changes so I don't have to.

Add pyupgrade

---

jobserver/context_processors.py
tests/jobserver/test_context_processors.py

This adds a nav item for the Users section which was missed in #596

Add Users to Nav

---

DEVELOPERS.md
README.md

Move developer notes to separate file

---

jobserver/models.py
jobserver/views/job_requests.py
tests/jobserver/test_models.py

This modifies the JobRequest.status` property to make use of prefetch Jobs if they exist.  It avoids running duplicate queries when treating the status as a field and trying to filter on it.  The event log page was doing this and generating 2600+ (duplicate!) queries even for pages where the status filter produced no results.

Speed up Event Log

---

jobserver/views/job_requests.py

Small tweak to shave a load of queries off the list page.

Select backends to save looking them up for the backend badges

---

jobserver/context_processors.py
jobserver/settings.py
tests/jobserver/test_context_processors.py

Add scripts_attrs to the global template context

---

jobserver/authorization/fields.py
jobserver/authorization/utils.py
jobserver/models/core.py
jobserver/templates/user_list.html
jobserver/utils.py
jobserver/views/job_requests.py
jobserver/views/users.py
tests/jobserver/authorization/test_fields.py
tests/jobserver/authorization/test_utils.py
tests/jobserver/models/test_core.py
tests/jobserver/views/test_users.py

This adds search, filtering by backend access, and filtering by applied roles to the UserList page.  Roles filtering is a little involved due to the db field being a JSONField and SQLite not support Django's `__contains` expression, but I think the custom function makes the API workable.
Many thanks to @Ian-Foote for their help in creating the ORM function!

Better User Tooling

---

DEVELOPERS.md
Makefile

- Add frontend assets pipeline to developer docs
- Update `make setup` command to add `npm run build` for assets

Document frontend assets pipeline

---

jobserver/api/__init__.py
jobserver/api/jobs.py
jobserver/api/releases.py
jobserver/urls.py
tests/jobserver/api/test_api.py
tests/jobserver/api/test_jobs.py
tests/jobserver/api/test_releases.py

Only changes are moves and import clean ups, no actual code changes at all.

Breakout api.py into a package

---

jobserver/api/releases.py
jobserver/management/commands/release.py
jobserver/models/core.py
jobserver/models/outputs.py
jobserver/releases.py
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_release_list.html
jobserver/urls.py
jobserver/views/releases.py
tests/factories.py
tests/jobserver/api/test_releases.py
tests/jobserver/models/test_core.py
tests/jobserver/models/test_outputs.py
tests/jobserver/test_releases.py
tests/jobserver/views/test_releases.py

- Remove workspace current files from workspace releases view.
- Add get_api_url() and get_api_index_url() convention functions
- Refactor release files API

workspace files api

---

jobserver/management/commands/ensure_admins.py
jobserver/management/commands/release.py
jobserver/models/outputs.py
jobserver/releases.py
requirements.dev.in
requirements.dev.txt

This sets up a couple of new flake8 linting plugins to catch and guard against common nits.

Add Flake8 Tooling

---

jobserver/management/commands/release.py

It's also more dev friendly, as it will create default workspace and
users for you if you pass --create

Update release management command to use new models

---

jobserver/templates/workspace_detail.html

This gives privileged users a shortcut to the current outputs view for a workspace.
Fixes #700

Add Current Outputs Button

---

assets/src/styles/_fonts.scss

So that text is shown whilst font is loading.

Add missing font-display CSS

---

assets/src/scripts/outputs-viewer/components/Image/Image.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
assets/src/scripts/outputs-viewer/hooks/use-file.js

So that we can load images cross-origin.

Encode images with base64 to pass auth headers

---

pyproject.toml

This removes some ignored warnings which are no longer necessary.

Remove Unused Warning Ignores

---

jobserver/views/releases.py
tests/jobserver/views/test_releases.py

This adds a missed permissions check.  Good job we put the TODO in!

Gate Viewing a Release

---

jobserver/templates/403.html
jobserver/templates/404.html
jobserver/templates/500.html

So that users can see why an error has occurred and navigate away from the error page.

Add error page templates

---

jobserver/views/projects.py
tests/jobserver/views/test_projects.py

Stop assigning ProjectCoordinator on Project creation

---

.github/workflows/main.yml
.gitignore
assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
assets/src/scripts/outputs-viewer/tests/App.test.jsx
assets/src/scripts/outputs-viewer/tests/__mocks__/server.js
assets/src/scripts/outputs-viewer/tests/__mocks__/zustand.js
assets/src/scripts/outputs-viewer/tests/components/Button/Button.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Button/PrepareButton.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Button/PublishButton.test.jsx
assets/src/scripts/outputs-viewer/tests/components/FileList/FileList.test.jsx
assets/src/scripts/outputs-viewer/tests/components/FileList/Filter.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Iframe/Iframe.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Image/Image.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Metadata/Metadata.test.jsx
assets/src/scripts/outputs-viewer/tests/components/NoPreview/NoPreview.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Table/Table.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Text/Text.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Toast/Toast.test.jsx
assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx
assets/src/scripts/outputs-viewer/tests/empty-module.js
assets/src/scripts/outputs-viewer/tests/helpers/files.js
assets/src/scripts/outputs-viewer/tests/hooks/use-file-list.test.js
assets/src/scripts/outputs-viewer/tests/jest-setup.js
assets/src/scripts/outputs-viewer/tests/test-utils.jsx
babel.config.js
jest.config.js
package-lock.json
package.json

Closes https://github.com/opensafely-core/job-server/issues/711
💯 [100% code coverage](https://github.com/opensafely-core/job-server/runs/3382284306?check_suite_focus=true#step:7:23) ✅

Add tests to the Outputs SPA

---

assets/src/styles/main.scss
jobserver/templates/base.html
jobserver/templates/index.html
jobserver/templates/partials/alerts.html
jobserver/templates/partials/footer.html
jobserver/templates/partials/header.html

- Add a footer matching other OpenSAFELY sites
- Update header nav
- Use HTML partials for header and footer
- Use Oxford blue colours with Bootstrap

Update header, footer, and link styling

---

jobserver/authorization/__init__.py
jobserver/authorization/roles.py

This removes the SuperUser role now that it's no longer in use by any users.
Follow up to #635

Remove SuperUser Role

---

assets/src/styles/_utilities.scss
jobserver/templates/base.html
jobserver/templates/org_detail.html
jobserver/templates/partials/alerts.html
jobserver/templates/release_detail.html
jobserver/templates/workspace_backend_files.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_file_list.html
jobserver/templates/workspace_latest_outputs_detail.html
jobserver/templates/workspace_log.html
jobserver/templates/workspace_output_list.html
jobserver/templates/workspace_release_list.html

- Update Workspace templates
-  backend files
- detail
- file list
- latest outputs detail
- log
- output list
- release list
- Update release detail template
- Move alerts above the breadcrumbs
- Add `prose-width` util CSS class

Update and style workspace templates

---

jobserver/management/commands/release.py
jobserver/templates/workspace_file_list.html
jobserver/views/workspaces.py

Two lots of fixes found while reviewing #894

Misc Fixes

---

jobserver/templates/snapshot_detail.html

Update snapshot detail template to match new styling.

Update snapshot detail template

---

jobserver/templates/workspace_detail.html
jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

This fixes the public/private badges on the WorkspaceDetail page.

Fix repo badges on WorkspaceDetail

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

This reports jobs with the status message "Internal error" to Sentry as message events (instead of exceptions) so we can start getting notifications about them.

Notify Sentry About Jobs With an Internal Error

---

jobserver/emails.py

Move job status to the start of job notification email subject line

---

jobserver/forms.py
jobserver/templates/components/README.md
jobserver/templates/components/form_roles.html
jobserver/templates/components/form_text.html
jobserver/templates/project_create.html
jobserver/templates/project_invitation_create.html
jobserver/templates/project_membership_edit.html
jobserver/templates/project_settings.html
jobserver/templates/workspace_create.html
staff/templates/staff/user_detail.html

Initial working version of the form field "components".
Everything worked out well except for help_text, which now need to be defined in Django forms, not ideal but it's the one big con I've found here.

Form Field Component

---

jobserver/context_processors.py
jobserver/models/core.py
staff/forms.py
staff/templates/staff/org_detail.html
staff/templates/staff/org_edit.html
staff/templates/staff/org_list.html
staff/templates/staff/project_detail.html
staff/templates/staff/project_edit.html
staff/templates/staff/user_detail.html
staff/templates/staff/workspace_detail.html
staff/urls.py
staff/views/orgs.py
staff/views/projects.py
tests/unit/jobserver/models/test_core.py
tests/unit/staff/views/test_orgs.py
tests/unit/staff/views/test_projects.py

This is a grab bag of changes to the staff area:
* Fix the project detail page to show its workspace list
* Make projects editable
* Add orgs (detail, list, edit) to the staff area
* Update some links to point to pages in the staff area
* Allow members to be added to/removed from orgs

Misc Staff Area Fixes and Changes

---

applications/templates/application.html
applications/urls.py
applications/views.py
jobserver/settings.py
jobserver/templatetags/snippet.py
jobserver/urls.py
requirements.prod.in
requirements.prod.txt
snippets/application.md
tests/unit/applications/test_views.py

All of this is up for discussion, including:
* is the approach sensible?
* are things named properly?
* is the code in the right place?

Add an application page which renders contents of snippets/application.md

---

staff/views/users.py
tests/unit/staff/views/test_orgs.py

Misc fixes from feedback on #946

Staff Area Orgs Fixes

---

jobserver/templates/base.html
jobserver/templates/job_request_list.html
jobserver/templates/org_detail.html
jobserver/templates/project_detail.html

Responsive style fixes

---

jobserver/templates/workspace_latest_outputs_detail.html

Fix latest outputs download link

---

applications/templates/applications/apply.html
applications/templates/applications/confirmation.html
applications/templates/applications/page.html
applications/templates/applications/process_form.html
applications/templates/applications/terms.html
jobserver/templates/components/form_checkbox.html
jobserver/templates/components/form_radio.html
jobserver/templates/components/form_text.html
jobserver/templates/workspace_create.html

Use Bootstrap styles to improve UX and form styling.

Update styling on application form

---

applications/wizard.py
dotenv-sample

This improves the developer documentation around which env vars to set and what the WizardPage instances are doing in regards to ModelForm construction/usage.

Better docs

---

applications/templates/applications/apply.html
applications/templates/applications/page.html
applications/templates/applications/sign_in.html
applications/templates/applications/terms.html
snippets/sign_in.md
snippets/start_page.md
snippets/terms.md

For each page in both the form wizard, and the pages beforehand (apply, sign in, terms) this adds:
* a meta title relevant to the page
* breadcrumbs
* a jumbotron with the title and sub title of the page

Wizard Template Fixes

---

jobserver/templates/components/form_radio.html

Update the radio button markup:

Update Radio Button Layout

---

jobserver/urls.py
static/robots.txt

To stop crawlers from trying (and failing) to access certain areas of the site.

Add a robots.txt file

---

jobserver/templates/workspace_create.html

Corrected typo on workspace creation page

fix: wrokspace->workspace

---

.gitignore
assets/src/styles/_staff.scss
assets/src/styles/main.scss
staff/templates/staff/backend_detail.html
staff/templates/staff/backend_edit.html
staff/templates/staff/backend_list.html
staff/templates/staff/index.html
staff/templates/staff/org_detail.html
staff/templates/staff/org_list.html

Add staff area specific styling to the backends and organisations views.

Staff area styles for backends and organisations

---

assets/src/styles/main.scss
jobserver/templates/_job_requests.html
jobserver/templates/index.html

- Update the home page template
- Fix the container width on job request template

Update styles on home and job request templates

---

staff/templates/staff/backend_list.html
staff/templates/staff/index.html
staff/templates/staff/org_detail.html
staff/templates/staff/org_edit.html
staff/templates/staff/project_detail.html
staff/templates/staff/project_edit.html
staff/templates/staff/project_list.html
staff/templates/staff/user_detail.html
staff/templates/staff/user_list.html
staff/templates/staff/user_set_orgs.html
staff/templates/staff/workspace_detail.html
staff/templates/staff/workspace_list.html

- Update staff area templates
- Projects
- Workspace
- Users
- Tweaks and changes to other staff area pages

Staff area template and styling updates

---

applications/emails.py
applications/templates/applications/emails/submission_confirmation.txt
applications/views.py
tests/unit/applications/test_emails.py
tests/unit/applications/test_views.py

This sends the author of an Application a confirmation email when they submit their application.

Send Applicant an Email Confirmation

---

applications/templates/applications/confirmation.html

This was broken when switching from primary key to hash.

Fix broken "change" link

---

applications/form_specs.py
applications/templates/applications/application_list.html
staff/templates/staff/application_detail.html
staff/templates/staff/application_list.html
staff/templates/staff/user_detail.html

Two small fixes found while importing applications:
* study lay description was an `<input>`, switched to a `<textarea>`.
* Some vestigial uses of Application.pk switched to Application.pk_hash.
* Fix a typo

Application Fixes

---

app.json
jobserver/copiloting.py
jobserver/jobs/weekly/notify_impending_copilot_support_windows.py
jobserver/management/commands/run_scheduled_commands.py
pyproject.toml
tests/unit/jobserver/test_copiloting.py

This adds a function, wrapped in a command, to notify slack of Projects with a co-pilot support window which ends in <5 days.
The expectation is this will be run daily or weekly to avoid spamming the channel.
Fixes #1208

Notify Slack of Projects with Impending Lack of Co-pilot

---

assets/src/scripts/outputs-viewer/hooks/use-file.js
assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx

This reverts commit cbb2693a251d860cd05ee2a92e5a8afc2c934137 and fixes the test.

Revert "Replace base64 image with URL"

---

applications/templates/applications/confirmation.html
staff/templates/staff/application_detail.html

Preserve whitespace in application fields when rendering outside inputs

---

jobserver/authorization/roles.py

This updates ProjectDeveloper description and adds a description for ProjectDeveloper to explain to a user what they do.

Update ProjectCollaborator and ProjectDeveloper role descriptions

---

snippets/start_page.md

Recreated from #1317 to avoid problems with Amir not being an Org member when he raised the PR.

Application Start Page Tweaks

---

snippets/researcher-server-access-footer.md

Fix link to safe researcher training

---

staff/views/applications.py
staff/views/index.py

This lets users search for Applications by Researcher names on both the index page and Application list page.
Fixes #1285

Search Applications by Researcher Name

---

applications/templates/applications/application_list.html

Add application status to application list for users

---

applications/form_specs.py

Set various fields to optional

---

applications/form_specs.py
tests/factories/applications.py
tests/unit/applications/test_wizard.py

Remove Legal Basis Page

---

applications/models.py

Allow internal Application notes to be empty on form save

---

jobserver/views/workspaces.py

This means it will always show releases if there are any.

fix: ingore project's new release when showing releases.

---

jobserver/jobs/hourly/dump_db.py

Actually interpolate the string 🤦‍♂️

Fix DB Dump Script

---

jobserver/settings.py
jobserver/urls.py
requirements.dev.in
requirements.dev.txt

Enable automatic reloading of the browser with [django-browser-reload](https://github.com/adamchainz/django-browser-reload) 🎉

Add Browser Reloading

---

requirements.dev.in
requirements.dev.txt
requirements.prod.in
requirements.prod.txt

This avoids conditionals in urls.py and settings.py

Shift browser-reload into prod requirements

---

assets/src/scripts/index.js
jobserver/templates/index.html

I don't think searching by repo was really helping us here, it was definitely tripping up @HelenCEBM in the reported ticket.
Fixes #1404

Only search workspaces by name

---

jobserver/api/releases.py

Caught this while testing something unrelated with releases.

Select extra columns to avoid further queries

---

jobserver/templates/workspace_backend_files.html

Caught these old names while fixing something else.

Fix Attribute for getting a Backend's Name

---

applications/templates/applications/confirmation.html
applications/templates/applications/page.html

Preserve Line Breaks in Reviewer Notes

---

jobserver/settings.py
requirements.prod.in
requirements.prod.txt
staff/views/repos.py
tests/factories/applications.py
tests/factories/jobserver.py
tests/unit/jobserver/test_urls.py

This upgrades us to Django 4, fixing the URL tests to be more correct along the way.

Upgrade to Django 4.0

---

staff/forms.py
staff/templates/staff/project_create.html
staff/templates/staff/project_list.html
staff/urls.py
staff/views/projects.py
tests/unit/staff/views/test_projects.py

This adds a create Project form, linked from the list page of Projects.  I've opted to not support a UserSetProject page since we don't seem to need that route currently.
Fixes #1085

Add Create Project to Staff Area

---

jobserver/github.py
tests/unit/jobserver/test_github.py

This enables connection pooling and reuse, reducing load and latency. It
also allows us to centralise the auth code a bit.

fix: use a persistant requests.Session.

---

DEVELOPERS.md

add a note about ignorable pg_restore failures

---

assets/src/styles/main.scss
jobserver/templates/job_request_list.html

This fixes the status drop down on the Event Log page and does a drive by fix on the started at column width.
Fixes #1298 (actually for reals this time)

Event Log fixes

---

jobserver/migrations/0008_add_workspace_uses_new_release_flow.py
jobserver/migrations/0009_copy_project_release_flag_to_workspaces.py
jobserver/migrations/0010_remove_project_uses_new_release_flow.py

Fix Migration Names

---

jobserver/templates/workspace_detail.html

Link to workspace branch instead of just repo

---

jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

Redirect to relevant Project page after archiving a Workspace

---

.github/workflows/auto-merge.yml

Pull data from event payload

---

jobserver/templates/project_detail.html

Add a warning about the purpose of the testing project

---

staff/templates/staff/user_detail.html

Describe to Staff Area users how they should pick which backends to give to a user they are setting up.

Add our backend access policy to the staff area

---

jobserver/templates/_release_list.html
jobserver/templates/workspace_latest_outputs_detail.html
jobserver/templates/workspace_release_list.html
jobserver/views/releases.py
tests/unit/jobserver/views/test_releases.py

This improves the release listings by improving some of the wording and showing the number of files in each release for authenticated users

Improve release listings

---

justfile

This applies the justfile changes from https://github.com/opensafely-core/repo-template/pull/47 and reformats it to match the template.

Bring justfile up to date with repo-template

---

jobserver/runtime.py
requirements.prod.in

We limited attrs to <21 at some point in the past due to a tooling conflict.  That seems to have gone away based on the lack of errors in #1679 
This updates our use of attrs to the modern APIs.

Update attrs Usage

---

jobserver/models/outputs.py
tests/unit/jobserver/models/test_outputs.py

Add backend system to preview url for latest files

Add backend system to preview url for latest files

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Previously this lacked the "only notify once" logic that applies to
email notifications and so it could end up spamming Sentry and
exhausting our quota and was removed in:
090c074febe81f65b206057ed3611f371161f242
This slightly refactors things to use the same logic for email
notifications and Sentry alerts.

Restore Sentry alerts for jobs with Internal Error

---

DEVELOPERS.md
README.md
TESTING.md
jobserver/authorization/roles.py
jobserver/templates/partials/footer.html
snippets/service-evaluation-audit-rubric.md
snippets/start_page.md
snippets/terms.md

...and update the footer styling to accommodate the longer team name.

Update "DataLab" to "Bennett Institute" in text

---

dotenv-sample
gunicorn.conf.py

fix: do a better job of configuring opentelemetry

---

jobserver/api/jobs.py

* let's see whether this helps

fix: opentelemetry metadata explicit conversion to string

---

jobserver/api/jobs.py

* in the hope of tying related jobs together

feat: add JobRequest.identifier to monitoring

---

staff/views/applications.py

This enables searching for Application by ID, as displayed on the site.
Fixes #1722

Search application by ID

---

jobserver/views/workspaces.py

* this chosen as a sample, because it is a commonly used endpoint, and also I think we can easily hook into `dispatch()`

feat: add more detail to WorkspaceLog telemetry

---

package-lock.json
package.json

Revert "Merge pull request #1769 from opensafely-core/dependabot/npm_and_yarn/axios-0.27.2"
This reverts commit 09a8fb048360213ebac9191a127db07d151c70e5, reversing changes made to 2c4334bf337f47e925331e190b162016a0ec6507.

Revert axios upgrade

---

pyproject.toml

The bump to freezegun was supposed to fix this.

ignore Distutils warning in tests

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Report unexpected DB errors and OOM errors to Sentry; only internal errors and unexpected DB errors will be sent to Slack ([alert](https://sentry.io/organizations/ebm-datalab/alerts/rules/job-server/8406619/details/) already updated)

Report unexpected db and oom errors to sentry

---

DEVELOPERS.md
docker-compose.yml
dotenv-sample

Add instructions on creating the postgress user with necessary permissions for the local db.
Also changed the default user from "user" to "jobsuser" because psql doesn't like a user with the name "user".

Add some additional instructions for running a local database

---

jobserver/api/jobs.py

Reverts opensafely-core/job-server#1813

Revert "feat: add action metadata to opentelemetry"

---

requirements.prod.txt

Reverts opensafely-core/job-server#1812

Revert "build(deps): bump pyjwt from 2.3.0 to 2.4.0"

---

jobserver/api/jobs.py

Reverts opensafely-core/job-server#1814

Revert "Revert "feat: add action metadata to opentelemetry""

---

requirements.dev.txt

Reverts opensafely-core/job-server#1815

Revert "Revert "build(deps-dev): bump pip-tools from 6.6.1 to 6.6.2""

---

requirements.prod.txt

Reverts opensafely-core/job-server#1816

Revert "Revert "build(deps): bump pyjwt from 2.3.0 to 2.4.0""

---

.github/dependabot.yml

Attempt to remove configured reviewers from dependabot

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.module.scss
assets/src/scripts/outputs-viewer/tests/components/FileList/FileList.test.jsx

Closes https://github.com/opensafely-core/job-server/issues/1825

Highlight selected file name in the file list

---

jobserver/templates/partials/footer.html
snippets/start_page.md

- Add privacy policy link to footer
- Update privacy policy link in application form

Update privacy policy links

---

jobserver/templates/workspace_detail.html

Add a badge to the L4 outputs URLs

---

assets/src/js/tablesorter.js
jobserver/github.py
staff/templates/staff/repo_list.html
staff/views/repos.py
tests/unit/jobserver/test_github.py
tests/unit/staff/views/test_repos.py

This adds various filters and extra information to the private repos report page.

Improve private repos list

---

applications/form_spec_helpers.py

I've also added `check` to the required status checks for this repo.

pyupgrade upgraded and made this change

---

staff/templates/staff/index.html

Add link to Redirects on Staff Area index page

---

jobserver/templates/project_detail.html
jobserver/views/projects.py

I saw this in action while working on #1878 and did some maintenance on the view while I was there.  We're no longer making O(N) queries for the researcher list and I've ditched DetailView since it wasn't doing a lot for us at this point.
Fixes #1712

Fix project researcher role display

---

jobserver/views/projects.py
tests/unit/jobserver/views/test_projects.py

Fixes [this Sentry event](https://sentry.io/organizations/ebm-datalab/issues/3435328842/?project=5443358&referrer=slack).

Fix ProjectDetail Page for General Public

---

staff/templates/staff/repo_list.html
staff/views/repos.py

So we can link to each one easily.

List all workspaces on repos report page

---

staff/templates/staff/application_list.html
staff/views/applications.py
staff/views/index.py
staff/views/projects.py

This adds a link to a Project if it's linked on the Application list page, using the number instead of the title:
Ref #1871

Link to project on application list page

---

jobserver/settings.py
jobserver/templates/job_request_create.html
jobserver/templates/job_request_list.html

Remove inline styles

---

justfile

make sure we have a pyhton environment to run collectstatic with

---

jobserver/templates/release_detail.html
jobserver/views/releases.py

Add full dates to relative dates on release listing pages.
Fixes #1735

Add day to release

---

.github/workflows/main.yml
assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/Button/PrepareButton.jsx
assets/src/scripts/outputs-viewer/components/Button/PublishButton.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileReview/FileReview.jsx
assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
assets/src/scripts/outputs-viewer/components/Review/Modal.jsx
assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/hooks/use-review-state.js
assets/src/scripts/outputs-viewer/index.jsx
assets/src/scripts/outputs-viewer/stores/use-app-store.js
assets/src/scripts/outputs-viewer/stores/use-file-store.js
assets/src/scripts/outputs-viewer/utils/props.js
jobserver/templates/outputs-spa.html
jobserver/templates/release_detail.html
package-lock.json
package.json

Re-deploying the SPA, along with a fix to show metadata only if it's been populated.

Releases SPA

---

assets/src/scripts/outputs-viewer/components/Review/Modal.jsx

Re-instate the redirect on submit of reviews.

Use the new release location header to redirect to

---

assets/src/scripts/outputs-viewer/components/Review/Modal.jsx

Wait for the response JSON before redirecting

---

assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
jobserver/api/releases.py
jobserver/releases.py

This saves the submitted metadata to the db and fixes the function which renders it.

Fix release metadata

---

assets/src/styles/_staff.scss
staff/templates/staff/repo_list.html

Improve the staff repo list table styles

---

jobserver/templates/_components/description-item.html
jobserver/templates/_components/timeline-item.html
jobserver/templates/_icons/ellipsis-horizontal-outline.svg
jobserver/templates/components.yaml
jobserver/templates/job_detail_tw.html

Update styles on the job detail page

---

jobserver/templates/_components/timeline-item.html
jobserver/templates/job_detail_tw.html

Update timeline layout for different states

---

staff/forms.py
staff/templates/staff/user_detail.html
staff/views/users.py
tests/unit/staff/test_forms.py

So we can add or fix full names for a User for #2098.

Add fullname field to user detail page

---

tests/unit/jobserver/api/test_jobs.py

#2128 changed the way we store repos but our tests missed that the values the in the JobRequest API changed.  This changes the test to check the value of every field.

Explicitly test every key of the JobRequestAPIList endpoint

---

snippets/terms.md

Refs: https://github.com/opensafely/documentation/issues/892

Clarify wording about making research repos public

---

jobserver/api/jobs.py

They are too numerous and consuming our quota

fix: remove current honeycomb job traces

---

jobserver/settings.py

So that the CSP is active.
Closes #2004

Disable CSP Report-Only mode

---

jobserver/templates/_components/header.html

- Fix staff area link
- Fix duplicate class

Fix staff area link and styles in new header

---

.github/workflows/main.yml
package-lock.json
package.json
vite.config.js

Improve asset build time

---

jobserver/models/core.py
jobserver/views/job_requests.py
jobserver/views/workspaces.py

We keep blowing our budget of events - some of the existing manual traces was too granular and didn't really add a lot of value.
This change removes all the manual tracing we've added, with a view to adding more automated tracing (requests and psycopg2) to replace it.

fix: remove old tracing that was too busy

---

assets/src/scripts/main.js
assets/src/styles/main.scss
jobserver/templates/_job_requests.html

As currently it is a hack of `<div>`'s.

Update the Event Log to use a table element

---

jobserver/honeycomb.py
jobserver/views/jobs.py
tests/unit/jobserver/test_honeycomb.py

* allow us to easier test the link generation
* fix a bug that we'd missed in the link generation

feat: refactor & test honeycomb trace url formatting

---

assets/src/scripts/tw.js
assets/src/styles/tw.css
jobserver/templates/_components/button.html
jobserver/templates/_components/header.html
jobserver/templates/_components/tooltip.html
tailwind.config.js

As they are causing cross-browser and cross-device issues.

Remove transition and scaling effects

---

jobserver/honeycomb.py
tests/unit/jobserver/test_honeycomb.py
tests/unit/jobserver/views/test_job_requests.py
tests/unit/jobserver/views/test_jobs.py

* fixes https://github.com/opensafely-core/job-server/issues/2199

feat: extend honeycomb time period for unfinished job requests

---

jobserver/honeycomb.py
tests/unit/jobserver/test_honeycomb.py

* fixes https://github.com/opensafely-core/job-server/issues/2214

feat: job request concurrency graph defaults to stacked

---

jobserver/templates/_components/alert.html
jobserver/templates/_components/card.html
jobserver/templates/_components/form/input.html
jobserver/templates/_icons/mini/exclamation-circle.svg
jobserver/templates/base-tw.html
jobserver/templates/components.yaml
jobserver/templates/job_detail_tw.html
jobserver/templates/settings.html

Closes #2175 
**Note:** This is simply updating the text that is already added, not specifically adding an error message at the top of the form.

Restyle user settings template

---

jobserver/templates/job_detail_tw.html

Improve styles of the status and status message

---

jobserver/settings.py
jobserver/templates/org_detail.html

- Fix spacing and alt text
- Fix upload directory

Org detail fixes

---

jobserver/templates/_components/header.html
jobserver/templates/org_list.html
jobserver/views/orgs.py

Restyle org_list template

---

jobserver/templates/job_detail.html
jobserver/templates/org_detail.html
jobserver/templates/org_list.html
jobserver/templates/settings.html

- Fix breadcrumb location names
- Fix word break issues on headings

Styling fixes in restyle

---

jobserver/slacks.py
jobserver/views/repos.py
tests/conftest.py
tests/unit/jobserver/views/test_repos.py

Notify copilots in slack when a repo is signed off by a researcher

---

jobserver/templates/_components/button.html
jobserver/templates/_components/form/select.html
jobserver/templates/_components/form/textarea.html
jobserver/templates/components.yaml
jobserver/templates/project_detail.html
jobserver/templates/project_edit.html

Restyle the Project Edit template

---

jobserver/templates/workspace_edit.html

Restyle the Workspace Edit template

---

jobserver/views/repos.py
tests/unit/jobserver/views/test_repos.py

This was missed when adding the notification in #2266

Only notify copilots for repos without outputs

---

jobserver/templates/_icons/building-library-outline.svg
jobserver/templates/_icons/user-outline.svg
jobserver/templates/components.yaml
jobserver/templates/project_detail.html
jobserver/templates/project_edit.html
jobserver/templates/project_repo_list.html
jobserver/templates/workspace_edit.html
jobserver/templates/workspace_file_list.html
jobserver/templates/workspace_output_list.html

<a href="https://user-images.githubusercontent.com/24863179/200287256-b8700b29-6a06-4e14-b425-9a9c5f7516b0.png">
</a>
<a href="https://user-images.githubusercontent.com/24863179/200287270-c57da637-d5ea-4b28-906b-ef12f049e57f.png">
</a>
<a href="https://user-images.githubusercontent.com/24863179/200287264-ccff9cd8-bf41-47f7-a830-c95109f22f9f.png">
</a>
<a href="https://user-images.githubusercontent.com/24863179/200287274-0be3c8f2-8151-4679-b454-fce94c42e0ec.png">
</a>
<a href="https://user-images.githubusercontent.com/24863179/200287266-63b7866a-2adf-4b9f-8cf1-b8e6b6c99d67.png">
</a>
<a href="https://user-images.githubusercontent.com/24863179/200287282-4ac3dba0-8702-4a4f-bf49-3d249d5a9e47.png">
</a>

Restyle multiple workspace and project templates

---

staff/views/repos.py

Update the tech-support ticket to be clearer on next steps

---

jobserver/jobs/daily/clearsessions.py
jobserver/settings.py
tests/integration/test_auth.py

Switch to db-backed sessions

---

jobserver/templates/sign_off_repo.html
jobserver/templates/workspace_detail.html

Add words to explain one must have the authority to make a repo public

---

jobserver/templates/workspace_detail.html

Link to repo sign off page for all private repos

---

assets/src/styles/tw.css
jobserver/templates/_components/card/card.html
jobserver/templates/workspace_detail.html

- Fix date not showing outside card
- Fix long workspace name not wrapping

UI fixes on Tailwind pages

---

assets/src/scripts/tw.js

🤦 checked the stats this morning and realised a lot of page views were missing...

Add Plausible script to Tailwind templates

---

jobserver/api/jobs.py

Unless we do this then jobs which transition immediately into an error state (such as those produced by a JobRequestError) will never notify and so we won't get Sentry alerts about them.
The previous worry, that we might end up notifying about jobs we had already notified about seems unfounded, and in any case not a disaster if it were to happen.

Notify for newly completed jobs with no previous state

---

jobserver/slacks.py

Link to internal docs for repo sign off process when slacking copilots

---

jobserver/templates/_components/index.html
jobserver/templates/job_request_detail.html

- Minor improvements to the UI gallery styling
- Fix so that Job ID can be selected in job request card view

Various restyle fixes

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Fixes https://sentry.io/organizations/ebm-datalab/issues/3760341821/?project=5443358

Ensure job fields use python representations when creating a new Job

---

jobserver/honeycomb.py
jobserver/views/jobs.py
tests/unit/jobserver/test_honeycomb.py
tests/unit/jobserver/views/test_jobs.py

* fixes https://github.com/opensafely-core/job-server/issues/2361

feat: add Historic job runs honeycomb link

---

jobserver/models/core.py
templates/job_detail.html
tests/unit/jobserver/models/test_core.py

Display action and run_command on JobDetail page

---

jobserver/api/releases.py

As per [PEP 594](https://peps.python.org/pep-0594/#cgi), 3.11 is deprecating the cgi module.  This switches us over to the recommended `email.message` way of parsing headers.  I don't love that it's more verbose now but at least it has `get_filename()` which helps a little.
Refs: #2310

Switch from cgi to email.message.Message for parsing header

---

templates/project_detail.html

Add create new workspace button to empty card

---

applications/views.py
tests/unit/applications/test_views.py

Enable editing of applications by staff

---

jobserver/management/commands/merge_projects.py
tests/unit/jobserver/management/commands/test_merge_projects.py

For #2373 we need to move several objects around to achieve the desired state.  We've done this a couple of times before and it seems like we might have to do it again so it seems like the ideal to put it into code now.

Add a merge_projects command

---

templates/staff/application_list.html

Display submission status on application list

---

applications/forms.py
applications/models.py
templates/applications/confirmation.html
templates/applications/researcher_form.html

Add GitHub username to the researcher section of the application form

---

staff/forms.py
templates/staff/workspace_edit.html

add archived checkbox to workspace edit form

---

applications/urls.py
tests/integration/test_applications.py
tests/unit/jobserver/test_urls.py

This adds an integration test of the full application process, successfully submitting an application.  It is intended to avoid obvious bugs like #2502

Integration test the submission of an application

---

templates/_components/link.html

Closes #2378
https://user-images.githubusercontent.com/24863179/213193497-f4240339-b52b-4ddf-a418-8969c3c2b290.mp4

Improve focus style on links

---

pyproject.toml
tests/unit/interactive/test_models.py

This adds missing config and coverage from the intial interactive work.

Cover interactive

---

jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

We changed the scope for changing visibility of repos very late in the initiative from "code in this repo [and thus workspace] ran >11 months ago" to "code in this **project** and all its workspaces ran >11 months ago".
This fixes the check for displaying the banner, since it's on a workspace page, to take the workspaces repo visibility into account as well.  This stops workspaces with public repos showing the banner.
Fixes: #2528

Only show the change visibility banner on workspaces for private repos

---

docs/adr/0004-use-timeflake-db-ids.md
docs/adr/0006-migrate-timeflake-db-ids-to-string-ulids.md

document our move from timeflake to string ulids

---

assets/src/scripts/main.js
assets/src/scripts/tw.js
assets/src/scripts/utils/double-click.js
assets/src/scripts/utils/wait.js

Use JS to disable the button for 1s after a user clicks it.
Linked to #2594

Don't allow users to double-click on submit

---

interactive/forms.py
interactive/views.py
tests/unit/interactive/test_forms.py
tests/unit/interactive/test_views.py

Validate the submitted form payload

---

assets/src/scripts/interactive/App.tsx
assets/src/scripts/interactive/components/CodelistSearch.tsx
assets/src/scripts/interactive/components/ComboboxItem.tsx
assets/src/scripts/interactive/components/SelectBox.tsx
assets/src/scripts/interactive/main.tsx
assets/src/scripts/interactive/pages/review-request.tsx
assets/src/scripts/interactive/stores/index.ts
assets/src/scripts/interactive/utils/index.ts
templates/interactive/analysis_request_create.html
vite.config.js

Submit data to the Django app.

Submit data from OSI form

---

assets/src/scripts/interactive/components/ComboboxItem.tsx
assets/src/scripts/interactive/pages/review-request.tsx

Fixes:
- Add a title to submissions
- Fix missing import

Form fixes

---

staff/forms.py
tests/unit/staff/test_forms.py

Tell users if the title they have picked produces an existing slug

---

interactive/forms.py
tests/unit/interactive/test_forms.py
tests/unit/interactive/test_views.py

We don't pass the `time_*` fields with one codelist so we need to conditionally require them.

only require the time_* fields with two codelists

---

.flake8
requirements.dev.txt

Required changing the format of the ignore config

chore: upgrade to flake8 6.0.0

---

assets/src/styles/main.scss
templates/_components/header.html
templates/_icons/mini/chevron-down.svg
templates/_icons/mini/chevron-up.svg
templates/components.yaml
templates/partials/header.html

In preparation for non-GitHub user accounts.

Remove avatar from header nav

---

tests/verification/test_github.py

This has been intermittently failing CI for a few months and I finally got annoyed enough at it to roll this.

Ignore rate limit errors when testing without auth

---

templates/snapshot_detail.html

Resolve missing day date information

Fix date format on snapshot detail page

---

assets/src/scripts/interactive/App.jsx
assets/src/scripts/interactive/components/Button/Button.jsx
assets/src/scripts/interactive/components/Button/CodelistButton.jsx
assets/src/scripts/interactive/components/CodelistBuilder.jsx
assets/src/scripts/interactive/pages/build-query.jsx
assets/src/scripts/interactive/pages/filter-request.jsx
assets/src/scripts/interactive/pages/find-codelists.jsx
assets/src/scripts/interactive/pages/preview-request.jsx
assets/src/scripts/interactive/pages/review-query.jsx
assets/src/scripts/interactive/pages/review-request.jsx

Various usability fixes for OSIv2

---

pyproject.toml
services/sentry.py
tests/unit/services/sentry_event.json
tests/unit/services/test_sentry.py

We can't seem to parse these out on Sentry's side so we're doing them here instead.  A benefit to that is we get to pick the list of values we want to replace.

parse sentry events to remove important tokens

---

DEVELOPERS.md

Document how to generate a sqlite dump for the copilot's report

---

templates/login.html

In preparation for email style logins.

Update login screen with new base template styles

---

interactive/__init__.py
interactive/views.py

- fix: add start/end dates to Analysis template data
- s/snomedct/snomed, as that is the value expected by cohortextractor

interactive data fixes

---

docs/adr/0008-interactive-workspace-and-repo-suffixes.md

ADR: Interactive Workspace and Repo suffixes

---

assets/src/scripts/interactive/components/CodelistBuilder.jsx
assets/src/scripts/interactive/data/form-fields.js
assets/src/scripts/interactive/pages/review-query.jsx
assets/src/scripts/interactive/pages/review-request.jsx
assets/src/scripts/interactive/utils/index.js

Linked to #2665
- Use the JavaScript Date object to generate the dates for the form
- Pass the dates as ISO strings to the submission

Add dates as JS Date and submit ISO dates

---

assets/src/scripts/interactive/pages/review-request.jsx

Django app is returning the URL we want to redirect to.

Update form submission data and redirect

---

interactive/__init__.py
interactive/views.py
tests/unit/interactive/test_forms.py
tests/unit/interactive/test_submit.py

The analysis code is now inferring the type of codelist from the system, which reduces the amount of information we need to pass across.

Remove codelist type

---

interactive/opencodelists.py

only display downloadable codelists to the interactive users

---

templates/job_request_detail.html

Only show timeline item when job has finished

---

assets/src/scripts/interactive/components/ComboboxItem.jsx
assets/src/scripts/interactive/utils/index.js
interactive/opencodelists.py
tests/fakes.py

This extra information should help users pick an appropriate codelist.

Add codelist published date

---

interactive/views.py
templates/interactive/analysis_request_create.html

Expose start&end dates to the OSI react app

---

assets/src/scripts/interactive/data/form-fields.js
assets/src/scripts/interactive/main.jsx
assets/src/scripts/interactive/utils/index.js

Use start and end dates passed by Django

---

jobserver/context_processors.py
jobserver/settings.py
jobserver/views/users.py
templates/_components/header.html
templates/base-tw.html
templates/partials/header.html

This fixes going through login with get args already on the URL.

Pass args through login

---

.github/workflows/main.yml

switch to pull_request target so we don't run CI on every push

---

templates/_components/description-item.html
templates/job_detail.html

Fix text overflow on job_detail template

---

templates/job_request_detail.html

Fix job_request_detail runtime tooltip

---

jobserver/api/jobs.py
jobserver/models/core.py
jobserver/urls.py
tests/unit/jobserver/models/test_job.py

Use the JobDetail redirector URL in Sentry

---

interactive/commands.py

Set a purpose for interactive workspaces

---

templates/staff/analysis_request_detail.html

A handful of fixes to the AnalysisRequestDetail page in the staff area now that we are using it to debug AnalysisRequests.
Fix: #2784

Better staff area AnalysisRequest page

---

interactive/emails.py
jobserver/api/releases.py
templates/emails/notify_report_uploaded.txt
tests/unit/interactive/test_emails.py

Email the requester when a report for an AnalysisRequest is uploaded

---

docs/adr/0010-creating-interactive-queries-v2.md

Describe the changes to analysis submission in OSIv2

---

templates/staff/analysis_request_detail.html

We don't have a staff page for JobRequests.

Link to main site JobRequestDetail from AnalysisRequest staff area page

---

templates/interactive/analysis_request_detail.html

Add watermark and styles to Interactive Reports

---

jobserver/views/users.py

only notify honeycomb about missing session data on login

---

templates/_components/form/input.html
templates/login.html

Style the login page for Interactive users

---

DEVELOPERS.md
docs/adr/0012-paired-field-state-with-check-constraints.md

Record what and why we're using CheckConstraints with examples on how others can make use of them.
Fix: #2798

Document why and how to use CheckConstraints for paired fields

---

jobserver/views/workspaces.py
templates/workspace_detail.html

Selectively show workspace admin

---

justfile

A few updates to the upgrade checks to target the correct directories and versions.

Fix upgrade checks

---

staff/forms.py
templates/staff/project_create.form.html
templates/staff/project_create.html
tests/unit/staff/views/test_orgs.py
tests/unit/staff/views/test_projects.py

Add copilot name

---

jobserver/models/core.py
jobserver/urls.py
jobserver/views/orgs.py
jobserver/views/yours.py
templates/_components/footer.html
templates/index.html
templates/org_detail.html
templates/yours/analysis_request_list.html
templates/yours/org_list.html
templates/yours/project_list.html
templates/yours/workspace_list.html
tests/unit/jobserver/models/test_workspace.py
tests/unit/jobserver/test_nav.py
tests/unit/jobserver/test_urls.py
tests/unit/jobserver/views/test_orgs.py
tests/unit/jobserver/views/test_yours.py

This adds pages showing objects just for the current user.
Fix: #2853
Fix: #2854
Fix: #2855 
Fix: #2856

Add user-centric pages 

---

assets/src/styles/tw.css
templates/_components/footer.html
templates/index.html
templates/yours/analysis_request_list.html
templates/yours/org_list.html
templates/yours/project_list.html
templates/yours/workspace_list.html

- Fix issues raised by Lighthouse
- Fix missing meta titles
- Fix home page styling issues
- Fix home page spacing
- Fix missing fonts on all Tailwind template pages

Various front-end fixes for new pages

---

DEVELOPERS.md

chore: add instructions for rotating OSI token

---

docs/adr/0013-interactive-templates-repo.md

chore: add ADR for template repo

---

interactive/dates.py

This reverts commit bbe2625cd5778ee7ad3d3455c0e05f2839e2b857.

Revert "Temporarily reduce the time period for testing"

---

assets/src/scripts/interactive/main.jsx
assets/src/scripts/interactive/pages/glossary.jsx
assets/src/scripts/interactive/pages/review-request.jsx

Add glossary page to the start of the request form

---

assets/src/scripts/analysis-request-detail.js
assets/src/scripts/interactive/pages/review-request.jsx
templates/_components/button.html
templates/interactive/analysis_request_detail.html

- PDF interactive request:
- Fix the size of the margins
- Improve the file size by switching to JPEG for the canvas screenshot
- Remove the watermark from the "Generating your request" section
- Add read and agree wording to the submission page
- Add a modal with information regarding the download

Interactive PDF changes and form wording tweaks

---

templates/project_detail.html

Fix the mobile and desktop display when there are three buttons visible.

Fix project button spacing

---

jobserver/views/users.py
templates/index.html
tests/unit/jobserver/views/test_users.py

Handle interactive-only users with >1 project

---

assets/src/scripts/interactive/pages/build-query.jsx

...for Interactive request form.

Change default time scale to 5 years

---

jobserver/middleware.py
jobserver/models/core.py
jobserver/settings.py
jobserver/views/users.py
justfile
templates/login.html
templates/settings.html
tests/conftest.py
tests/factories/jobserver.py
tests/unit/jobserver/models/test_user.py
tests/unit/jobserver/test_middleware.py
tests/unit/jobserver/views/test_users.py

- feat: add middleware for detecting request from backend
- fix: restrict token login to TPP only.

ip restrictions

---

assets/src/scripts/interactive/components/Tabs/TabPanel.jsx
templates/interactive/analysis_request_detail.html

Update text and input autocomplete based on user feedback.

Fix for Interactive form controls and text

---

templates/interactive/report_publish_request_update.html

A quick update to make the AnalysisRequestUpdate page a little more usable.

Match styles with the AnalysisRequestDetail page

---

templates/applications/apply.html

Add a link to the user's existing applications on the main apply page

---

interactive/dates.py
tests/unit/interactive/test_dates.py

Fix: #opensafely-core/interactive-templates#60

Set the end date to the last complete complete month

---

assets/src/scripts/interactive/pages/filter-request.jsx
assets/src/scripts/interactive/pages/purpose.jsx
assets/src/scripts/interactive/pages/review-request.jsx
interactive/forms.py
tests/unit/interactive/test_forms.py

In the front-end form submission.

Change 'demographics' from required to optional

---

docs/adr/0016-publishing-reports.md

Document our decision on how reports will be published

---

interactive/notifications.py
tests/unit/interactive/test_notifications.py

Handle newlines in the AnalysisRequest purpose

---

services/slack.py

A follow up to opensafely-core/interactive.opensafely.org#410 using the suggested implementation.

Print slack messages to the console in debug mode

---

interactive/slacks.py
jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

notify the tech support channel when an analysis request fails

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/__tests__/App.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/FileList/FileList.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/Viewer/Viewer.test.jsx
assets/src/scripts/outputs-viewer/__tests__/helpers/files.js
assets/src/scripts/outputs-viewer/__tests__/hooks/use-file-list.test.js
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/utils/props.js

Remove short name from file data

---

requirements.prod.in
requirements.prod.txt

Update interative-templates to 8239d4ef8a0c29a969bccf0cbab9d4d01d20ed86

Update interactive templates to latest version

---

interactive/commands.py
interactive/slacks.py
interactive/submit.py
jobserver/api/releases.py
tests/unit/interactive/test_submit.py
tests/unit/interactive/test_views.py
tests/unit/jobserver/api/test_releases.py

Add OSI slack notifications

---

assets/src/scripts/interactive/components/Textarea.jsx
assets/src/scripts/interactive/pages/analysis-information.jsx

So that users know what text to enter.

Update analysis title and summary hint text

---

assets/src/scripts/interactive/pages/review-request.jsx
jobserver/settings.py

...and fix the amount of errors sent to Sentry.

Fix Sentry issues for JS apps

---

jobserver/slacks.py
tests/unit/jobserver/views/test_repos.py

Add copilot to repo signoff slack message

---

interactive/notifications.py

The measures files produced with OSI were updated in https://github.com/opensafely-core/interactive-templates/pull/87. This updates the issue template to reflect these changes

update file paths in OSI issue template

---

requirements.prod.in
requirements.prod.txt
tests/unit/interactive/test_submit.py

start/end_date are now required fields, so this addes them to tests

Update to latest interactive

---

interactive/commands.py
interactive/submit.py
requirements.prod.in
requirements.prod.txt
tests/integration/test_interactive.py
tests/unit/interactive/conftest.py
tests/unit/interactive/test_submit.py

This change include moving `create_commit()` and related functions from
job-server to interactive-templates.

Update to latest interactive-templates

---

staff/views/reports.py
templates/staff/report_list.html
tests/unit/staff/views/test_reports.py

Various fixes for the staff area's ReportList page

---

assets/src/scripts/interactive/pages/glossary.jsx

Remove the organisation requirement for codelists

---

assets/src/scripts/analysis-request-detail.js
assets/src/scripts/interactive/pages/review-request.jsx
templates/interactive/analysis_request_detail.css
templates/interactive/analysis_request_detail.html
templates/interactive/report_edit.html

- Remove JS from "Report title and summary edit" page
- Improve variable naming in JS file
- Responsive size fixes for small screens
- Hide report behind modal when generating PDF

Various fixes for Interactive report and PDF

---

jobserver/views/reports.py

This view posts with no data so we have nothing to validate, no Form class, and we don't create a PublishRequest with a ModelForm.  So CreateView (and FormView) don't make sense here.

Refactor PublishRequestCreate to use View

---

templates/interactive/publish_request_create.html

Add details of what publishing entails to publish request page

---

interactive/urls.py
interactive/views.py
jobserver/authorization/roles.py

Let staff view unpublished reports

---

templates/_icons/exclamation-triangle.svg
templates/components.yaml
templates/interactive/analysis_request_detail.html

Show failed analysis state to users

---

interactive/emails.py
jobserver/emails.py
staff/views/users.py
templates/emails/notify_report_uploaded.html
templates/emails/notify_report_uploaded.txt
templates/emails/welcome.html
templates/emails/welcome.txt
tests/unit/interactive/test_emails.py
tests/unit/jobserver/test_emails.py

This updates the wording for a couple of emails, with a quick code location update.
Fix: #3019

OSI email rewording

---

assets/src/scripts/analysis-request-detail.js
templates/interactive/analysis_request_detail.html

Approved projects link:
Link to job-server in the PDF:
Fix: #3033

Link OSI reports to their approved project

---

snippets/researcher-details.md

New version added to replace outdated version. New version approved by NHSE over email 03.07.23.

DAA updated by NHSE

---

DEVELOPERS.md

Update docs to include additional table

feat: add additional table

---

static/robots.txt

We're seeing high levels of traffic from Amazonbot that's affecting site availability. Instructions here https://developer.amazon.com/support/amazonbot

Stop Amazonbot from crawling us

---

assets/src/scripts/_expand-list.js
assets/src/scripts/interactive/components/Fieldset.jsx
assets/src/scripts/tw.js
package-lock.json
package.json
templates/_components/button.html
templates/_components/header.html
templates/project_release_list.html
templates/workspace_release_list.html

Closes #3184
- Use separate nav bars for desktop and mobile views
- Replace dropdown code with a custom vanilla JS driven solution based on data attributes

Replace Alpine.js

---

gunicorn.conf.py

We beefed up the server, so make use of it

Update gunicorn.conf.py workers to 9

---

jobserver/migrations/0003_create_redirects_to_remove_org_from_all_urls.py
redirects/models.py
tests/unit/redirects/test_models.py

A couple of fixes that came out of deplying and then fixing #3310

Redirect fixes

---

staff/views/orgs.py
templates/staff/org_detail.html

Display redirects for orgs in the staff area

---

jobserver/views/index.py

Explicitly aggregate started_at onto homepage JobRequests

---

services/sentry.py
tests/unit/services/sentry_event2.json
tests/unit/services/test_sentry.py

Our Sentry events have been silently failing for ~5 months, since I introduced the `strip_sensitive_data` function.
This will hopefully rectify that, but it will need some monitoring.

Fix sentry parser

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
templates/snapshot_detail.html

Various issues fixed from the initial release.

Fixes for the Outputs SPA

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
templates/_components/breadcrumbs/breadcrumb.html
templates/release_detail.html
templates/snapshot_detail.html
templates/workspace_backend_files.html
templates/workspace_latest_outputs_detail.html

Various fixes associated with #3356 and #3361

Fixes for spacing and padding in SPA

---

jobserver/settings.py

Missed as part of font changes in #3364

Fix font CSP setting

---

jobserver/models/core.py
jobserver/views/users.py
staff/views/users.py
templates/_components/header.html
templates/partials/header.html

Cache whether a user uses social auth to login

---

assets/src/scripts/sign-off-repo.js
templates/_components/article/header.html
templates/_components/form/input.html
templates/_components/form/textarea.html
templates/sign_off_repo.html
templates/workspace_create.html
templates/workspace_create_error.html
templates/workspace_log.html
vite.config.mjs

Switch templates to Tailwind styles

---

jobserver/management/commands/backfill_job_run_command.py

I extracted the logic of this script before making #3380 and of course forgot to check it.  I've also added a filter to the jobs queryset so we don't overwrite the run command when it's already been set.

Fix backfill script

---

jobserver/views/workspaces.py
templates/workspace_log.html

A couple of small fixes for WorkspaceLog, including [this Sentry event](https://ebm-datalab.sentry.io/issues/4386666492/?alert_rule_id=10884789&alert_type=issue&project=5443358).

WorkspaceLog fixes

---

templates/sign_off_repo.html

Fix form attr for submission method

---

jobserver/views/projects.py

Add tracing spans when building the repos data for ProjectDetail

---

jobserver/views/projects.py

try to instrument GitHub API queries under the same trace

---

jobserver/views/projects.py

Pass context down into function running in other threads

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

We've moved these alerts to Honeycomb.

Remove sentry forwarding

---

templates/applications/page.html

`field.field.value` will equal `True` or `False` if the checkbox is checked.

Fix checkbox checked status on applications

---

templates/_components/form/checkbox.html
templates/job_request_create.html
templates/workspace_log.html

Fix for regression added in https://github.com/opensafely-core/job-server/pull/3391

Fix missing custom_field values

---

templates/_components/breadcrumbs/breadcrumb.html
templates/_components/list-group/list-group.html
templates/_partials/staff-hero.html
templates/components.yaml
templates/staff/index.html
templates/staff/sentry/index.html
templates/staff/sentry/message.html

Update the Sentry Staff Area templates

---

jobserver/models/core.py
staff/forms.py
staff/urls.py
staff/views/projects.py
staff/views/users.py
templates/staff/org_detail.html
templates/staff/project_detail.html
templates/staff/project_membership_edit.html
templates/staff/user_detail_with_email.html
templates/staff/user_detail_with_oauth.html
templates/staff/user_role_list.html
tests/unit/jobserver/models/test_user.py
tests/unit/staff/test_forms.py
tests/unit/staff/views/test_projects.py
tests/unit/staff/views/test_users.py

Add a roles page to the staff area for users

---

jobserver/github.py

We only use this for verification tests, and they can run fast enough that GitHub hasn't finished creating the repo we're asking them to delete.  The hope is a 1 second back off will fix this.  They don't give us any backoff window for this operation so we're having to pick the backoff ourselves.

Add a retry to GitHubAPI.delete_repo

---

templates/project_detail.html

Show project numbers to all users

---

jobserver/authorization/fields.py
tests/unit/jobserver/authorization/test_parsing.py

Remove now-unused RolesField

---

jobserver/models/core.py
jobserver/urls.py
jobserver/views/users.py
templates/user_detail.html
templates/user_event_log.html
tests/integration/views/test_users.py
tests/unit/jobserver/models/test_user.py
tests/unit/jobserver/views/test_users.py

Add event log page for users

---

staff/views/repos.py
templates/staff/repo_detail.html

Fixes [this Sentry event](https://ebm-datalab.sentry.io/issues/4460577231/?alert_rule_id=10884789&alert_type=issue&project=5443358)

Fix staff repo detail when repo has no jobs

---

requirements.prod.txt

* not updating to latest because I'm trying to encourage dependabot to kick into life

chore: update otel to 1.16.0

---

justfile
requirements.prod.in
requirements.prod.txt

The hope is this will unstick dependabot, of course we can't check that until this is merged 🤞
Fix: #3031 
Ref: #3537

Use the now-versioned interactive-templates

---

justfile

This was removed in cc7e92cae25f63e5539cbb8e73e7b4a09df47032 without realising it's part of how interactive-templates automatically creates PRs in job-server.
This has now been updated to:
* use a sheband that is more likely to resolve bash
* use a cross-platform invocation of sed
* use the generated tag
Ref: #3031

reinstate the update-interactive-templates just command

---

jobserver/views/job_requests.py
jobserver/views/jobs.py
tests/unit/jobserver/views/test_job_requests.py
tests/unit/jobserver/views/test_jobs.py

Show alerts when job/requests are cancelled

---

assets/src/scripts/outputs-viewer/__tests__/components/Viewer/Viewer.test.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
assets/src/scripts/outputs-viewer/utils/file-type-match.js
jobserver/releases.py
tests/unit/jobserver/api/test_releases.py

Flag released files which haven't been uploaded

---

assets/src/scripts/job_request_create.js
templates/job_request_create.html

Fix run_all status on job request create page

---

staff/views/users.py
templates/staff/user/list.html
tests/unit/staff/views/test_users.py

Show user role status and add filter to staff area

---

staff/views/users.py

This lets us have one construction that we either filter or don't. Django's .filter() and .exclude() have different semantics for how they produce AND/OR queries.
.filter() uses AND regardless of multiple kwargs or chaining, while .exclude() produces OR statements with multiple kwargs and AND statements when chaining, making using these methods in combination confusing to the reader.
Since we know we want the same query as either a filter or an exclude this change builds up the query with Q objects (so we can explicitly control the AND/OR statements generated) and then calls the appropriate QuerySet method based on the input value.
This also removes the __exact lookup because it doesn't change the resulting SQL.  It's unclear if this is because we're querying an array field or because …

Use Q objects to build up a [does not] have roles query

---

jobserver/views/index.py

This removes 10 additional queries and reduces page load by 100ms for both the authenticated and unauthenticated versions of the index page.

Select org for job requests in SQL queries

---

templates/_components/tooltip.html
templates/job_request_list.html
templates/org_event_log.html
templates/project_event_log.html
templates/user_event_log.html
templates/workspace_event_log.html

Show the last tooltip in a log table on top

---

templates/_components/multiselect/multiselect.html
templates/_components/multiselect/multiselect.js
templates/staff/project/create.html

Allowing a single selection for a form.

Use single multiselect in staff area project template

---

templates/_components/list-group/list-group-rich-item.html
templates/staff/repo/detail.html

Fix archived flags on workspaces in staff area

---

.github/workflows/main.yml
docker/docker-compose.yaml
docker/justfile
justfile
pyproject.toml
scripts/test-coverage.sh

- Refactor running tests with coverage.
- Attempt to run test CI in parallel

Refactor coverage and xdist in CI

---

jobserver/views/job_requests.py
templates/_partials/alerts.html
tests/unit/jobserver/views/test_job_requests.py

Add link to docs in the out-of-date codelists warning

---

assets/src/scripts/components.js
templates/_components/form/select.html
templates/_components/form/textarea.html
templates/_components/index.html

Add all components to the UI Components gallery page

---

jobserver/views/yours.py
templates/yours/org_list.html
templates/yours/project_list.html
templates/yours/workspace_list.html

Closes #3791
- Users "Your orgs" list is now paginated
- Users "Your workspaces" list:
- Is now paginated
- Shows associated org and project
- Shows workspace status (archived or not)
- Users "Your projects" list:
- Is now paginated
- Shows associated org

Improve user list page templates

---

.github/dependabot.yml

This isn't an intended end-state. I just want to check that the grouping works and how the PRs that are created are labelled (so we can understand whether auto-merging can be configured sensibly).

Experiment with Dependabot configuration

---

jobserver/views/repos.py
tests/unit/jobserver/views/test_repos.py

Fix Review project URL on repo sign-off page

---

templates/_partials/latest-job-requests-table.html
templates/job_request_list.html

Add links and modify columns for Event Log

---

templates/staff/application/edit.html

Increase status box rows and allow resize

---

templates/_components/pill/project-status.html
templates/yours/project_list.html

And fix issue with the project status pill text.
Closes #3844

Display status pill on "Your projects" list page

---

DEVELOPERS.md
requirements.prod.in
requirements.prod.txt

* includes support for final http telemetry names

chore: update opentelemetry to 0.43b0

---

assets/src/scripts/_plausible.js
templates/base.html

Capture the logged in and staff status of users in Plausible Analytics.
Part of #3522

Add Plausible custom events for logged in and staff status

---

docs/adr/0018-redirects.md

Document why we added the Redirect model and middleware.

Add redirects ADR

---

jobserver/management/commands/release.py

We removed this path in #3890, but because this command isn't tested we missed it.

Switch release command to new style release path

---

scripts/collect-me-maybe.sh

chore: tiny refactor of collectstatic script

---

assets/src/scripts/outputs-viewer/__tests__/components/Iframe/Iframe.test.jsx
assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
templates/_includes/outputs-spa.html

Increase height of Output Viewer and file list

---

jobserver/api/releases.py
jobserver/commands/users.py
jobserver/models/user.py
jobserver/urls.py
jobserver/views/users.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/commands/test_users.py
tests/unit/jobserver/models/test_user.py
tests/unit/jobserver/test_urls.py
tests/unit/jobserver/views/test_users.py

- Invert check logic in authorization checks.
- Refactor token generation and validation logic
- Add token auth api
Fixes #4025

token login api

---

tests/unit/jobserver/api/test_releases.py

The tests for this passed because the branch this came from was a little bit behind the removal of ProjectMembershipFactory (done in #3607).

Switch ProjectMembershipFactory for project_membership fixture

---

jobserver/management/commands/merge_projects.py
tests/unit/jobserver/management/commands/test_merge_projects.py

In practice this is very unlikely to happen but we need to handle explicitly deleting ProjectCollaborations so we also make sure no information about related orgs is lost just in case.

Add any orgs not already related to the primary project

---

jobserver/issues.py

Include github username in issue body when requesting repo be made public

---

templates/staff/user/detail_with_email.html

Add joined date to email-based user template

---

templates/staff/user/detail_with_oauth.html

Combine missing user info boxes under single title
fixes  #4044

Fix missing info box title on UserDetailWithOAuth page 

---

jobserver/management/commands/release.py
tests/unit/jobserver/management/commands/test_release.py

Fixes #3986 
Adds tests and a couple of fixes for bugs revealed by these tests

Test release command

---

templates/staff/job_request/detail.html

Add commit hash to staff detail page

---

templates/staff/workspace/detail.html

Fix links to jobs in staff workspace detail page

---

.github/dependabot.yml

These config changes are intended to reduce the volume of dependabot PRs we receive without compromising security.

Dependabot config tweaks

---

templates/yours/project_list.html

Show project numbers on list of projects

---

assets/src/scripts/interactive/main.jsx

Spotted while being walked through the code.

Fix typo: "You" -> "Your"

---

jobserver/models/job_request.py

Quick post-merge addendum to #4130  based comments from @inglesp

Explain how min/max is used to derive JobRequest status

---

templates/release/detail.html
templates/workspace/latest_outputs_detail.html

Update text on release and latest release pages

---

tests/unit/jobserver/views/test_index.py

Our index page, whether logged in or not, makes quite a few calls to the database, yet we want it to remain fairly performant. This adds some assertions into the existing unit tests that check the view. It also adds some tests using the Django Client to render the template and assert on the number of database queries we're making using both the view and the template. That way, if we accidentally change this behaviour by updating the template, we'll know. We may want to expand these tests over time to ensure we're rendering the template correctly or to check the number of db queries in different scenarios.

Assert on num db queries for views and templates

---

staff/views/dashboards/copiloting.py
templates/staff/dashboards/copiloting.html

Add last run job date to copilot dashboard

---

assets/src/scripts/_plausible.js
templates/job/detail.html
templates/job_request/detail.html

Add Plausible events to outbound clicks on job diff buttons.
Closes #4166

Add Plausible events to outbound clicks

---

templates/_components/index.html
templates/job/detail.html

Remove tooltips from CPU stats and update gallery

---

jobserver/jobs/hourly/dump_db.py

This means we're no longer providing the password as part of the connection string on the command line and are instead passing it in as an environment variable. This stops the password from being accidentally reported in error logs, etc.

Replace cli arg with env vars

---

templates/_components/form/input.html
templates/_components/form/radio_list.html
templates/_components/form/select.html
templates/_components/form/textarea.html
templates/applications/page.html

Fix hint text on application inputs

---

assets/src/scripts/outputs-viewer/__tests__/App.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/Button/Button.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/FileList/FileList.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/Link/Link.test.jsx
assets/src/scripts/outputs-viewer/__tests__/components/Toast/Toast.test.jsx
assets/src/scripts/outputs-viewer/index.jsx
package-lock.json
package.json

...and fix incorrect use of `@testing-library/user-event` dependency.

Fix for testing library version mismatch

---

requirements.dev.txt
requirements.prod.txt

Dependabot couldn't do this for whatever reason.

Upgrade idna manually

---

tests/conftest.py
tests/unit/applications/test_views.py
tests/unit/interactive/test_views.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/models/test_user.py
tests/unit/jobserver/views/test_job_requests.py
tests/unit/jobserver/views/test_jobs.py
tests/unit/jobserver/views/test_projects.py
tests/unit/jobserver/views/test_releases.py
tests/unit/jobserver/views/test_reports.py
tests/unit/jobserver/views/test_workspaces.py

Decouple production roles from tests

---

.eslintrc.cjs
assets/src/scripts/interactive/components/Alert.jsx
assets/src/scripts/interactive/components/Button.jsx
assets/src/scripts/interactive/components/CharCount.jsx
assets/src/scripts/interactive/components/Checkbox.jsx
assets/src/scripts/interactive/components/Diagrams/EventsBefore.jsx
assets/src/scripts/interactive/components/Fieldset.jsx
assets/src/scripts/interactive/components/RadioButton.jsx
assets/src/scripts/interactive/components/Textarea.jsx
assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/__tests__/components/Button/Button.test.jsx
assets/src/scripts/outputs-viewer/components/Button/Button.jsx
assets/src/scripts/outputs-viewer/components/Card/index.jsx
assets/src/scripts/outputs-viewer/components/Form/Input.jsx
assets/src/scripts/outputs-viewer/components/Link/index.jsx
assets/src/scripts/outputs-viewer/components/NoPreview/NoPreview.jsx

https://github.com/facebook/react/pull/16210
Blocked by: https://github.com/opensafely-core/job-server/pull/4304

Replace defaultProps with JavaScript default parameters

---

assets/src/scripts/_datatable.js
assets/src/styles/_datatable.css
dotenv-sample

- **Fix db port typo in dotenv-sample**
- **Allow datatables to opt out of columns being searchable**
- **More specific targetting of datatable css**
- **Make datatable set up not an anonymous function.**

datatable tweaks

---

templates/_components/button.html
templates/_components/index.html
templates/_components/modal/modal.html

- **Expose more attributes on button component**
- **Add autoshow attribute to modal componentent**

More component attrs

---

templates/_components/index.html
templates/_partials/latest-job-requests-table.html
templates/job_request/list.html
templates/org/event_log.html
templates/project/event_log.html
templates/staff/dashboards/copiloting.html
templates/staff/dashboards/projects.html
templates/staff/dashboards/repos.html
templates/staff/dashboards/repos_with_multiple_projects.html
templates/user/event_log.html
templates/workspace/event_log.html

https://github.com/opensafely-core/job-server/assets/24863179/42230c84-52ce-49fd-b5a3-e9660038403b

Stop tables causing an overflow on mobile devices

---

DEVELOPERS.md
docker/.env
docker/docker-compose.yaml
docker/justfile

Migrate to `docker compose` v2 command

---

airlock/views.py
tests/unit/airlock/test_views.py

Fixes https://github.com/opensafely-core/airlock/issues/427

Update output-checking issues for Airlock partially reviewed and reviewed events

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

This sends a boolean "ongoing" status rather than the specific Project status. This data is expected to be consumed by Airlock, which just needs to know whether a project is ongoing or not in order to determine whether release requests can be created. In case the specific statuses change in job-server (and there's some comments in the model that suggest that they might in future), we don't want Airlock to be looking for exact job-server controlled strings.

Include project status in user details endpoint

---

docs/adr/0020-replace-zen-queries.md

While implementing the decision described in the ADR, we found a better way of testing the number of database queries generated by a template. Since the ADR is still new and the decision hasn't really changed, I'm clarifying the existing decision rather than writing a new ADR.

Update Replace Zen Queries ADR

---

.github/workflows/update-interactive-templates.yml

Fixes a few small issues with the newly added workflow, that were, of course, discovered after trying to run the workflow.

Fix up the "update interactive-templates" workflow

---

staff/views/applications.py
tests/unit/staff/views/test_applications.py

This attempts to do the right thing, making up for #4459 (a quick fix) and #4460. The commit messages contain my reasoning, so I'll not repeat them here.

Fix `ApplicationList` view

---

.github/CODEOWNERS
jobserver/permissions/cohortextractor.py
jobserver/permissions/sqlrunner.py
jobserver/permissions/t1oo.py

It's not obvious to someone editing these files that they are referenced elsewhere so we add some breadcrumbs/back-links here.
For discussion on the limitations of CODEOWNERS see: https://bennettoxford.slack.com/archives/C058N7P4T2S/p1721723419112229?thread_ts=1721312706.728699&cid=C058N7P4T2S

Add reminders to update documentation if needed

---

templates/job_request/detail.html
templates/workspace/detail.html

This clarifies the use of highly senstive data and improves the wording in a few other places. In particular, I think it's important that we're consistent with the nouns we use to describe concepts such as jobs, actions and environments.

Improve wording shown to the public

---

docs/adr/0022-grant-output-checkers-view-released-file.md
jobserver/authorization/roles.py

Provide Output Checkers with the permission to view released files

---

jobserver/authorization/roles.py
templates/staff/project/membership_edit.html
templates/staff/user/role_list.html

- Update the descriptions
- Remove docstring duplication of descriptions
- Update template language to clarify the page titles and what changes can be made
Closes #4584

Update global and project roles descriptions

---

requirements.prod.in
requirements.prod.txt

pydantic is still a transitive dependency of pipeline.

Remove now-unused dependencies

---

redirects/middleware.py

- The `QuerySet` is a little complex, so document its purpose more clearly.
- Make the docstring a little clearer.
- Comment code blocks to aid reading the control flow.

Document redirects middleware QuerySet and control flow.

---

TESTING.md

Remove end-to-end test references

---

templates/project/detail.html

Improve text of project timeline sidebar

---

templates/_components/modal/modal.html

Apply auto margins on all sides.

Align modal centrally on the page

---

justfile

Before, it just updated .in, now should also update .txt
Fixes: #4852

Fix automatic pipeline upgrade

---

airlock/views.py
tests/unit/airlock/test_views.py

Fixes opensafely-core/airlock#854.

Use organisation slug for Airlock notification lookups

---

jobserver/runtime.py
requirements.prod.in
requirements.prod.txt
tests/unit/jobserver/test_runtime.py

Remove use of `attrs`

---

.github/workflows/main.yml
DEVELOPERS.md
docker/docker-compose.yaml
docs/adr/0014-osi-token.md
dotenv-sample
jobserver/settings.py

Relates to #4858.
See the commit message for more explanation.

Remove most references to Interactive GitHub token

---

jobserver/emails.py
jobserver/forms.py
jobserver/urls.py
jobserver/views/users.py
templates/login.html
tests/unit/jobserver/test_emails.py
tests/unit/jobserver/views/test_users.py

Fixes #4866.
See the commit message for details.

Remove Interactive login form

---

jobserver/authorization/permissions.py
tests/unit/jobserver/views/test_projects.py

Remove analysis request create permission

---

docs/adr/0002-implement-interactive-using-the-django-web-framework.md
docs/adr/0003-creating-interactive-queries.md
docs/adr/0005-migrate-interactive-into-job-server.md
docs/adr/0008-interactive-workspace-and-repo-suffixes.md
docs/adr/0009-download-released-reports.md
docs/adr/0010-creating-interactive-queries-v2.md
docs/adr/0011-login-via-magic-link.md
docs/adr/0013-interactive-templates-repo.md
docs/adr/0014-osi-token.md
docs/adr/0017-publishing-reports.md
docs/adr/0019-redirects.md
docs/adr/0029-sunset-osi-interactive.md

Closes #4863.
Also deprecate Interactive-related ADRs.

ADR for `initiative:sunset-interactive`

---

requirements.dev.txt
requirements.prod.txt

Update to Django 5.1.7

---

requirements.prod.in

We're oftentimes wondering "What is this package for? Roughly where is it used?". Here are some comments explaining the current state of play.
They could possibly get slightly out of date if someone uses a dependency in a new place. That's probably not too damaging and won't happen too often and can be weighed against the usefulness of having at least some information readily available.
These comments are also useful when checking for childless dependencies. I needed this information to do that process, so I'm writing down these notes for future reference. See https://github.com/opensafely-core/job-server/issues/4873

Document dependency purpose and usage

---

requirements.dev.txt

This updates the pre-commit part of our dependency tree.
These are all developer requirements.

Upgrade pre-commit dependencies

---

redirects/models.py
tests/unit/redirects/test_models.py

A couple of functions weren't used or useful. See commit messages.

Remove unused `redirects` code

---

TESTING.md

Add some notes to `TESTING.MD` on some points I came across during #4972 and in general. Expand the list of useful `pytest` parameters. Note how migrations are tested. Some notes on the `slow_test` marker, and how tests should use the DB.

Notes on useful `pytest` params, use of the DB, `slow_test`s

---

requirements.dev.txt
requirements.prod.txt

These are mostly transitive dependencies that are shared by multiple packages.

Update miscellaneous dependencies

---

.github/workflows/deploy.yml

Finalize Sentry release separately from creation

---

templates/applications/emails/submission_confirmation.txt

Edits to text required, as the text was out of date. 
This edit has been signed off by Pete Stokes and Juliet Underdown.

Update to text required

---

jobserver/authorization/roles.py

Update `OutputChecker.description` - mention release of files

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

We track "last contact" statistics for each backend which we use to confirm that the backend is available and update status pages and issues alerts appropriately. But since the RAP Controller now sits between the backend and Job Server, contact from the controller is no longer evidence of the health of the backend.
To address this the RAP Controller now tracks last contact times for the agent in each backend and passes these up to Job Server. This PR makes Job Server use those timestamps, rather than the current time, as a record of when each backend was known to be alive. The rest of the status checking mechanisms can remain unchanged.
See:
* https://github.com/opensafely-core/job-runner/issues/1037
* https://github.com/opensafely-core/job-runner/pull/1049

Use timestamps from RAP Controller in backend stats

---

.gitignore
package-lock.json
package.json

Closing various dependabot requests

Update JS dependencies

---

tests/unit/jobserver/management/commands/test_check_rap_api_status.py

Update mock test data to match new API response structure

---

jobserver/management/commands/cancel_jobs.py
jobserver/management/commands/rap_status.py
jobserver/rap_api.py
tests/unit/jobserver/management/commands/test_cancel_jobs.py
tests/unit/jobserver/management/commands/test_rap_status.py
tests/unit/jobserver/test_rap_api.py

* will fix https://github.com/opensafely-core/job-server/issues/5228

Create rap/status management command

---

jobserver/api/jobs.py

Reverts opensafely-core/job-server#5264

Revert "Add debug logs"

---

templates/job/detail.html
templates/job_request/detail.html
templates/staff/job_request/detail.html

Closes https://github.com/opensafely-core/job-server/issues/5219
- Make sure that "Job Request" not "Job" is used on the request template
- Clarify some of the language around "Job Requests" and "Jobs"
- Update the incorrect text in the staff area about cancelling a Job Request

Clarify and update text around jobs, job request, and cancelling

---

jobserver/models/job_request.py
tests/unit/jobserver/views/test_job_requests.py
tests/unit/jobserver/views/test_jobs.py

Addresses [comment](https://github.com/opensafely-core/job-server/pull/5274#discussion_r2341762346) on previous PR

Filter for pending/running jobs in get_active_actions

---

DEVELOPERS.md

As discussed in standup today, for clarity.

Improve `DEVELOPERS.md` wording around risky migrations

---

DEVELOPERS.md
docker/docker-compose.yaml

See #4739.
This requires:
* the production database to be upgraded
* developers to update any local testing databases to use PostgreSQL 16

Upgrade to PostgreSQL 16

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Remove the conditional around the filtering of job requests in the JobRequest API (called by the controller sync loop to retrieve job requests that job server thinks are active). Having no jobs is now a possible state for a completed job request, so these are not included in the "active" requests.
Note #5319 made the job request creation page use the RAP API to create jobs for all backends; it has been deployed for a few days and jobs have been created and run successfully.
Fixes #5246

Update job-requests api's definition of active job request
