Procfile
gunicorn.conf.py
jobserver/settings.py
requirements.in
requirements.txt
services/logging.py

This uses structlog to get structured logging and middleware-based request logging.  It configures gunicorn's logs to match the application's log format to make spelunking logs easier.

Configure Logs with Structlog

---

jobserver/settings.py
jobserver/templates/job_detail.html
jobserver/templates/job_list.html
jobserver/urls.py
jobserver/views.py

This adds a fairly simple Job detail page.  The ordering of the fields is fairly random since I don't know enough about them to do any sensible group just yet.  This page is likely to get some orchestration buttons later on at which point it will probably be more obvious how to group them.
Fixes #11

Job Detail Page

---

jobserver/templates/job_detail.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_list.html
jobserver/urls.py
jobserver/views.py

This adds the Workspace detail page.  It links to the Job list page with the appropriate Workspace filter set.
Fixes #15

Workspace Detail Page

---

jobserver/context_processors.py
jobserver/settings.py
jobserver/templates/base.html

This adds menu items so one can navigate the site without knowing  URLs.  It rebuilds the menu using Bootstraps suggested layout, and uses a context processer to build the menu and its states.  I've moved to a higher contrast background (Bootstrap's primary blue) which might be a _little_ garish but we can set up a site-wide theme later.
Fixes #21

Add Menu Items

---

jobserver/settings.py

INSTALLED_APPS is processed top the bottom with the first app to satisfy a search used, so third party apps should go before Django apps, and the project (and its apps) should go before third party apps.
More info can be found here: http://meshy.co.uk/posts/ordering-django-applications

Reorder INSTALLED_APPS

---

jobserver/urls.py

This moves the API under a `/api` prefix so the web UI can take over the un-prefixed URLs.  Pretty URLs for the humans!
It needs to be deployed in conjunction with opensafely/job-runner#29

Move API Under Prefix

---

jobserver/urls.py

This redirects `/` to the Job list page (`/jobs`).  We don't have any user-specific pages currently but it's likely we'll have a dashboard of sorts at the root URL.  For now though we don't want the site to appear broken when visitors first arrive.

Redirect / to Job list page

---

Dockerfile
docker-compose.yml
entrypoint-dev.sh
entrypoint.sh
jobserver/settings.py

This configures production to run `collectstatic` on boot.  The docker-compose-for-local-dev flow is preserved via `entrypoint-dev.sh.
Fixes #36

Set up Static in Production

---

.dockerignore
.github/workflows/main.yml
.pre-commit-config.yaml
Dockerfile
docker-compose.yml

This pins the version of Python we run in Production (and dev via docker-compose) using a Python base image.  We gain better layer caching, fewer layers, and a simpler file by building the image this way.  This also contians changes I made to ensure the docker-compose flow works.  I've also set some options to save on image size (turning off pip caching), avoid caching edge cases (turn off pycs), and avoig buffering issues (turn off buffering).
Note: this removes, what appear to be, the unused dependencies `file` and `docker.io`.  It's been done as an atomic commit to make it easy to revert if that's incorrect.
Fixes #35

Pin Python

---

jobserver/settings.py
requirements.in
requirements.txt
services/sentry.py

This installs the Sentry SDK and configures it, pulling relevant config from the env.
I've pulled the configuration of Sentry itself into a function to avoid polluting the global settings with random variable names.
Fixes #41

Install and Configure Sentry

---

jobserver/templates/job_list.html
jobserver/templates/workspace_list.html
jobserver/templatetags/querystring_tools.py
tests/jobserver/templatetags/test_querystring_tools.py

This adds pagination to the Job and Workspace list pages.
Since we use query args for filtering (via the `url_with[out]_querystring` templatetags) and Pagination also makes use of them I needed to make the templatetags aware of the `page` argument.  This addresses adding/removing a filter while on a page greater than one.  Either use case can result in an erroneously empty page.  Instead I've opted to reset the page arg whenenver a filter is changed.  Note: pagination while using a filter still works as expected.
Fixes #13

Paginate List Pages

---

jobserver/views.py

This sets an ordering for the Workspace list page.  We don't have many workspaces yet and I've only had 4-5 in testing so this was easy to miss.  Luckily Django's [default Paginator](https://github.com/django/django/blob/3.0.7/django/core/paginator.py#L110-L126) warns about this and pytest picks that up by default 🎉

Order Workspaces

---

jobserver/models.py
jobserver/templates/job_list.html
jobserver/templatetags/status_tools.py

This fixes a few small parts of the Job List:
* View button goes to the correct Job detail page now
* Hovering over a status icon shows the Status label (via `title`)
* Convert `DependencyRunning` -> `Pending`
Fixes #63 
Fixes #66

Job List Fixes

---

.github/dependabot.yml

This adds some improvements to our Dependabot config to, hopefully min/max review time.

Dependabot Tweaks

---

jobserver/templates/job_list.html
jobserver/views.py
tests/jobserver/test_views.py

This adds a search box to the Job list page:
Behind the scenes it's searching for either action and ID or just action (if we can't convert the query to an int).
Fixes #69

Add search to Job list page

---

jobserver/templates/job_list.html

This moves the Job list page's two-column layout to Bootstrap's [`md`](https://getbootstrap.com/docs/4.0/layout/grid/#grid-options) column sizes.
The Job list itself still needs more work since it overflows the screen but elements are no longer overlapping so this is a start.
Fixes #64

Push filters below list on smaller viewports

---

jobserver/templates/job_list.html

This fixes a small bug with the Jobs list view where a JobRequest with no Jobs still had a working show/hide button which opened an empty list of Jobs.

Remove expandability of JobRequest when it has no jobs

---

jobserver/api.py
tests/jobserver/test_api.py

This configures the filters on JobViewSet to act like they did before we added `JobRequest`, specifically by hiding the move of `backend` and `workspace` to `JobRequest`.

Fix API Filters

---

jobserver/serializers.py

We ignore the job_request key as a defensive measure.  It shouldn't exist in the first place but we want to make sure job-runner can't update it (at the moment).

Ignore job_request Missing

---

jobserver/serializers.py
jobserver/templates/job_detail.html

This aims to address the two most obvious production failures:
* The APIs list & detail pages breaking for pre-`JobRequest` Jobs (because we had no default for the serializer trying to source `job.job_request.backend`)
* Job Detail pages trying to reverse the Workspace Detail URL with a broken variable.

Prod Fixes

---

services/sentry.py

This ignores the `django-structlog` logger in Sentry.  We want these logs emitted, but we don't want to see unsuccessful requests appearing in Sentry via this logger since they appear as duplicates there.
Fixes #109

Ignore django_structlog Logger in Sentry

---

jobserver/serializers.py

This removes the `default` option to the `workspace` key in the Jobs API.
For `Job`s with no `JobRequest` this results in the removal of their `workspace` key, however I don't think this should be an issue as they're now legacy `Job`s.
With the previous default of an empty string we got errors because DRF took that when building the `workspace` key for those legacy `Job`s and tried to look up various values on the empty string.

Make workspace API Key Optional

---

jobserver/templates/job_list.html
jobserver/templatetags/runtime.py
jobserver/templatetags/status_tools.py
static/css/main.css

This rebuilds the per-JobRequest list of Jobs using CSS grid so we can get table-like functionality without the problems using `<table>` brings (namely fixed-width tables force equal-width columns).  It also drops some columns on smaller devices to make the UI more readable there.
The JobRequest data is still not great on phone sized screens (small/medium in Bootstrap terms):
But I need to have a think on how to make that more responsive since I can't apply a normal Grid to it.

Grid Job List

---

jobserver/templates/workspace_detail.html

This adds a button to the Workspace detail page to take the User to the Add Job page, skipping the select Workspace page.
Fixes #118

Add a Job directly from a Workspace

---

jobserver/settings.py
jobserver/templates/base.html
jobserver/templates/job_list.html
jobserver/urls.py
jobserver/views.py
static/css/main.css
tests/jobserver/test_views.py

This adds a page at `/` (instead of redirecting users to `/jobs` which shows `JobRequest`s for the currently logged in User.  Anonymous Users are redirected to `/jobs` as before so the general Jobs feed can stay open to the public.
As the Dashboard docstring says this is a near identical copy of the `JobRequestList` view but is expected to diverge as we add more features.
Fixes #98

Add User Dashboard

---

jobserver/templates/job_list.html
jobserver/views.py
static/css/main.css

This adds the ability to filter JobRequests by the User who created them:
It also fixes a bug with long filter labels when that filter is active pushing the clear button onto a new line (yay flexbox)
Fixes #86

Filter by User

---

jobserver/templates/base.html

This adds a banner explaining the Alpha status of this site.
Fixes #123

Add site-wide banner espousing Alpha status

---

jobserver/models.py
tests/jobserver/test_models.py

This changes `Job.save()` to only set `Job.started_at` when it hasn't already been set so we don't overwrite it on each subsequent save after creation.
Fixes #127

Only Set started_at Once

---

jobserver/templates/job_list.html
static/css/main.css

This improves the JobRequest portion of the Jobs list page on mobile/different viewport configurations.  It selectively removes columns as the viewport collapses and cuts out words from the Job list toggle button at the same time.
Note: I tried to build this with Grid as per thoughts in #120 but lining up the cells to make borders work didn't look easy (possible?).  Since we needed to remove columns at smaller viewports anyway this turned out to be Good Enough™.
Fixes #120

Job Request List Mobile Fixes

---

jobserver/views.py

This replicates the use of the `ordering` instance variable in `ListView.get_queryset`, which both views completely override.
No more warnings in tests!

Fix QuerySets missing Ordering

---

jobserver/templates/job_list.html

This uses the `page_obj` context variable in Job list and Dashboard template, which is the limited QuerySet from the Pagination class.
Fixes #132

Fix JobRequest list pages (/ & /jobs)

---

.github/workflows/main.yml
Dockerfile
jobserver/views.py

This updates us to Python 3.9.
It seems some of our dependencies don't have wheels for debian with 3.9 so this also moves us away from a slim build so don't have to manually install build tooling.

Python 3.9

---

jobserver/forms.py
jobserver/github.py
jobserver/templates/base.html
jobserver/templates/workspace_select.html
jobserver/views.py
static/js/workspace_select.js
tests/jobserver/test_forms.py
tests/jobserver/test_github.py
tests/jobserver/test_views.py

This enhances the select-or-create Workspace page's Repo and Branch fields to be driven by live GitHub data.  To avoid O(N) requests to GitHub's API I've used their GraphQL (v4) API to create a list of repo-with-branches dictionaries from which the form is generated.
The branch selector is driven by some JavaScript so we don't end up with a giant list or the set of all branches.  The data driving this is loaded into the template to avoid any further API lookups.
Fixes #92

List Repos and Branches

---

jobserver/github.py
jobserver/project.py
jobserver/templates/job_create.html
jobserver/views.py
tests/jobserver/test_github.py

This adds in handling for Branches which don't contain a `project.yaml` file.  I opted to replace the entire page to avoid Users having the option to fill in a partially rendered form since they'll need to reload the page to get actions anyway.

Handle Missing project.yml

---

jobserver/templates/dashboard.html
jobserver/templates/job_list_base.html
jobserver/templates/jobrequest_list.html
jobserver/templatetags/querystring_tools.py
jobserver/views.py

This is the start of adding some visual distinction between the Dashboard (currently logged in user) and Jobs pages.
So far:
* Different titles
* Dashboard gains a link to the Jobs page with the current filters maintained
Fixes #148

Add some visual distinction between My and All Jobs

---

jobserver/templates/job_list_base.html

This fixes the `Requested Actions` field for `JobRequest`s in the job listing views to pull from the correct field, join the values with a comma, and correctly assign to the `title` attribute.

Fix Requested Actions

---

jobserver/models.py
jobserver/templates/job_list_base.html
static/css/main.css
tests/jobserver/test_models.py

This adds a badge to each `JobRequest` row to show which backend it is for.  Since we're space constrained it also removes the `Started At` column and changes how `JobRequest.runtime` works to display a value once any related `Job` has started turning it into more of a running timer.
Fixes #111

Show Backend

---

jobserver/templates/job_list_base.html
static/css/main.css

This removes the previously-missed `Started` column header on the Job List page.

Job List Visual Tweaks

---

jobserver/templates/workspace_select.html

This uses `Workspace.repo_name` since the full URL takes up a lot of space unnecessarily.
Fixes #156

Use Repo name when displaying Workspaces

---

jobserver/models.py
jobserver/views.py
tests/jobserver/test_models.py

This adds a property to our User model to always get a name for a given User, and fixes the Jobs list filter by using that name so GitHub users who haven't set a name can still filter Jobs.
Fixes #147

Fix Users Missing Names in Job Filters

---

jobserver/forms.py
jobserver/templates/job_create.html
jobserver/views.py
tests/jobserver/test_forms.py
tests/jobserver/test_views.py

This removes the `backends` choice from the JobRequest page since we only have one backend currently and it's been causing some confusion (#111).
I've kept the backend badges on the list page as they're small and unobtrusive.
Fixes #157

Remove backend choices for JobRequests

---

jobserver/templates/job_request_create.html

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/?project=5443358)
This static call was left around from when I thought using tooltips for Actions needs might be viable (it wasn't!).

Remove Unused Static File

---

jobserver/forms.py
jobserver/templates/job_request_create.html

This removes the `callback_url` field from the create JobRequest form to avoid invalid URL entries in the short term.
Fixes #174

Hide Callback URL

---

jobserver/templates/job_list_base.html
static/css/main.css

This replaces `JobRequest` runtimes with the time they started at (and reflows the columns so they make sense) on the JobRequest listing pages.  For a variety of reasons it's currently likely that JobRequets end up with their `completed_at` property returning None so they appear to never finish which means their `runtime` property runs off `timezone.now()`… forever increasing.
Fixes #178

Fix JobRequest Runtimes

---

services/sentry.py

We're already ignoring the root `django_structlog` logger, however we're still seeing ERROR logs from `django_structlog.middlewares.request` appear in Sentry, duplicating the exception reporting events already being sent.
Since we don't get a huge number of errors from this site it's been slow to test, but hoping this fixes the issue.
_exasperated noises_

Ignore Specific Django Structlog Logger

---

jobserver/templates/job_list_base.html
static/css/main.css

This sets an appropriate right margin on the `Started At` column header for the three viewports we typically work to (small, medium and large in Bootstrap nomenclature) to work around the Show/Hide button widths.

Correctly position Started At column header

---

jobserver/templates/workspace_detail.html
jobserver/templates/workspace_list.html

This addressess a couple of quick usability fixes on the Workspace pages:
* use `repo_name` on the Workspace list page, and link it to the GitHub repo
* fix the owner/created_by field on the Workspace detail page
* add a title with the absolute datetime to the created_at field on the Workspace detail page
Fixes #183 
Fixes #184

Workspace fixes

---

jobserver/templates/job_request_create.html
jobserver/templates/landing.html
jobserver/templates/workspace_create.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_list.html
jobserver/templates/workspace_select.html

This swaps out all remaining `col-[0-9]` classes for their `md` or `lg` variants so pages are more usable on phone and tablet sized viewports.
Fixes #124

Use mobile friendly column sizing

---

entrypoint.sh
jobserver/admins.py
jobserver/management/commands/ensure_admins.py
pyproject.toml
tests/jobserver/test_admins.py

This gives us an easy way to configure admins at application boot via env vars.
I originally had the code in `get_admins` as a one-liner in settings.py but realised it would be better to 1) test it, 2) document what it's doing and 3) pull it out of the global namespace.

Ensure Admins are Configured on Boot

---

jobserver/middleware.py

API v2 needs to exist alongside v1 while we transition over to it.  This removes the reliance on a named URL for that prefix, ready for the versioned URLs to arrive.
Refs #186

Hardcode API Prefix

---

jobserver/templates/job_detail.html

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/2022221372/?project=5443358&query=is%3Aunresolved)
This makes the JobRequest link on the Job detail page conditional so Jobs without related JobRequests (there are 114) don't break the page.

Conditionally Link to JobRequests

---

jobserver/middleware.py
tests/jobserver/test_middleware.py

This changes our stats middleware to only log when a response is 2xx.
Previously we logged for any response status, including 403s (when we broke the auth), which gave false positives.

Only log API access when response is a success

---

jobserver/templates/workspace_detail.html

This hides the JobRequest creation form (ie the Actions list) when a User is anonymous.  It also expands the details section so the page isn't quite so bare when in this state.
Fixes #217

Fix Workspace Detail for Anon Users

---

jobserver/project.py
jobserver/templates/workspace_detail.html
tests/jobserver/test_project.py

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/2042192762/?project=5443358&query=is%3Aunresolved)
When parsing invalid YAML we get an error and return a 500 to the user.  This catches that error and updates the message we show users when we can't find or parse their `project.yaml`.

Catch invalid YAML

---

jobserver/templates/base.html

This makes use the `next` param to redirect a User back to the current page when clicking `Login`.

Redirect to the current page after logging in

---

jobserver/api.py
jobserver/serializers.py
tests/jobserver/test_api.py

job-runner v1 only knows about action_ids, not actions (a simple rename on job-servers side).  v2 uses action internally, matching how we talk about what they represent IRL too, however we want v1 to keep running with action_id to avoid churn right before a major update.

Keep action_id in v1 API

---

jobserver/forms.py

This sets a more meaningful error message when a User hasn't selected any Actions when creating a `JobRequest`.
Fixes #227

Set a Helpful Actions Error Message

---

jobserver/forms.py

This sets help text under the Repos dropdown when creating a Workspace to help explain why someone's repo might not be there.
I toyed with more extensive language around what team the repo needed to be in under our GitHub Org but decided to keep it short and sweet since they wouldn't be able to self-service the fix anyway.
Fixes #230

Explain Missing Repo When Creating a Workspace

---

jobserver/views.py
tests/jobserver/test_views.py

This ensures there's always a `run_all` action.  When adding it to the list this takes the somewhat blunt approach and treats every other action as a direct "dependency" since this is only used in the UI for the "Needs" accordion.
Fixes #234

Ensure run_all Action

---

jobserver/templates/workspace_detail.html

This add help text blocks to both the Actions list and the Force Run Dependencies toggle to explain how a Users selections affect how their chose Actions are run.
> run_all will run all dependencies
Since `run_all` is defined by a User in their project.yaml (ie not something we do for them currently), should we still include this part?
Fixes #198

Explain Action Run Conditions

---

jobserver/views.py
tests/jobserver/test_views.py

This redirects a User to the Logs page of a Workspace after they create a JobRequest.
Fixes #238

Redirect to a Workspace Logs

---

jobserver/api.py
tests/jobserver/test_api.py

This changes the way we create Jobs in the v2 API.  Currently we delete all Jobs for a given JobRequest, then create a brand new set based on the incoming payload.  This has the advantage of being very simple.  However, it has made our PKs spiral upwards for no particularly good reason.  This change instead groups the incoming Jobs by their JobRequest identifier and then processes them to delete/create/update as appropriate.
The longer term fix to this is to replace `Job.pk` with `Job.identifier`, but in order to that we need to remove all Jobs created via the v1 API (and from before even that!).  Since we only deployed v2 earlier this week I'd like to let it get a bit more use before I start deleting our historical Jobs (or modify them with unique identifiers).
Ref #244

Replace Rather than Recreate Jobs

---

jobserver/project.py
tests/jobserver/test_project.py

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/2072073412/?project=5443358)
When the `needs` key is defined without content it arrives as None, this handles that case.

Handle needs key being Empty

---

jobserver/models.py
tests/jobserver/test_models.py

This removes the field modifying parts of Job's custom `.save()`.  Now that job-runner is setting these fields we can rely on them being in the correct state.
Ref #254

Remove Custom Job.save Paths

---

jobserver/views.py
tests/jobserver/test_views.py

This stops the sorting of actions listed when creating a `JobRequest` so they retain their ordering from project.yaml.
With [carehomes](https://github.com/opensafely/carehomes-research/blob/master/project.yaml):
Fixes #267

Sort Actions by project.yaml Order

---

Dockerfile

This bumps the version of sqlite3 in our Docker image, since the previous version (`3.27.2-3`) no longer exists.
@bloodearnest – am I doing this right?  I've not pinned apt packages before (hadolint told me to), but I assume something changed with `python:3.9-buster` to make this happen?

Bump sqlite3

---

jobserver/models.py
jobserver/project.py
jobserver/templates/workspace_detail.html
jobserver/views.py
tests/jobserver/test_models.py
tests/jobserver/test_project.py
tests/jobserver/test_views.py

This reworks the `get_actions()` function to raise exceptions on errors so we can bubble the `YamlScanner` and fetching-from-github exceptions up to the UI and display them to the User.
This required building a lookup table of action -> status to pass into `get_actions()` so that replaced `Workspace.get_latest_status_for_action()`.
Fixes #270

Display YAML Parsing Errors

---

jobserver/templates/job_detail.html

This wraps the `Job.status_message` field in a `<pre>` instead of a `<code>` to maintain whitespace and newlines, and removes the disused `Job.started` field we removed in #265.
Fixes #271 
Ref #254

Improve Job Detail Page

---

jobserver/views.py
tests/jobserver/test_views.py

We're not showing a control to pick the backend for JobRequests yet but
we do change backend for local development so pick the first one
configured for now.

Use First Configured Backend

---

jobserver/views.py
tests/jobserver/test_views.py

This stops the loading of a project.yaml's actions from GitHub when a User is not logged in, avoiding any penalty to the page load for those users.

Selectively Load Actions

---

jobserver/views.py
tests/jobserver/test_views.py

Django's pagination (provided by MultipleObjectMixin [1]) constructs the
Paginator instance as part of it's get_context_data so the filtered
object_list needed to be passed to that.
[1]: https://github.com/django/django/blob/3.1/django/views/generic/list.py#L113-L136

Fix JobRequestList Status Filtering

---

jobserver/templates/workspace_detail.html

This hides the API URL we're exposing to the Javascript code.
Oops 😬

Hide API URL from WorkspaceDetail Template

---

jobserver/github.py
jobserver/settings.py
jobserver/templates/base.html
tests/jobserver/test_github.py

This limits successful authentications to the OpenSAFELY GitHub Org.  As the custom backend class explains I had to reimplement the provided GitHub backend classes from social-core to let us use our PAT instead of the User's OAuth token.

Limit authentications to OpenSAFELY GitHub Org

---

jobserver/templates/job_detail.html

This switches the wrapping element of `Job.status_message` from `<code>` to `<pre>` so the formatting in that string appear in the UI.
(not a great example but I don't have any YAML failures locally!)
Fixes #271

Respect line breaks and spaces in status messages

---

jobserver/github.py
jobserver/settings.py
jobserver/templates/base.html

This changes the social auth provider's name to match our previous provider's name (`github`), allowing us to avoid trying to work out how to migrate the existing database rows.
Ref #294 
Ref #297

Change Social Provider Name

---

jobserver/settings.py

Fix social auth settings for backend name change.

Remove org suffix from auth settings

---

jobserver/github.py
tests/conftest.py
tests/jobserver/test_github.py

This documents the endpoint we use to make the Organization check and groups all the status code handling into a single conditional.

Improve GitHub Org Check

---

jobserver/migrations/0055_add_workspace_is_archived.py

This fixes the migration name of one of the duplicate migration files which came about because I made #305 and #307 in parallel.

Fix Duplicate Migration Names

---

jobserver/templates/workspace_detail.html

This adds some more help text under the actions list to explain how the `run_all` actions.
Fixes #276

Explain run_all Semantics

---

jobserver/github.py
jobserver/project.py
jobserver/templates/workspace_detail.html
tests/jobserver/test_github.py
tests/jobserver/test_project.py

This surfaces a Workspace's branch missing on GitHub as a first class error state to the UI.  When we can't get a project.yaml from GitHub we check for the presence of the branch (so the extra request is only triggered when there's already no actions to show) and if it's missing bubble that up to the UI.
Fixes #314

Expose Missing Branch as an Error State

---

jobserver/api.py
tests/jobserver/test_api.py

This adds some useful logging inside our only write endpoint, which allowed me to find that we weren't actually deleting Jobs so everything worked by accident 🤒 
Updated the tests to capture the scenario we saw today too.

Correctly Remove Jobs

---

jobserver/context_processors.py
jobserver/models.py
jobserver/templates/status.html
jobserver/views.py
tests/jobserver/test_context_processors.py
tests/jobserver/test_models.py
tests/jobserver/test_views.py

This updates the Stats page (and related backend warnings banners) to handle multiple backends.
When a backend needs to show a warning:

View Backend Stats

---

jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html

This tries to improve the Job & JobRequest detail pages in terms of answering "where am I".  This was born from a researcher sending us links to both pages and it not being clear where in the app one had landed.
Of particular note, I've added breadcrumbs to both pages and promoted the action of a Job to be its title.
**Job Request Detail**
**Job Detail**

Job & JobRequest UI Improvements

---

jobserver/forms.py
jobserver/models.py
jobserver/templates/workspace_detail.html
jobserver/urls.py
jobserver/views.py
tests/jobserver/test_models.py
tests/jobserver/test_views.py

This converts both the Archive and Notifications toggling view(s) to use hidden form inputs with the desired value.
There's no handling of or tests for an invalid form because I couldn't make one…  Any string value is considered truthy, while the lack of a value or the key is considered falsey.

Improve Workspace's Toggle Views

---

jobserver/views.py
tests/jobserver/test_views.py

This some feedback to clicking the Save button on the Settings form so the user has some idea of whether their changes were actually saved.  It also redirects them to the homepage since there's only one setting so they probably don't need to stay there.
Fixes #329

Add Feedback when Saving Settings

---

jobserver/api.py

This refreshes the `job` variable to a Job instance as retrieved from the database.  Without this change the datetime fields (eg `started_at` and `completed_at`) used in calculating Runtime were strings as contained in the payload.
[Related Sentry issue](https://sentry.io/organizations/ebm-datalab/issues/2164587438/?project=5443358&query=is%3Aunresolved)

Refresh Job Instance Before Sending Emails

---

jobserver/github.py
jobserver/settings.py
jobserver/templates/base.html
tests/jobserver/test_github.py

This uses the Social Django middleware to redirect Users to the homepage and explain why they haven't been logged in.  It links to the OpenSAFELY contact page so they can hopefully get in contact with us.
Fixes #331

Handle Wrong Org Logins

---

.github/workflows/main.yml

This uses GitHub Actions to deploy to dokku.
I've tested all these changes apart from `if: github.ref == 'refs/heads/master'` for obvious reasons!
Fixes #327

Deploy Pushes to Master

---

jobserver/templates/base.html
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/templates/workspace_detail.html

This sets up Open Graph meta tags for the site and detail pages so we get rich previews in Slack.
Fixes #324

Better Slack Previews

---

jobserver/templates/job_detail.html

This adds the updated_at timestamp to the JobDetail page.
Leaving warning text because I think it's going to be tied to the work for #332
Refs #344

Add Job.updated_at to JobDetail

---

jobserver/backends.py
jobserver/context_processors.py
jobserver/views.py
tests/jobserver/test_backends.py

This fixes a bug with how we look up stats (making it a per-backend lookup) and changes the warnings check to ignore unacked jobs.
Fixes #332

Fix Backend Warnings

---

jobserver/backends.py
jobserver/forms.py
jobserver/templates/workspace_detail.html
jobserver/views.py
tests/jobserver/test_backends.py
tests/jobserver/test_forms.py
tests/jobserver/test_views.py

This reinstates the Backend selector on the JobRequestCreateForm, adapting it for our current Backends implementation.  The view and form are a little fiddly because of the superuser requirement, but that will all go away when we roll out backends to everyone and we can rely on a ModelForm field declaration instead.
Fixes #350

Admin-Only Backend Selector

---

jobserver/models.py
jobserver/templates/job_detail.html
tests/factories.py
tests/jobserver/test_models.py

This adds a warning to the JobDetail page if the Job has yet to complete AND we haven't seen an update in >30 minutes.  I've phrased the warning to try and avoid specifically saying "this job has died" or "sync is busted".
Fixes #344

Add Stale Data Warning

---

jobserver/templates/workspace_detail.html

This exposes the current state of a Workspace's notification settings below the JobRequestCreate form and provides some explainer text for what that means when notifications are on or off.
**Notifications are on**
**Notifications are off**
Fixes #333

Explain Notification Settings

---

jobserver/emails.py
jobserver/models.py
jobserver/templates/emails/notify_finished.txt
tests/jobserver/test_models.py

This handles some timestamp related edgecases:
* Abstract the finished Job state (`failed` or `succeeded`) into a property
* Only look up Jobs via state (I _think_ I caught all of those)
* Add checks for timestamp fields when doing maths with them
We've agreed on:
* `created_at`: always set
* `updated_at`: always set
* `started_at`: mabye set
* `completed_at`: mabye set
However I've added the check on timestamps involved in maths to ensure we further edge cases don't 500 on us.

Be More Resilient Around Timestamps & State

---

jobserver/api.py
jobserver/emails.py
jobserver/settings.py
tests/jobserver/test_emails.py

This configures the sites domain via the env allowing us to decouple sending emails from the request and tighten up the `ALLOWED_HOSTS` setting.
Fixes #357

Configure Domain

---

jobserver/models.py
tests/jobserver/test_models.py

When Jobs dont' have a `started_at` or `completed_at` (both of which are optional) return `0` for their runtime.

Handle Missing started_at/completed_at in JobRequest.runtime

---

jobserver/models.py
tests/jobserver/test_models.py

This changes `JobRequest.completled_at` to generate a timestamp when its status is `failed` or `succeeded` since we want to know about runtimes for failed Jobs too.  This mirrors how Jobs work.
Fixes #366

Set JobRequest.completed_at when status is failed

---

jobserver/models.py
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/views.py

This hides the non-standard `__error__` Jobs from Users and bubbles their status message up to the JobRequest page.
Fixes #275

Expose JobRequest Errors

---

jobserver/forms.py
jobserver/templates/job_request_list.html
jobserver/views.py
tests/jobserver/test_views.py

This adds an input the Event Log page to jump to a JobRequest by its Identifier field (which we expose in the job-runner logs).  It's only shown to superusers as we don't use identifiers to reference JobRequests for Users.
The Event Log page doesn't feel like the best possible place (suggestions welcome!), but given that page is a list of JobRequests it felt like the obvious place until a better one is found.
Fixes #338

Look Up JobRequest by Identifier

---

jobserver/templates/job_request_detail.html

Show the number of requested actions for JobRequest previews instead of listing them out.
Fixes #379

Show Count of Requested Actions

---

jobserver/templates/_job_request_pagination.html
jobserver/templates/_job_requests.html

This duplicates the pagination controls for a list of JobRequests (used on the Event Log & Workspace Logs pages) to the top of that list, saving a User the need to scroll to the bottom of the list each time they want to go to the next page.

Duplicate Pagination Controls Above List

---

requirements.in
requirements.txt

We dropped slack #264 but missed this dependency.

Drop slackclient Dependency

---

jobserver/templates/job_request_detail.html

This makes the SHA URL on JobRequest detail pages _actually_ work…

Fix JobRequest SHA URL

---

.github/workflows/main.yml
Makefile
tests/jobserver/test_github.py
tests/jobserver/test_project.py

This replaces references to the branch `master` with `main`, including fixing the deploy related bits to do the same.

Master -> Main

---

jobserver/settings.py
requirements.in
requirements.txt

`environs` ships with Django "support" (via setuptools' extras_require), which is `dj_database_url` under the hood.
This switches to the environs function for consistency.
It also removes the database connection max age configuration, which kept database connections open for 10 minutes, since we're not making use of it.

Clean up DB Connection Config

---

jobserver/github.py
jobserver/roles.py
jobserver/settings.py
jobserver/templates/index.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_log.html
jobserver/views.py
pyproject.toml
requirements.in
requirements.txt
tests/conftest.py
tests/integration/test_auth.py
tests/jobserver/test_github.py
tests/jobserver/test_roles.py
tests/jobserver/test_views.py

This removes the requirement to be in the OpenSAFELY GitHub Org when signing up, shifting it to the views where the difference between [un]authenticated users are displayed.
This is a preparatory step towards adding a demo of the platform (with the expectations backend), and the very beginnings (more in intent rather than implementation) of roles based permissions.

Remove GitHub Organisation Requirement for Registration

---

jobserver/models.py
tests/jobserver/test_models.py

This filters Jobs looked up when building the status lookup table for a Workspace's Actions to the action name being looked up, instead of getting the latest Job regardless of Action.
The `test_workspace_get_action_status_lut_success` test has been updated with a more realistic example.
Fixes #416

Look up latest status for the specific action

---

jobserver/api.py
jobserver/models.py
jobserver/releases.py
tests/jobserver/test_api.py
tests/jobserver/test_releases.py

- require valid manifest.json in zip
- fix bug in Release.files listing (via list_files())
- refactor hash_files logic to use list_files()
And some minor fixes:
- fix raising ValidationError() for consistent error formatting
- return full urls in the Location header from release api.

fix: require manifest in uploaded zip

---

nginx.conf.sigil

* default behaviour of redirecting http to https was causing an issue with CloudFlare's SSL/TLS "Flexible" proxying
* revert this when we are able to switch the CF proxy to "Full" mode
* template is from dokku v0.24.1 , the same as the current deployment https://github.com/dokku/dokku/blob/v0.21.4/plugins/nginx-vhosts/templates/nginx.conf.sigil - removes [this block](https://github.com/dokku/dokku/blob/v0.21.4/plugins/nginx-vhosts/templates/nginx.conf.sigil#L14-L16)

Serve the full site over http as well as https

---

jobserver/templates/job_detail.html
jobserver/views.py
tests/jobserver/test_views.py

This has now been wired up on the job-runner side and tested:
https://github.com/opensafely-core/job-runner/pull/186

Enable cancel button for all users

---

jobserver/roles.py
jobserver/views.py
tests/jobserver/test_views.py

This consolidates how we check for superusers and makes use of our `can_run_jobs` function to gate access to views where a User must be part of our GitHub organisation.

Require GH Org Membership  for Some Actions

---

tests/jobserver/test_views.py

When using `mock.patch`, without the `new` kwarg, use `autospec=True` so changes in the object being patched break tests as expected.
Full explanation in this article: https://blog.thea.codes/my-python-testing-style-guide/#a-mock-must-always-have-a-spec

Patch with Autospec

---

jobserver/templates/index.html

* in response to public feedback
mockup:
* part of https://github.com/opensafely-core/job-server/issues/442

Add disclaimer to homepage about links to private repos

---

jobserver/templates/job_detail.html
jobserver/views.py
tests/jobserver/test_views.py

This disables the cancel button when a Job has already finished, and makes the handler view a noop in that situation too.
Fixes #438

Selectively Show Cancel Button

---

jobserver/admin.py

This removes a selection of fields from the User change page in the Admin:
* **password**: We're using social auth so this is an intentially broken password.
* **groups**: We're not using this.
* **user_permissions**: We're not using this.
* **roles**: This field (because it returns Classes) breaks the Admin, and we don't want this configurable from the Admin, which is going away soon-ish™.

Remove Some Fields from Admin Page

---

jobserver/templates/job_request_list.html
jobserver/views.py
tests/jobserver/test_views.py

This adds a new filter to the JobRequest listing page to limit results to Backend.
I've opted to not put the visibility and functionality of this filter behind a Permission as I don't think it adds anything here.
Fixes #455

Filter by Backend

---

jobserver/authorization/admins.py
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/templates/job_request_list.html
jobserver/templates/workspace_detail.html
jobserver/views.py
tests/jobserver/test_views.py

This converts all our uses of `User.is_superuser` for checks in templates to booleans from the `has_role()` function.

Stop using User.is_superuser in Templates

---

jobserver/models.py
jobserver/templates/job_request_detail.html
jobserver/urls.py
jobserver/views.py
tests/jobserver/test_models.py
tests/jobserver/test_views.py

This bring the mighty Cancel button to the JobRequestDetail page.
fixes #437

Cancel All Jobs in a JobRequest

---

jobserver/api.py
jobserver/models.py
jobserver/urls.py
tests/jobserver/test_api.py
tests/jobserver/test_models.py

This adds an authenticated API for Users listing their roles and permissions, with context for any Local Roles (and thus Permissions) as part of the output.
The output for a given User is:
```
{
"permissions": {
"global": ["cancel-job", "run-job"],
"orgs": [],
"projects": [
{
"slug": "great-project",
"permissions": [
"cancel-job",
"check-output",
"run-job",
],
}
],
},
"roles": {
"global": ["CoreDeveloper"],
"orgs": [],
"projects": [
{
"slug": "great-project",
"roles": [
"ProjectCollaborator",
],
}
],
},
}
```
The output for `orgs` mirrors that of `projects` with a slug and related permissions/roles.

Roles & Permissions API

---

jobserver/context_processors.py
tests/jobserver/test_context_processors.py

This hides the backend warning banners when DEBUG is on.
The warning banners are shown when a backend's job-runner hasn't talked to the API in over 5 minutes.  During development this happens most of the time and one ends up with two red banners on every page.  I am very done with this.

Hide Backend Warning Banners in Debug

---

jobserver/settings.py
requirements.txt

This updates Django to 3.2 and sets a `DEFAULT_AUTO_FIELD` as per the warning Django emits.

Bump Django to 3.2

---

jobserver/management/commands/link_user_to_project.py

This switches to `update_or_create` in the `link_user_to_project` script so we can change the Roles of an existing Project member without having to delete them first.

Update or Create ProjectMemberships in link_user_to_project

---

jobserver/management/commands/create_project_from_workspace.py

Some workspace names normalise in such a way that they end up with the same Project, during initial roll-out testing it's ideal to combine them into the same Project (famous last words probably).

Link Multiple Workspaces to Project

---

.github/workflows/main.yml

This sets up [job-level concurrency](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idconcurrency) for the `deploy` job.
I'm not quite sure how to test this does what we want without just using it…
My hope is it blocks just the `deploy` job in the CI workflow on the `main` branch, however I could see it blocking the entire CI workflow while another one ran on `main`, which I don't think would be the worst, just a bit slower than we'd like.
However if this blocks PR branches from running CI then we'll have to roll it back.
Ref #433

Limit Concurrency on the Deploy Action

---

jobserver/settings.py
requirements.in
requirements.txt

This disables Google's FLoC for the site using [django-permissions-policy](https://pypi.org/project/django-permissions-policy/).
[This article](https://adamj.eu/tech/2021/05/04/disabling-floc-googles-new-advertising-technology/) gives a great overview of why we might want this change.

Disable FLoC

---

jobserver/forms.py
jobserver/views/projects.py
tests/jobserver/views/test_projects.py

This adds the full name of a User, if we have that, to the User select2 picker when creating an Invitation to a Project.
Fixes #484

Add Full Name in Project Invitation Selection UI

---

Dockerfile

This swaps the ordering of our dependency installs, putting the less frequent APT ones first, and the more frequent Python ones second, saving us some unnecessary layer invalidation.

Install Python Dependencies after APT Dependencies

---

jobserver/management/commands/link_workspace_to_project.py
pyproject.toml

Some Projects need more than one Workspace attaching to them, this simplifies my ability to do that while migrating Users to the Project lifestyle.  I expect this command to go away once the migration is done.

Add Workspace -> Project Linking Command

---

.github/workflows/main.yml

Much like opensafely-core/cohort-extractor#551 we've hit some kind of caching-related bug in CI, so this strips out the caching, in favour of spending a few more seconds installing dependencies to save many more seconds of developer time.

Remove CI Caching

---

jobserver/models.py
jobserver/templates/project_detail.html
jobserver/templates/project_invitation_create.html
jobserver/templates/project_settings.html
jobserver/urls.py
jobserver/views/projects.py
tests/jobserver/test_models.py
tests/jobserver/views/test_projects.py

This makes a Project's name editable on the settings page, moving ProjectInvitationForm to a new page.  I've also tightened up the UI a little for consistency.
**Settings Page**
**ProjectInvitationForm**

Edit Project Name

---

jobserver/settings.py

The Whitenoise docs say that it should come after SecurityMiddleware [1]
and the Debug Toolbar docs say that it should come after any middleware
that encodes the response [2].  Since Whitenoise could be configured to
do that it makes sense to keep Debug Toolbar after it in the order.
[1]: http://whitenoise.evans.io/en/stable/#quickstart-for-django-apps
[2]: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#enabling-middleware

Move SecurityMiddleware to first position

---

jobserver/management/commands/create_project_from_workspace.py

The `research` suffix was to help us categorise research repos on GitHub, I don't think they're useful in Project names.

Don't use research suffix in Project names

---

jobserver/models.py
jobserver/templates/project_membership_edit.html
jobserver/urls.py
jobserver/views/projects.py
tests/jobserver/test_models.py
tests/jobserver/views/test_projects.py

This fixes the membership removal button form whose view was tested… but still very broken.  This also normalises the view name to match the related view.

Fix Membership Removal

---

jobserver/models.py
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/urls.py
jobserver/views/job_requests.py
jobserver/views/jobs.py
tests/jobserver/test_models.py
tests/jobserver/views/test_job_requests.py
tests/jobserver/views/test_jobs.py

Now that job-runner v2 is well and truly deployed and tested we no longer need to deal with stale Job statuses.

Remove Zombification

---

jobserver/api.py
jobserver/urls.py
requirements.dev.txt
requirements.in
requirements.txt
services/logging.py
services/slack.py
tests/conftest.py
tests/jobserver/test_api.py

This sets up the API for handling Release Notifications from osrelease, and pushing them into a Slack channel.
Example (created by running locally):
Related PR: opensafely-core/output-publisher#21

Handle Release Notifications

---

.github/workflows/main.yml

This switches the deploy action to use the SSH key stored at the Org level.

Switch to Org-level SSH Deploy Key

---

pyproject.toml

This updates the warning filters, mostly to catch Django 4.1 warnings.

Update pytest Warning Filters

---

.github/workflows/main.yml

GitHub Actions doesn't let you address an action version (release) with a short SHA, so taking the opportunity to switch over to our fork of the action.

Switch to our fork of deploy action

---

jobserver/api.py
tests/jobserver/test_api.py

This greatly reduces the noise from POSTing to the JobUpdateAPI view by removing a selection of the log calls and combining the most useful ones (which Jobs got created or updated) into a single line.
Note: You'll notice I also removed some logging context from a ReleaseNotificationAPICreate unit test.  I finally tracked down a way to stop the context bound in JobUpdateAPI from leaking into that view&test.  I still don't know how it got in there given the bind call was assigned to a new variable in another class instance.  The django-structlog middleware isn't in effect because I'm using [a derivative of] RequestFactory.  More digging for another time.

Quieten Logging in JobUpdateAPI

---

jobserver/templates/workspace_detail.html

This script works on DOM elements which are only present when a User is
logged in so lets save some requests to the backend.

Only load the status polling JS when a user is authenticated

---

jobserver/views/job_requests.py
tests/jobserver/views/test_job_requests.py

This returns an unfiltered list of jobs when the filter value is unexpected.

Handle unexpected filter values on the job listing page

---

jobserver/admin.py
jobserver/templates/approve_users.html
jobserver/urls.py
jobserver/views/admin.py
tests/jobserver/test_admin.py
tests/jobserver/views/test_admin.py

This adds an action to the User section of the admin to approve 1 or more Users.  In this context "approval" is simply connecting the Users to 1 or more Backends and Orgs.
This will be superseded later as the onboarding process is built out but for now it allows us to approve users after the changes in #534 and #537.

Add an Approve Action

---

tests/jobserver/templatetags/test_querystring_tools.py
tests/jobserver/test_api.py
tests/jobserver/test_github.py
tests/jobserver/test_project.py
tests/jobserver/test_roles.py
tests/jobserver/views/test_index.py
tests/jobserver/views/test_jobs.py
tests/jobserver/views/test_projects.py
tests/jobserver/views/test_workspaces.py

This tidies up how the mocks currently work across all the tests in an effort to standardise them, and more importantly make sure `autospec=True` is always set.  Now that mocks are no longer context managers I've also pulled them away from the request/response construction bits in each test since they feel more akin to factories at this point.
This was pulled out of the bigger chunk of work to move all URLs under Orgs&Projects, which necessitates the combing of the ProjectWorkspaceDetail and GlobalWorkspaceDetail views, which brought up that the mocks could be a little neater/easier to read.

Better Mocks

---

jobserver/views/job_requests.py
tests/jobserver/views/test_job_requests.py

Django does some automated conversation when we use the ORM so passing
in the string "123" to a filter, eg .filter(pk="123") will find a record
with the integer pk 123.  However if this value can't be converted to an
integer this filter will throw a ValueError.  Since our filter inputs
here are user generated this checks query is using valid values before
adding the filter to the query.
Fixes [this Sentry ticket](https://sentry.io/organizations/ebm-datalab/issues/2424701368/?project=5443358&query=is%3Aunresolved).

Ensure values used for filters exist in the db

---

jobserver/models.py
jobserver/templates/workspace_detail.html
tests/jobserver/test_models.py
tests/jobserver/views/test_workspaces.py

This wraps up the workspace-logs URL reversing (and its many kwargs) into a helper function.

Add a helper function for the Workspace logs URL

---

jobserver/templates/org_detail.html
jobserver/views/orgs.py
tests/jobserver/views/test_orgs.py

This removes the Register Project button, and the text reference to it when there are no Projects, for an Org when the viewing User isn't a member of that Org.

Remove references to project registration when user is not an Org member

---

jobserver/views/projects.py
tests/jobserver/views/test_projects.py

This adds the `ProjectDeveloper` role to ProjectMembership created when a User creates a Project so said User can run jobs in Workspaces for that Project.

Add ProjectDeveloper role to User who creates a Project

---

jobserver/templates/workspace_detail.html

This brings the WorkspaceDetail page inline with the other pages by adding some navigation via breadcrumbs.

Add breadcrumbs to WorkspaceDetail

---

pyproject.toml

Rather than filtering any RemovedInDjango41Warning this changes the filter to only target the dependencies which we know it affects.

Only filter deprecation warnings to know apps

---

jobserver/views/projects.py

Since Graphnet will only be working with dummy data for the PoC they do not need to use the onboarding form.

Enable Simple Project Form for Graphnet

---

.pre-commit-config.yaml

This is a small house keeping change to bring the Python versions in our pre-commit config in line with the Python version we use for local dev, CI, prod, etc.

Bring pre-commit python versions inline with other configs (3.9)

---

jobserver/api.py
jobserver/models.py
static/js/workspace_detail.js
tests/jobserver/test_models.py

This rebuilds the status watching script to use the selected Backend in the form (if one is selected), switching the script to loop the actions in the DOM instead of the actions in the returned data so we can clear each icon before trying to pull it from the data.
This is by no means a polished solution since the status script only runs every 10s so there's up to a 10s wait to see changes come through.
Ref #526

Per Backend Statuses Icons

---

jobserver/forms.py
tests/jobserver/test_forms.py

This removes the default option for Backends when the User has access to more than one Backend so the default isn't accidentlly picked.
Fixes #549

Remove backend default when creating JobRequests

---

README.md
docker-compose.yml
jobserver/authorization/admins.py
tests/jobserver/authorization/test_admins.py

A collection of improvements to the project UX when setting up from scratch.
In particular one no longer has to set `ENSURE_ADMINS`, and its error message is now clearer.
Fixes #398

Improve UX for Initial Project Use

---

jobserver/views/jobs.py
tests/jobserver/views/test_jobs.py

This adds the ability to use a partial identifier to look up a Job when visiting the JobDetail page.  If you use a partial id the view will redirect to itself so the URL becomes the full ID.
I've also reworked the view to use TemplateResponse now that DetailView's `get_object` is no longer a good fit.
Fixes #493

Partial job id search

---

jobserver/forms.py

This adds some help text to the Workspace creation form to explain how it will be used.
Fixes #472

Add help text to the name field of WorkspaceCreateForm

---

jobserver/api.py
tests/jobserver/test_api.py

This adds a fix for the databricks job-runner filtering name and creates a warning in Sentry should we see anything similar from any backend to help us track down misconfigurations during intial backend setup.

Improve Backend Filtering of JobRequests API

---

jobserver/api.py
tests/jobserver/test_api.py

This changes the JobRequestAPIList to only compare the query arg and token-linked backend names when they both have a value.
ref: https://github.com/opensafely-core/job-server/pull/581#discussion_r651656478

Fix Sentry Warning Check

---

jobserver/forms.py
jobserver/models.py
tests/jobserver/views/test_workspaces.py

This removes the "slice" DB option since it was only available on the TPP backend.

Remove the slice db option

---

jobserver/github.py
jobserver/models.py
jobserver/templates/project_detail.html
jobserver/templates/workspace_detail.html
jobserver/views/projects.py
jobserver/views/workspaces.py
tests/jobserver/test_github.py
tests/jobserver/test_models.py
tests/jobserver/views/test_projects.py
tests/jobserver/views/test_workspaces.py

This adds badges to GitHub repo links showing if they are public or private.  As part of this work I realised we were duplicating repo URLs on the ProjectDetail page so this fixes that too.
Fixes #442

Add Badges to Repo URLs

---

jobserver/api.py
jobserver/models.py
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/views/job_requests.py
jobserver/views/jobs.py
tests/jobserver/test_api.py
tests/jobserver/test_models.py
tests/jobserver/views/test_job_requests.py
tests/jobserver/views/test_jobs.py

This selectively does `s/finished/completed/` across the codebase to bring the nomenclature inline with job-runner.  It also fixes an incorrect test discovered along the way.
Fixes #363

Rename "finished" to "completed"

---

README.md

This removes a stale section from the docs talking about testing the v2 API.

Remove V2 Section from Docs

---

.gitignore
DEVELOPERS.md
jobserver/settings.py
scripts/dev-env.sh

Some updates for getting a local development server running
- added a `read_env()` to settings.py so it'll read env variables from the file if it exists
- updated README to use the dev-env.sh script for native and docker setup
- a couple of updates to the dev-env.sh script to get it working for me (ubuntu 20.04)
- Changed the Testing section to document how to run tests (it was duplicating the docker-compose section)

Updates for local development

---

requirements.dev.txt

Adds the version bump I somehow removed from #602

Bump isort from 5.8.0 to 5.9.1

---

jobserver/templates/project_detail.html
jobserver/templates/project_releases.html
jobserver/urls.py
jobserver/views/projects.py
jobserver/views/releases.py
tests/jobserver/views/test_releases.py

This adds a new page at `/<org>/<project>/releases` for us to build the output publishing flow under.  We'll likely change the URL (and view name) as we flesh out the MVP but this allows for developement of the SPA in the meantime.

Add basic releases skeleton page

---

jobserver/authorization/roles.py
jobserver/migrations/0001_initial.py
jobserver/models/__init__.py
jobserver/models/backends.py
jobserver/models/core.py
jobserver/models/onboarding.py
jobserver/models/outputs.py
jobserver/models/stats.py
tests/jobserver/authorization/test_utils.py
tests/jobserver/models/test_backends.py
tests/jobserver/models/test_core.py
tests/jobserver/models/test_onboarding.py
tests/jobserver/models/test_outputs.py
tests/jobserver/models/test_stats.py

This breaks models module into a package since it's grown fairly large.  The new modules are a little arbitrary but here is my reasoning:
* `onboarding` because the spike into an onboarding flow showed we likely needed more than just `ResearcherRegistration` to preserve state of in-flight sign ups.
* `stats` because it didn't have a better home.
* `backends` because they're sort of a (core?) sub-system unto themselves.
* `outputs` because the project outputs voyage is adding more models around this.
No new migrations are required because of the importing in `jobserver/models/__init__.py` but unfortuately the Roles definitions needed updating.

Split Up Models

---

jobserver/views/index.py

This removes the extra queries spawned by Workspace.get_absolute_url calls for the list of Workspaces after moving Workspaces under Org and Project.

Remove extra queries from URL construction on index page

---

assets/src/scripts/main.js
jobserver/templates/base.html

So that we can track IE11 users in a privacy-friendly way.

Update Plausible Analytics script

---

jobserver/views/workspaces.py

This moves the main gate for running a Job back to `can_run_jobs()` which is a facade for "is logged in AND is member of the correct GitHub Org".
There are some other pieces of the template which used this check (showing the Archive and Notifications buttons) but the views behind those buttons were still gated on the `can_run_jobs()` call so no change is needed for those.

Checking GitHub Organisation Membership to Run a Job

---

jobserver/views/projects.py
tests/jobserver/views/test_projects.py

This stops a User clicking the accept invitation link for the second time getting a 500.

Ignore Accepted Invitations

---

jobserver/models/outputs.py
jobserver/releases.py
tests/conftest.py
tests/factories.py
tests/jobserver/models/test_outputs.py
tests/jobserver/test_api.py
tests/jobserver/test_models.py
tests/jobserver/test_releases.py

1. New ReleaseUploadFactory to setup a zip stream and valid hash for
testing upload handling
2. Re-implementend ReleaseFactory in order to handle the fact that it
needs filesystem state set up first before we create the ORM object,
and that some of its attribute depend on the hash of the uploaded
content.
3. Add autouse fixture to ensure every tests uses a clean
RELEASE_STORAGE dir
4. Refactored some of handle_release workflow to share more things in
common with the testing setup

Refactor Release testing machinery

---

Makefile
jobserver/api/releases.py
jobserver/urls.py
tests/jobserver/api/test_releases.py

One to list the files in release, another to get the file contents.
Download api supports a production optimisation for using nginx.
Drive by fix to report missing coverage lines by default.
Fixes #627

Add releases read API

---

jobserver/authorization/admins.py
jobserver/authorization/decorators.py
jobserver/authorization/permissions.py
jobserver/authorization/roles.py
jobserver/forms.py
jobserver/templates/user_detail.html
jobserver/views/admin.py
jobserver/views/orgs.py
jobserver/views/users.py
tests/conftest.py
tests/jobserver/api/test_jobs.py
tests/jobserver/authorization/test_admins.py
tests/jobserver/authorization/test_decorators.py
tests/jobserver/models/test_core.py
tests/jobserver/test_admin.py
tests/jobserver/views/test_admin.py
tests/jobserver/views/test_orgs.py
tests/jobserver/views/test_projects.py

This removes our use of the SuperUser Role from all parts of the code base, opting to either add an appropriate new permission or fallback to `User.is_superuser`.
The Role itself can be removed when all Users no longer have it assigned.

Remove Use of SuperUser Role

---

docker-compose.yml
dotenv-sample
jobserver/github.py
jobserver/settings.py
pyproject.toml
tests/conftest.py
tests/integration/test_auth.py
tests/jobserver/test_github.py

This is a near full revert of 5c3313c, except the auth backend now handles multiple GitHub Orgs, provided via configuration.
This continues to a separate check to our permissions framework, but will enable us to get rid of `can_run_jobs` as per #642 
Fixes #644

Require Configured GitHub Orgs to Login

---

jobserver/models/core.py
jobserver/templates/project_detail.html
jobserver/templates/project_release_list.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_release_list.html
jobserver/urls.py
jobserver/views/projects.py
jobserver/views/releases.py
tests/factories.py
tests/jobserver/models/test_core.py
tests/jobserver/views/test_releases.py

This adds two new views listing Releases in their Workspace or Project contexts.  It includes a a function to get the latest version of each file, akin to a current working directory view for a Workspace, however the implementation of this is expected to potentially change as the current voyage proceeds.
**Workspace Files**
**Project Files**
Fixes #654

List Releases for Workspaces and Projects

---

jobserver/templates/project_detail.html
jobserver/templates/workspace_detail.html
jobserver/views/projects.py
jobserver/views/workspaces.py

Releases are still being developed but we don't want to run a staging site or have a long running branch while developing them so this adds logic to remove links to them from the relevant pages.

Add a Feature Flag for Release Pages

---

jobserver/management/commands/release.py
jobserver/releases.py
pyproject.toml
tests/factories.py
tests/jobserver/test_releases.py

Usage:
python manage.py release <workspace> <backend> directory/
Involved a refactor of the ReleaseUploadFactory code to extract the zip-construction logic, including automatically generating a manifest.
Also, found and fixed a bug in the exclusion of MANIFEST_PATH from the release hash.

Add a release management command for local dev:

---

jobserver/models/core.py
jobserver/models/outputs.py
jobserver/templates/outputs-spa.html
jobserver/templates/release_detail.html
jobserver/templates/workspace_detail.html
jobserver/templates/workspace_output_list.html
jobserver/urls.py
jobserver/views/workspaces.py
tests/jobserver/models/test_core.py
tests/jobserver/models/test_outputs.py
tests/jobserver/views/test_workspaces.py

This adds a new entrypoint to the SPA, the "outputs" page, our meta view showing the latest version of each file across all releases.
I've pulled the SPA template out into an include so we can use it in two different contexts and not complicate the breadcrumb construction.
Fixes #663

Add Outputs Page

---

jobserver/models/core.py
jobserver/models/outputs.py
jobserver/urls.py
jobserver/views/releases.py
tests/jobserver/models/test_core.py

This puts the API URL names under the `api` namespace.
Fixes #664

Namespace API URLs

---

jobserver/authorization/roles.py
jobserver/views/users.py

This enables the ProjectCoordinator role on User models.
Fixes #645

Allow ProjectCoordinator on Users

---

tests/jobserver/api/test_jobs.py
tests/jobserver/models/test_core.py
tests/jobserver/test_backends.py
tests/jobserver/test_context_processors.py
tests/jobserver/test_releases.py
tests/jobserver/views/test_status.py
tests/utils.py

This pulls the `minutes_ago` function out of a test function and into a utils module, applying it everywhere we can.  It also adds `seconds_ago` since we were also doing that in various places.
Fixes #669

Add <time>_ago Helper Functions

---

jobserver/forms.py
jobserver/templates/user_detail.html
tests/jobserver/test_forms.py
tests/jobserver/views/test_users.py

This fixes the form on the UserDetail page by 1) tell us there was a problem by rendering the error and 2) use an appropriate form field for a boolean.

Fix User Detail Form

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/PrepareButton/PrepareButton.jsx
assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/index.jsx
jobserver/api/releases.py
jobserver/authorization/permissions.py
jobserver/authorization/roles.py
jobserver/models/core.py
jobserver/models/outputs.py
jobserver/templates/outputs-spa.html
jobserver/templates/workspace_detail.html
jobserver/urls.py
jobserver/views/releases.py
jobserver/views/workspaces.py
tests/jobserver/api/test_jobs.py
tests/jobserver/api/test_releases.py
tests/jobserver/models/test_core.py
tests/jobserver/models/test_outputs.py
tests/jobserver/test_utils.py
tests/jobserver/views/test_releases.py

This teaches the outputs SPA about the snapshot preparation URL, showing a "Publish" button if it's instantiated with one:
Since a User must already be privileged to view the current ReleaseFile for a Workspace we don't need to do any further permission checks.
The SPA will use the prepare URL to post a list of ReleaseFile IDs to the API, which creates a draft Snapshot, and returns the direct URL for an SPA.
I've not taken much (any) time to style the button because there's a confirmation flow to add on top of it, where I'll deal with that.
Refs #675

Move Publish Outputs into SPA

---

jobserver/api/releases.py
jobserver/views/releases.py
tests/jobserver/api/test_releases.py
tests/jobserver/views/test_releases.py

This allows the general public to view published Snapshots (eg on the project or workspace pages) without any permissions, or even being logged in.
I've duplicated the `validate_release_access` function for this because the current one doesn't quite fit with this paradigm, but I'd like to see if we can combine them in #699.
Ref #702 
Ref #689

Open Published Snapshots to the Public

---

jobserver/api/releases.py
jobserver/templates/project_detail.html
jobserver/templates/workspace_output_list.html
jobserver/views/projects.py
jobserver/views/releases.py
tests/jobserver/api/test_releases.py
tests/jobserver/views/test_projects.py
tests/jobserver/views/test_releases.py

This adds a list of outputs to the ProjectDetail page.  It only takes the most recent published version from each Workspace.  Each output links to the same entry point used on the Workspace's Outputs page.
Fixes #702

List Outputs on Project page

---

assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
jobserver/templates/outputs-spa.html
package-lock.json
package.json
vite.config.js

- Add polyfills for Fetch and Promise
- Tell Vite Legacy to specifically target IE11
- Fix File List height depending on screen size

Fixes for IE11 and file list height on small screens

---

jobserver/templates/workspace_detail.html

This pulls the branch name from a muted string at the end of the repo name (where we all missed it!) into its own section.
Fixes #715

Pull Branch Name into a Section

---

jobserver/api/releases.py
tests/jobserver/api/test_releases.py

DRF helpfully strips of leading paths.

Reparse content-disposition header to get full filename

---

jobserver/authorization/roles.py
jobserver/views/workspaces.py
tests/jobserver/api/test_jobs.py
tests/jobserver/models/test_core.py
tests/jobserver/views/test_workspaces.py

This double checks a User has the `manage_project_workspaces` permission in the WorkspaceCreate view itself.  It also moves this permission onto the `ProjectDeveloper` role so researchers can create workspaces.

Enforce Permissions for Workspace Creation

---

package-lock.json
package.json
vite.config.js

- Update @vitejs/plugin-legacy to 1.5.1
- Remove Bluebird as Promises has a polyfill ([source](https://github.com/vitejs/vite/blob/365e3ad224e83e99811e61edd8a6aab7b2280cce/packages/plugin-legacy/CHANGELOG.md#151-2021-08-03))

Update Vite legacy dependency

---

jobserver/templates/workspace_release_list.html
jobserver/views/releases.py
tests/jobserver/views/test_releases.py

This disables the view and files buttons on the ReleaseList page when a Release has no files to view (eg from a broken upload) and returns a 404 on the ReleaseDetail page if there are no files for a Release.
Fixes #751

Disable Viewing Files when Release is Empty

---

jobserver/templates/workspace_detail.html
jobserver/views/workspaces.py

This tidies up the outputs buttons on a WorkspaceDetail page so they're in the order one gains access to them, and improve the logic around when they're added.
I've also removed the two buttons (with different names!) pointing to the "current" outputs (latest version of every file released in a workspace) since that's available via the Released Outputs and it felt confusing in the UI.

Better Outputs Buttons

---

jobserver/templates/workspace_detail.html
jobserver/views/workspaces.py
tests/jobserver/views/test_workspaces.py

This checks that the current user has the `create_snapshot` permission to gate showing the Publish button.
Fixes #756

Check Perms for Publish Button

---

jobserver/templates/snapshot_detail.html

We mark draft versions of published outputs, so this marks published ones explicitly too.
Fixes #757

Denote Published Outputs

---

assets/src/scripts/outputs-viewer/components/FileList/List.jsx
assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
assets/src/scripts/outputs-viewer/hooks/use-file.js
assets/src/scripts/outputs-viewer/utils/pretty-file-size.js

- Show file size as `title` in the file list
- Improve performance when rendering CSVs
- Stop large CSVs from being previewed

File size fixes for the Outputs SPA

---

jobserver/models/outputs.py
jobserver/releases.py
jobserver/templates/release_detail.html
jobserver/templates/workspace_release_list.html
jobserver/urls.py
jobserver/views/releases.py
tests/jobserver/models/test_outputs.py
tests/jobserver/test_releases.py
tests/jobserver/views/test_releases.py

This adds the ability for privileged users (those with ProjectCollaborator role/`view_release_file` permission) to download a zip of a Release.
**Downlad from Release list page**
**Download from ReleaseDetail page** 
Fixes #766

Download Releases

---

assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
assets/src/scripts/outputs-viewer/utils/file-type-match.js

- Debounce the file filter functions to improve performance
- JSON files can now be previewed
- Do not preview CSV files over 500 lines
- Preview first 1000 lines of CSV files between 1000-5000 lines long

Fixes for outputs file viewer SPA

---

jobserver/models/outputs.py
jobserver/templates/snapshot_detail.html
jobserver/urls.py
jobserver/views/releases.py
tests/jobserver/models/test_outputs.py
tests/jobserver/views/test_releases.py

This lets users download the files in a Snapshot (published outputs) as a zip.  Users must be a ProjectCollaborator to download the files in a draft Snapshot.
Fixes #767

Download Snapshots

---

jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/views/job_requests.py
jobserver/views/jobs.py
tests/jobserver/views/test_job_requests.py
tests/jobserver/views/test_jobs.py

This switches cancelling jobs on either the Job or JobRequest detail pages to use the `cancel_job` permission instead of relying on `can_run_jobs()`.  This refines who can cancel jobs, to only those with either the CoreDeveloper role or the ProjectDeveloper role, the latter of which is tied to the Project any given Job[Request] is owned by.
Ref #642

Remove Some Uses of can_run_jobs

---

jobserver/urls.py

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/2551065720/?project=5443358&query=is%3Aunresolved)
This stops us 500ing when we try to look up a model with an integer PK with a string, instead returning a 404 as one would expect.

Apply int converters to all integer PKs

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.module.scss
assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
package-lock.json
package.json

[React window](https://github.com/bvaughn/react-window) works by only rendering part of a large data set (just enough to fill the viewport). This helps address some common performance bottlenecks:
- It reduces the amount of work (and time) required to render the initial view and to process updates.
- It reduces the memory footprint by avoiding over-allocation of DOM nodes.
We can use this library for the FileList to help alleviate performance issues.
---
Closes #802

Render FileList using a virtualisation library

---

assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.module.scss
assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx

So that the padding doesn't overlap the links.
React Window sets an exact height on each element using a prop, which means padding and margin do not work as expected. Therefore we need to add padding to outer elements, and make the height of each list item taller to space them out.

Update FileList styles

---

assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
assets/src/scripts/outputs-viewer/components/Image/Image.jsx
assets/src/scripts/outputs-viewer/components/NoPreview/NoPreview.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
assets/src/scripts/outputs-viewer/components/Text/Text.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx

Error in `react-papaparse`: `Cannot read property 'readable' of undefined`
- Do not show preview components if data returned is not defined
- Replace `data` prop with query in each preview component
- Define a `<NoPreview />` component to be used when preview is failing

Fix error when no data passed to preview components

---

assets/src/scripts/outputs-viewer/components/Toast/Toast.jsx

Fix word break for long file names

---

jobserver/models/core.py
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/urls.py
jobserver/views/job_requests.py
jobserver/views/jobs.py
tests/jobserver/models/test_core.py
tests/jobserver/views/test_job_requests.py
tests/jobserver/views/test_jobs.py

This moves the `/jobs/*` and `/job-requests/*` URLs under the main URL hiearchy of Org -> Project -> Workspace, and does some related housekeeping.
`/jobs/` has been moved to `/event-log/` to match the menu item.
Redirect views have been added for the old URLs.

Move Job&JobRequest URLs under Orgs, Projects, & Workspaces

---

jobserver/views/job_requests.py
tests/jobserver/views/test_job_requests.py

This ensures only users with access to one or more Backends can access the page to run jobs.
It also tidies up the JobRequestCreate tests on top of the work done in #814 
Fixes #653

Check Users have Access to Backends to Run Jobs

---

jobserver/templates/_job_requests.html
jobserver/templates/_release_list.html
jobserver/templates/index.html
jobserver/templates/job_detail.html
jobserver/templates/job_request_detail.html
jobserver/templates/project_detail.html
jobserver/templates/workspace_detail.html

This adds the timezone, in the format +0000, to all timestamp hovers across the site (where we use the `title` attribute) and a short explainer to why timestamps are all in UTC.
We can't reliably get the local timezone for a User without asking them to set it on their account which currently felt overkill.
Fixes #451

Add Timezone to Timings Hovers

---

assets/src/scripts/outputs-viewer/components/Button/PrepareButton.jsx
assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
assets/src/scripts/outputs-viewer/components/Image/Image.jsx
assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
assets/src/scripts/outputs-viewer/components/Table/Table.jsx
assets/src/scripts/outputs-viewer/components/Text/Text.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
assets/src/scripts/outputs-viewer/components/Viewer/Wrapper.jsx
assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/hooks/use-file.js

Whilst adding tests (https://github.com/opensafely-core/job-server/issues/711) - various issues with the code have been identified. This PR covers fixes to the Outputs SPA as the first part of adding tests.
---
One issues identified was added in https://github.com/opensafely-core/job-server/pull/821:
> Replace `data` prop with query in each preview component
This meant that each child component of the `<Viewer />` required knowledge of the state of the query. This overcomplicates each child component, and therefore has been reverted to pass `data` as a prop to the child components.

Various fixes for the Outputs SPA

---

assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/hooks/use-file.js

- `Headers()` constructor is broken with Axios in Firefox
- `.toJSON()` is not required for retrieving the error message

Fix SPA errors in Firefox

---

jobserver/templates/index.html
tests/jobserver/views/test_index.py

This fixes the test for checking the page without users by making sure there is a Workspace so that whole section of the template loads, and fixes the actual bug by only showing the button block when the user is authenticated.
The broken version didn't deploy thanks to the deploy checks at least.

Fix Homepage for Unauthenticated Users

---

jobserver/templates/job_detail.html

This adds explanations for what users are seeing on a jobs page, particularly around the timings of jobs.
Having tried out the suggestions in #610 I opted not to use long form labels as it made the section look very crowded.  The smaller explainer paragraphs mean a regular user can get the information they need at a glance but the extra detail is still there if needed.
I've also threaded in some "live" information to the top and timing paragraph to help with the context of what a secure backend actually is.
Fixes #610

Better Timing Labels

---

dotenv-sample

Add and improve env var docs.
Based on treating these docs like they're for staff working on the central service I opted not to document the DATABASE_URL which is set up with a default for local dev.
Fixes #607

Improve Env Vars Docs

---

jobserver/templates/job_request_create.html

This adds a `Created` label to the latest JobRequest section of the Run Jobs page with a relative time, and the absolute date and time on hover.
The runtime column of the related Jobs already had the absolute date and time for when a Job started so I've left that as is.
Fixes #856

Add JobRequest Created

---

jobserver/authorization/roles.py
tests/jobserver/api/test_jobs.py
tests/jobserver/models/test_core.py

This removes the permissions attached to the CoreDeveloper role which were already on other roles.  This moves CoreDeveloper to being a more typical role rather than a bucket for "do everything".
Fixes #641

Remove Duplicate Permissions from CoreDeveloper Role

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

This adds the the relevant Backend name to the various index endpoints ready for the UI to display it.
Fixes #755

Add Backend to Index Endpoints

---

jobserver/project.py
tests/unit/jobserver/test_project.py

We render project.yaml contents on JobRequest detail pages, but any reasonably sized file adds a lot of scrolling to the page.
In lieu of the upcoming parser library this makes some aesthetic changes in an attempt to make the page a little more usable.
**Before:**
**After:**

Tidier project.yaml Rendering

---

jobserver/authorization/roles.py

This lets us set the ProjectDeveloper role "globally" on a User instance, so staff can have this role without having to be members of every Project.  This is more important now that running jobs is tied to the `run_job` permission provided by this role.

Enable ProjectDeveloper role being set on User instances

---

assets/src/styles/main.scss
jobserver/templates/workspace_log.html
jobserver/templatetags/selected_filter.py
jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

This adds a backend filter to the WorkspaceLog page, using GET args as we do with all our other filter pages:
Fixes #527

Filter Workspace Logs by Backend

---

jobserver/templates/index.html
tests/unit/jobserver/views/test_index.py

Currently when a User signs up/first logs in they have no related Org since we don't know which Org to place them in.  This removes the new workspace button from the homepage while a user is in that state.
Ref #632

Hide new workspace button when first signed up

---

jobserver/project.py

links_map is always going to have an (original, replacement) tuple for
every run line at this point, even if `replacement` is the same as
`original`, so we don't need to remove Nones which aren't there.

Remove no-op compacting

---

pyproject.toml

I find this gives more manageable output.
Compare:
```
(job-server) inglesp@gronk:~/work/ebmdatalab/opensafely/job-server$ pytest tests/unit/jobserver/api/test_releases.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
django: settings: jobserver.settings (from ini)
rootdir: /home/inglesp/work/ebmdatalab/opensafely/job-server, configfile: pyproject.toml
plugins: network-0.0.1, subtests-0.5.0, django-4.4.0, env-0.6.2, Faker-8.10.1, freezegun-0.4.2, cov-2.12.1, mock-3.6.1
collected 53 items …
```

Set --tb=native by default

---

staff/views/index.py

as per https://github.com/opensafely-core/job-server/pull/844/files?file-filters%5B%5D=.py#r704314663
This adds a bit of consistency and thus readability to the config.

break all staff index search config dicts across multiple lines

---

jobserver/pipeline.py
jobserver/settings.py
tests/integration/test_auth.py
tests/unit/jobserver/test_pipeline.py

Some duct tape to tell us when a user first logs into the job-server while we build a better onboarding story.

Notify Slack when a New User Registers

---

staff/templates/staff/user_detail.html
staff/views/users.py
tests/unit/staff/views/test_users.py

This displays the roles for Projects and Orgs against the relevant Projects/Orgs on the user page of the staff admin:
Note: we don't use roles on OrgMemberships currently, but this will display them when we do.

Display All User Roles

---

staff/views/users.py

This sorts the role labels for Orgs & Projects listed on a User's detail page in the Staff Area.

Sort the roles for users org&projects lists

---

jobserver/authorization/decorators.py
tests/unit/jobserver/authorization/test_decorators.py
tests/unit/staff/views/test_orgs.py
tests/unit/staff/views/test_projects.py
tests/unit/staff/views/test_users.py
tests/unit/staff/views/test_workspaces.py

Django's defaults.permission_denied will handle these exceptions and return a 403 with our 403.html template as well.

Fix 403 Pages

---

staff/views/index.py

This enhances the Staff Area search items with Orgs, Projects, and a Users membership in either, eg searching `bristol` will find the Org and any users who are members of it.

Further Staff Searches

---

jobserver/models/core.py
tests/factories.py
tests/unit/jobserver/models/test_core.py

This sets a default for `Org.github_orgs` so that we at least have something in the field to stop the site being broken for users.
Fixes #960

Set Default GitHub Org

---

staff/views/users.py

Reinstate showing all orgs on the set orgs page for a user as per: https://github.com/opensafely-core/job-server/pull/955#discussion_r708297056

Show all orgs on the User's set orgs page

---

gunicorn.conf.py

A single sync worker is usually not a good idea with gunicorn, as one
long request will block everything, and we're using whitenoise so there
are more requests for a pageload.
I temporarily added up to 4 workers in prod, but only 2 were every
really used, so 3 seemed a good start.

Set workers in prod to 3, rather than the default of 1.

---

applications/views.py
jobserver/authorization/permissions.py
jobserver/authorization/roles.py
tests/unit/applications/test_views.py
tests/unit/jobserver/api/test_jobs.py
tests/unit/jobserver/models/test_core.py

This adds a requirement that users are logged in, and either created the application or have the `application_manage` permission (the idea being that staff will use the latter).

Require Auth for Applications

---

jobserver/urls.py

Rather than raising 500s to various spiders and scrapers of the form "Field 'foo' expected a number but got 'somestring'" we can automatically return a 404.
This tidies up a subset of our Sentry events which are just noise.

Set types for each URL capture

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Previously, if the job already existed it would notify based on the
_old_ `status_message` of the job, not the one to which we were about to
update.  This didn't get caught by the tests because if the job was a
new job then different update logic was used.
This PR amends the test to catch this condition and then slightly
refactors the update logic to fix the bug and hopefully make it clearer
(though its arguable whether the changes are an overall improvement).

Fix bug with "internal error" notifications

---

applications/form_spec_helpers.py
applications/form_specs.py
applications/templates/applications/page.html
jobserver/templates/components/form_email.html
jobserver/templates/components/form_text.html
jobserver/templates/components/form_textarea.html
tests/unit/applications/test_form_spec_helpers.py

This adds the ability to override field templates and add attrs to fields in the spec module.  Some extra form component types are added for the overrides, and the Attributes class handles a very specific subset of overrides for the component templates.  Currently only the text component implements the extra attributes.

Add Field Types for the Wizard Forms

---

jobserver/context_processors.py
jobserver/settings.py
jobserver/templates/base.html
jobserver/templates/index.html
jobserver/templates/job_request_create.html
jobserver/templates/outputs-spa.html
jobserver/templates/project_create.html
jobserver/templates/project_onboarding_create.html
jobserver/templates/workspace_create.html
requirements.prod.txt
tests/unit/jobserver/test_context_processors.py

As part of the `django-vite` package upgrade, we now don't need our custom `scripts_attrs` from the content processors.
Closes https://github.com/opensafely-core/job-server/pull/1015
(Also a small fix for the display width of the Outputs SPA)

Update Django Vite package and remove scripts_attrs

---

.github/workflows/main.yml

This sets up our CI to create releases on Sentry using the action they maintain.
Fixes #1022

Configure Sentry Releases

---

applications/templates/applications/sign_in.html
jobserver/templates/partials/header.html

This is sort of redundant following #1036 which disallows these URLs in
`robots.txt`. But this might have a more immediate effect than the
`robots.txt` changes and so seems worth trying.

Add `rel="nofollow"` to login links

---

jobserver/views/projects.py
tests/unit/jobserver/views/test_projects.py

ProjectCreate checks request.user is a member of the project and 404s if
not, but login_required will get a user to login and return them to the
view so this is a slightly nicer UX for users who should have access but
are just logged out but doesn't change anything for non-members.

Apply login_required to ProjectCreate

---

jobserver/templates/job_request_detail.html
jobserver/templates/project_detail.html
jobserver/templates/workspace_detail.html
jobserver/views/projects.py
jobserver/views/workspaces.py

This removes our feature flag for releases, swapping in some conditionals for the Releases section on Project and Workspace pages so we aren't left with empty card bodies.

Remove Releases Feature Flag

---

assets/src/scripts/outputs-viewer/hooks/use-file-list.js
assets/src/scripts/outputs-viewer/tests/hooks/use-file-list.test.js

We pull a common prefix from the filenames served to the outputs viewer
app.  We use this prefix to create a `shortName` value on the files
array for display in the file list UI.  However with one file the
longest common prefix is the entire filename, leading to an empty
shortName, and showing an empty file list.
Fixes #1073

Avoid setting blank shortNames for single file outputs responses

---

applications/models.py
applications/urls.py
applications/views.py
jobserver/context_processors.py
staff/templates/staff/application_detail.html
staff/templates/staff/application_list.html
staff/templates/staff/index.html
staff/urls.py
staff/views/applications.py
staff/views/index.py
tests/unit/applications/test_models.py
tests/unit/applications/test_views.py
tests/unit/jobserver/test_urls.py
tests/unit/staff/views/test_applications.py

This adds list and detail pages for Applications to the Staff area and makes applications searchable by their creator on the homepage.
The fields listed on the detail pages have all been manually added for now since we're not quite sure how it's going to work so I just did some vim macro magic with the intention that we should definitely do something better there once we have an idea how the application-dependent models are going to work.

Add Applications to the Staff Area

---

staff/templates/staff/user_detail.html

This adds Orgs & Projects to the UserDetail page even if there are no items to display.  For Orgs this is because this is where we get to the page to select which orgs are valid.  For both lists it's useful to see when they are empty as this is something to fix with the user.

Always show orgs and projects section of the user detail staff page

---

applications/templates/applications/sign_in.html
jobserver/settings.py
jobserver/templates/login.html
jobserver/templates/partials/header.html
jobserver/urls.py
jobserver/utils.py
jobserver/views/users.py
tests/integration/test_auth.py
tests/unit/jobserver/test_utils.py
tests/unit/jobserver/views/test_users.py

Previously, get requests were made to GH from each page. Now, post requests are made to GH from a new login page. Post requests don't create new sessions in the database; the new login page is simply a nice-to-have.
Thanks for the discussion about this PR, both here and on Slack ([open redirects](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1633341732201500); [the applications flow](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1633342236207800)).
I'm going to squash and merge, if this PR is approved, so the commit messages are terse. However, I have:
* ensured post requests are made to GH by switching from links to buttons and by decorating `social_django_views.auth` with `csrf_exempt` and `require_POST`
* created a new `Login` view that checks whether the value of the `next` URL …

Make post requests from a new login page

---

staff/templates/staff/user_list.html
staff/views/users.py
tests/unit/staff/views/test_users.py

This adds an org filter to the staff area's UserList page.  This will be useful when setting up new user's orgs to confirm that all the required users have been done.

Filter Users by Org

---

jobserver/api/jobs.py

This creates locking problems under SQLite (see #1087 and #1032). But we
don't actually need transactionaility here because the sync process this
endpoint participates in is self-healing: the caller just declares the
full state of every active job and we persist that. If we only manage a
partial update then we'll correct that the next time we get polled.

Remove transaction wrapper from `JobAPIUpdate.post` view

---

applications/form_spec_helpers.py
applications/templates/applications/confirmation.html
applications/urls.py
applications/views.py
applications/wizard.py
tests/unit/applications/test_views.py
tests/unit/jobserver/test_urls.py

*Rebuilt after switching to mirroring the staff template and using Field to define value and validity*
This adds final validation to the Wizard so we know if the confirmation can be submitted or not.  Validation is bubbled up through the form_spec helpers since Field already knows if it's valid or not so we build up from there to the Wizard.

Validate Entire Application on Confirmation Page

---

static/robots.txt

So that search engines can index the form start page.

Remove form URLs from robots.txt

---

staff/templates/staff/application_detail.html

Following change in 9261afbb09f4573f4a8167bd259c0e160173f652 which
renamed `instance` to `page_instance`.

Fix review details on staff review page

---

applications/views.py
staff/views/applications.py
tests/unit/applications/test_views.py

* Add `application` instances to context on staff Application detail page
* Don't notifiy slack of new or submitte applications in debug mode

Application Fixes

---

jobserver/releases.py
jobserver/views/releases.py

After moving to Postgres the "list of releases" page for a Workspace suffered from some N+1 query issues. Locally, with 6 Releases, and the latest files item, it generated 3616 queries.
This removes the majority of query duplicates from the page.

Release List Optimisations

---

staff/views/applications.py
tests/unit/staff/views/test_applications.py

This stops a Staff member trying to approve an Application which doesn't have the minimum amount of data required to generate a project (the study name).
Fixes #1248

Only allow approval of applications with minimum viable data

---

staff/forms.py
tests/unit/staff/test_forms.py

This checks the Project name supplied during Application Approval is unique rather than throwing a 500.
Fixes #1249

Validate Project Names on Application Approval

---

jobserver/jobs/hourly/dump_db.py

This adds a command to run pg_dump on our production database, putting it into the configured storage location for job-server in production.
This means developers can more easily copy down the production db for local work.

Add Dump Database Command

---

DEVELOPERS.md

This adds documentation for running Postgres locally when you're not using docker-compose.
Ref #1033 
Fixes #1189

Document Running Postgres Locally

---

jobserver/github.py
jobserver/settings.py
tests/conftest.py
tests/integration/test_auth.py
tests/unit/jobserver/test_github.py

This removes our custom auth backend, and the need for users to be a part of the `opensafely` GitHub organisation, so that we can move to having applications happen in job-server.
Fix #1133

Remove Custom GitHub Auth Backend

---

jobserver/jobs/hourly/dump_db.py

This attempts to fix th dump_db command which was erroring with `pg_dump: error: could not write to output file: Bad file descriptor`.
Running `pg_dump` with `--file` directly in the container works so I'm hoping this works.
The removal of the try/catch should mean sentry flags up failures next time.

Fix dump_db Command

---

applications/form_specs.py

We want to capture multiple emails in this field and type="email" stops the use of punctuation to delimit addresses.
Fixes #1365

Switch Study lead email(s) field from email to text

---

jobserver/templates/job_request_detail.html
jobserver/views/job_requests.py
tests/unit/jobserver/views/test_job_requests.py

This swtiches JobRequestDetail to look up JobRequests by the provided Org, Project, and Workspace as well as PK to avoid other URLs from falling through to it by accident.
I've also taken the opportunity to switch the view to be based on View, returning a TemplateResponse to mirror JobDetail since it's a simpler flow.

Fix JobRequest URL Handling

---

staff/templates/staff/application_detail.html

Mirroring the confirmation page this adds links to each section of an Application in the Staff Area.  I've opted for `View on Site` to mirror the buttons else where in the Staff Area:
Fixes #1286

Link to Application Sections from Staff Area

---

applications/templates/applications/confirmation.html

This sets the approval status text colour to red if a section isn't approved:
Fixes #1370

Use red text for "not approved" status on confirmation page

---

.github/dependabot.yml

We currently have Dependabot raising JS dependency bumps throughout the week and @tomodwyer bunching them into a single PR on Monday mornings.
This tries to reduce some of the noise in the build up to Tom's typical routine, and hopefully lowers the number of dependencies he is required to deal with since we don't need regular updates to dev tooling.

Tweak JS Dep Updates

---

DEVELOPERS.md

Add a step to run `npm ci` and have one location for documentation about compiling assets.

Improve compiling assets documentation

---

assets/src/scripts/outputs-viewer/hooks/use-file.js
assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx
assets/src/scripts/outputs-viewer/tests/jest-setup.js

- Replace function converting images to base64 with [`URL.createObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL)
- Update tests to use mock for window functions

Replace convertBlobToBase64 with createObjectURL

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

This is being done for every job included in an update, rather than any
job which transitions into this state, blowing through our Sentry quota
in a matter of days.

Stop sending internal error events to Sentry

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

Currently we can talk to the the JobRequsts listing API (`/api/v2/job-requests/`) with either:
* `?backend=<backend.slug>`
* a valid Backend.auth_token in the Authorization header
* both
Should we find both values, we give the value from the query_arg precedence.
Recently we renamed the databricks Backend to NHSD, however we are not in control of their deploy of job-runner which is still querying this API with both a valid Backend token, and `?backend=databricks`.  Since we deployed the changes (as of writing) we've notified Sentry about this mismatch ~24k times since it triggers on every API query.
This removes all the logic and only filters the endpoint when a valid token is present.
In the short term (and as we burn through our Sentry quota) I think we should merge this as-is. …

Remove ability to filter /api/v2/job-requests/ by backend in get args

---

jobserver/templates/_release_list.html
jobserver/templates/project_release_list.html
jobserver/templates/workspace_release_list.html
jobserver/views/releases.py
tests/unit/jobserver/models/test_outputs.py

I somehow missed this round of optimisations on the same page as  #1236 
This is a tricky one, since both the Workspace and Project ReleaseList views are rendering N Releases _and_ N ReleaseFiles.  I couldn't find a way to tell Django to select_related the approrpiate objects for building URLs with the `get_FOO_url` methods of the ReleaseFiles.  This lead to every ReleaseFile on the page executing 2-3 extra queries.
I tried rebuilding WorkspaceReleaseList by getting all the ReleaseFiles for the Workspace, then grouping by Release using groupby, but hit the same issue because I wasn't passing QuerySets around again.
I suspect we might be able to break the view down but I have a feeling it will hurt readability and have already spent several hours on it.

More Query Optimisations

---

services/logging.py

Gunicorn's loggers are called `gunicorn.access` and `gunicorn.error` so this actually configures those loggers.  Gunicorn's logs should now match the rest of the applications.

address gunicorn loggers correctly

---

applications/views.py
tests/unit/applications/test_views.py

This stops approved applications from being edited by users.
Fixes #1287

Block applications from being edited after being approved

---

.github/workflows/main.yml

This moves to using the setup-* action's caching (which is just the cache action under the hood but with expected defaults), and turns Pip caching back on but in the expected manner.  I've been trialling this on some personal projects without issues yet.
I'd like to trial the Pip caching here for ~1 month before rolling out to other projects.

Update CI Caching

---

jobserver/models/core.py
staff/forms.py
staff/templates/staff/project_detail.html
staff/templates/staff/project_membership_edit.html
staff/urls.py
staff/views/projects.py
tests/unit/jobserver/models/test_core.py
tests/unit/staff/views/test_projects.py

This enables editing a ProjectMembership in the Staff Area, linked from a given Membership on a given Project.
Fixes #1293

Edit ProjectMemberships in the Staff Area

---

jobserver/releases.py
jobserver/views/releases.py
jobserver/views/workspaces.py
tests/unit/jobserver/test_releases.py

This catches ReleaseFiles where their on-disk file is missing, which happens when we redact a file.  When building a zip for downloading a Release (or Snapshot) we now replace missing files with a short text template linking to the ReleaseFile and saying who deleted it.
Fixes #1070

Handle Missing ReleaseFiles

---

jobserver/templates/project_detail.html
jobserver/views/projects.py

This groups and denotes archived workspaces on project pages.
Fixes #1403

Surface Archived Workspaces

---

jobserver/templates/workspace_output_list.html
jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

We previously stopped the Outputs page for a Workspace from responding if there were no Snapshots but a change to the URL structure at some point made it easy to end up at a point where you are at `outputs/latest/`, at which point the parent page is 404ing.  Rather than meddle with the URLs (which I think still make sense), this takes the pragmatic route and just displays an explicit message that there is nothing to see here.
Fixes #1337

Always render the outputs page even if there are no snapshots

---

jobserver/templates/project_detail.html

This adds the roles for each Project member when the user viewing the page is a member of the Project's Organisation.
For example, the `COVID-19 Vaccine Effectiveness` Project which is a member of the DataLab org will display role information for any viewer who is also a member of the DataLab org:
Fixes #904

Display Roles on Project Page

---

jobserver/management/commands/inflate_release_files.py
pyproject.toml

This builds dummy files for ReleaseFiles missing their on-disk files and is expected to be run for local dev.  I've only tackled the easy subset of file types so we didn't have to pull in pillow to dev requirements for this to work.  It still covers a majority of ReleaseFiles.
Fixes #1202

Replace Missing ReleaseFiles

---

jobserver/settings.py

All form submissions are broken in production, maybe this will fix it? (although it shouldn't)

Set CSRF_TRUSTED_ORIGINS to our base URL

---

.github/workflows/main.yml

This matches our general tooling setup across the group and removes some unnecessary time installing dependencies in CI.

Combine Dev Tooling Checks

---

jobserver/backends.py
jobserver/templates/workspace_backend_files.html
justfile

Also, drive by fix for just file not erroring properly.
Also disabled the Download button on level 4 output viewer pages. It doesn't work, but it should be obvious that it doesn't work. I've opted to disable rather than remove, as I like UIs that don't disappear or change layout under you, but I'm not sure there's any styling to support `a.btn[disabled]`, at least I couldn't find any.

fix: set EMIS level_4_url to be localhost (same as TPP)

---

assets/src/scripts/outputs-viewer/components/Table/Table.jsx
assets/src/scripts/outputs-viewer/tests/components/Table/Table.test.jsx

We've already loaded the entire JSON, and we only display the first 1000
rows, so this is no more resource intensive, and more user friendly

fix: remove the 5000 line limit on displaying CSVs

---

jobserver/templates/status.html
jobserver/views/status.py

dictsort's resolution logic was restricted in Django 4.0.1, dropping
support for indexing on dictionaries, to avoid a potentional information
disclosure bug.
https://docs.djangoproject.com/en/4.0/releases/4.0.1/#cve-2021-45116-potential-information-disclosure-in-dictsort-template-filter

Order backends on Status page using ORM query instead of dictsort

---

.github/dependabot.yml

The dependabot config changed child items of `allow` to be an array, this updates to that syntax.

Switch dependabot allow items to an array

---

jobserver/views/projects.py

On ProjectDetail pages with several repos the lookup for private/public
status was noticably slowing the page down.  This switches to
ThreadPoolExecutor to run through them in parallel (mostly).

Run Repo Requests in Parallel on ProjectDetail Pages

---

.github/workflows/main.yml

See Simon's comment [1] for context.
[1]: https://github.com/opensafely-core/job-server/pull/1564#issuecomment-1024151856

Pin hadolint action since it's a third party action

---

assets/src/styles/main.scss
jobserver/templates/job_request_list.html

This switches the event log page to use dropdowns with select2.  As a bonus it makes it much clearer which filters are applied on page load.
Fixes #921 
Fixes #1298

Convert Event Log Filters to Dropdowns

---

staff/views/applications.py

Since we create a Project when approving an Application it seems useful to redirect to that after the approval action completes.

Redirect to Project After Application Approval

---

.github/workflows/auto-merge.yml

~This is waiting on Dependabot to raise a new PR we can test against.  In it's current form it will upload the full event payload (I hope) as an asset so we can work out if only running this for Python dependencies is possible.~
The plan is to have this workflow added to the repo template and applied to existing repos, auto-applying certain classes of dependency.  For job-server this will be all Python dependencies assuming all checks have passed.
---
We can't test this until it's on the default branch so the plan is to get it in, test with some dependabot PRs, then iterate from there, following [this seciton of the docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge …

Investigate GHA Metadata

---

.github/workflows/auto-merge.yml

This does a few things:
* drop event types now that we can see #1597 triggers `pull_request_target`
* use echo instead of cat because context is a templating construct
* grab the entire dependabot metadata blob [because `outputs.updated-dependencies-json` doesn't appear to contain anything useful](https://github.com/opensafely-core/job-server/runs/5184168004?check_suite_focus=true#step:3:1)
* grab the event pyayload
* bundle both outputs to a directory and expose them as artefacts

Get More Dependabot Metadata

---

.github/workflows/auto-merge.yml

Echoing to a file produces `Object` in both files (🤦‍♂️), so lets try getting the contents of the objects into logs instead.

echo to logs instead of a file

---

.github/workflows/auto-merge.yml

Dependabot appears to raise PRs with labels set so lets see if we can rely on that.
My only worry here is the labels are added after the PR is created so we might see the event come through initially without that data.  If that's the case then we'll need to checkout the head branch and grep `git-diff --stat` for the appropriate filename changes.  But since that's far more involved I think we can punt on it until we know it's required.

Only run this workflow on PRs from Dependabot and the python label

---

.github/workflows/auto-merge.yml

The previous attempt didn't run the workflow so we also didn't get any output, so this attempts to see what the contains() expression gives us as well as outputting the other parts of the previous check so we can manually verify them.

Check contains output in a run block

---

.github/workflows/auto-merge.yml

Following [these](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#approve-a-pull-request) [two](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request) sections in the docs the `gh` commands should now approve and toggle auto-merge on PRs which pass the `tests` check (a requirement for merging in this repo).

Approve and auto-merge Dependabot's Python PRs

---

.github/workflows/main.yml

We don't gain anything from hiding our org and project names in the
config, and we now have an Org-level secret for the integration.

update Sentry release config

---

jobserver/api/releases.py
jobserver/models/outputs.py
jobserver/releases.py
jobserver/settings.py
jobserver/urls.py
jobserver/views/releases.py
tests/unit/jobserver/models/test_outputs.py
tests/unit/jobserver/test_urls.py
tests/unit/jobserver/views/test_releases.py

ReleaseFiles are currently served to the SPA (and directly when opening in a new tab) by the `ReleaseFileAPI` view.  This checks a file can be viewed by checking details about the requesting user and the workspace.  Unfortunately this doesn't let us check if a file has been published, or handle the user being anonymous.
To work around this situation this PR:
* removes the default BasicAuthentication auth class from DRF so unauthenticated users can get through to views, since we handle our own permissions inside each view.
* Adds a new `PublishedSnapshotFile` view under `/<org>/<project>/<workspace>/published/<file_id>/` from which we can serve a file.
This lets us serve publicly viewable files from a completely separate URL, meaning we could, if necessary, apply caching to those URLs …

Expose Published Files to Unauthenticated User

---

entrypoint.sh
jobserver/backends.py

This was rewriting the db config in production.
ensure_backends command still works locally if needed in dev.

fix: do not ensure_backends on deployment

---

snippets/datasets-rubric.md

In `snippets/terms.md`, the same page is linked, but on the production
site.
This change makes the links consistent.
The production site also has more content than the URL linked. For
example, the ONS-CIS information is "awaiting acknowledgement content"
in the page linked, but updated on the production site.

Update policy link to production site

---

jobserver/templates/job_detail.html
jobserver/views/job_requests.py
tests/unit/jobserver/views/test_job_requests.py

Cancelling a job request previously added all the jobs to the request's cancelled_actions.  This resulted in jobs that had already completed (both failed and succeeded jobs) being marked as cancelled too.  This PR filters the request's jobs to cancel only those that have not yet completed.
Also adds some explanatory text to the individual job Cancel button.
Fixes #1629

Cancelling jobs from a job request

---

staff/views/applications.py
tests/unit/staff/views/test_applications.py

This should be set so we always have an audit trail.

Set Project.created_by when approving an Application

---

staff/templates/staff/project_detail.html
staff/views/projects.py

Now that we're handling application approvals via the Staff Area this puts a link to a Project's application, if one exists, on the ProjectDetail page.

Display application on Staff Area ProjectDetail page if it exists

---

staff/forms.py
staff/templates/staff/project_detail.html
staff/templates/staff/project_link_application.html
staff/urls.py
staff/views/projects.py
tests/unit/staff/test_forms.py
tests/unit/staff/views/test_projects.py

This adds a page to the Staff Area to help us (likely, only me though) link Projects to their Application.  We have a number of Projects which were created via the Staff Area since we weren't using the Approve Application UI (but now are) and so aren't linked to their relevant Application.  We need to manually reconcile that and this is intended to help with that process.

Link Project to Application UI

---

.github/workflows/auto-merge.yml

The current version of this workflow hasn't been triggering, from which I can assume that labels are applied after the PR is raised, so they're not present in the event payload we're receiving.
This looks at the PR branch to look for Python-specific requirements changes done in a Dependabot PR.  Mirroring how we look for tag updates in Data Builder it sets an output which we check in the subsequent step so non-Python updates (from Dependabot) should be ignored _without_ a failing Job.
---
This extra set of steps probably isn't required for most of our projects, which can rely on tests passing alone.  However, for job-server don't want to automatically merge Javascript changes without testing them out manually.  We're confident-enoiugh that our tests will catch problems with the Python …

Check Code Changes to get Language Type

---

jobserver/models/outputs.py
jobserver/templates/_release_list.html
jobserver/views/releases.py
tests/unit/jobserver/models/test_outputs.py
tests/unit/jobserver/views/test_releases.py

The URL for files in the latest release are structured differently to
URLs in other releases, which contain the Release id. So, we need
another way of retrieving the Release id. This solution parses the file
path to retreive it.

Retrieve Release id from ReleaseFile path

---

jobserver/templates/workspace_release_list.html
jobserver/views/releases.py
tests/unit/jobserver/views/test_releases.py

The collection of most recent files forms a pseudo-release object,
containing a list of files and other data. This has been renamed to
latest_release.

Rename latest files to latest release

---

jobserver/templates/workspace_create_error.html
jobserver/views/workspaces.py
staff/templates/staff/user_detail.html
staff/templates/staff/user_list.html
staff/views/orgs.py
staff/views/users.py
tests/unit/jobserver/views/test_workspaces.py
tests/unit/staff/views/test_orgs.py
tests/unit/staff/views/test_users.py

This is a collection of changes aimed at making the setup of new Users easier for either co-pilots/staff or users themselves.
Specifically it flags up when a User is missing memberships to any one of Backends, Orgs, or Projects on their detail page in the Staff Area (fixing #1704), on the User list page using badges (fixing #1705), and tells a user to contact their copilot/support when they aren't linked to an Org (fixing #1706).

Smooth Setting Up Users

---

jobserver/views/releases.py
tests/factories/jobserver.py
tests/unit/jobserver/views/test_releases.py

It was impossible to determine which backend a release came from without
it.
Fixes #1736

fix: include backend name in release lists

---

jobserver/releases.py
tests/unit/jobserver/views/test_releases.py

This adds a header to all responses which serve ReleaseFiles to add the date they were last updated.  This is for the reports site so it can display that information on the page along with the file contents.
Is there a better key for this header to show it's a custom one from job-server?

Set a last-updated header when serving ReleaseFiles

---

jobserver/api/releases.py
jobserver/models/core.py
tests/integration/test_release_api_access.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/models/test_core.py

This switches our token-based auth to the format `username:token`, so that we can look up the relevant User with the username.

Require Usernames for Token-based Auth

---

.github/workflows/auto-merge.yml

We want GitHub actions PRs to also be marked for auto-merge, so lets capture those tags as well.

Capture GitHub Actions PRs for auto-merge

---

.github/workflows/main.yml

This is generally slowing down feedback from CI.

Don't gate CI tests on tooling checks

---

staff/forms.py
staff/templates/staff/application_approve.html
staff/templates/staff/org_create.html
staff/templates/staff/org_create.htmx.html
staff/urls.py
staff/views/applications.py
tests/unit/staff/views/test_applications.py

When approving an Application we need the Staff member to select an Org and decide on a title for the Project they're about to create.  When the Application is for a new Org the user has to go to the Org section of the Staff Area and create it there, which for a single field form feels like a bit much.  This uses HTMX to call a view which returns a Bootstrap modal with the Org create form in it.  On success it redirects the user back to the approval page with the new Org's slug in the query args so the Org dropdown can pre-select that Org for the user.
I attempted to break down the OrgCreate page's template so we could re-use the form but it ended up being a bit tricky.  The Form instance is generated under the hood by OrgCreate (which is a configured CreateView) so there's no definition …

Add an Org via the Approve Application Page

---

jobserver/api/releases.py
jobserver/templates/snapshot_detail.html

This fixes two pieces of downloading Snapshots (published outputs).
The download URL was being created on the wrong object and we now only include existing ReleaseFiles in a Snapshot.  ReleaseFiles can be deleted after a Snapshot is created still but we won't add them by default.
Fixes #1784

Fix downloading published outputs

---

DEVELOPERS.md

This adds a set of quick-start docs for setting up local data if one doesn't have access to the production backups or wants a clean local copy of the site.  It's based off [my comment to an outside integrator](https://github.com/opensafely-core/job-server/issues/1651#issuecomment-1120771890).
Ref opensafely/documentation#708

Document how to create data locally without a production backup

---

requirements.dev.txt

Pre-commit hooks were erroring for me, apparently due to [this bug](https://github.com/pypa/virtualenv/issues/2163).  (On python 3.10 - the issue reports errors on 3.7 and 3.8 but not 3.9, but it seems 3.10 was affected too, or at least my version of it).  Upgrading to virtualenv==20.7.1 as mention in the issue fixed the problem, but since pre-commit requires >=20.0.8, might as well upgrade to the latest one.

Upgrade virtualenv

---

requirements.dev.txt

Reverts opensafely-core/job-server#1811

Revert "build(deps-dev): bump pip-tools from 6.6.1 to 6.6.2"

---

assets/src/scripts/outputs-viewer/context/FilesProvider.jsx
assets/src/scripts/outputs-viewer/hooks/use-file.js
assets/src/scripts/outputs-viewer/tests/jest-setup.js

Currently the outputs viewer is caching `fetch` requests too aggressively. We want to refetch files from the server on page reload.
This PR generates a cryptographically random UUID each time the React app is mounted, and appends this as a query string to the fetched URL. This forces a file download on first attempt, but allows for cached queries when navigating between files.

Generate UUID to force a fresh download on reload

---

DEVELOPERS.md

* `_KEY` twice!
* also clarify that key refers to "Client ID" in the current Github interface.

fix: typo in Developer docs

---

jobserver/templates/job_request_detail.html
jobserver/views/job_requests.py
tests/unit/jobserver/views/test_job_requests.py

* matching documentation here: https://github.com/opensafely/documentation/pull/753 
* very open to suggestions on better layout/styling
* looks like this: 
* nb. these links will be visible to everyone, but only users with honeycomb logins will be able to view the visualisations. There may be an argument for only showing the links to e.g. admin users.

feat: add links to two simple visualisations

---

jobserver/slacks.py
tests/unit/jobserver/api/test_releases.py

`opensafely-outputs` was getting quite noisy. This moves notifications for releases from `opensafely-outputs` to the newly created `opensafely-releases`.
@ghickman is this all I need to do are is there more to it?

update slack channel for release notifications

---

assets/src/js/tablesorter.js
staff/templates/staff/repo_list.html
staff/views/repos.py

This adds the contact column to the Private Repos report page of the Staff Area in an attempt to save Amir looking it up.

Add Workspace Contact to Private Repos Report

---

jobserver/settings.py
jobserver/views/job_requests.py
tests/unit/jobserver/views/test_job_requests.py

This adds a feature flag to disable creating jobs.
Previously we relied on the user's BackendMemberships QS being the full set of backends a user could access.  With this change I've hoisted that lookup into dispatch so we can selectively exclude some backends if the flag is enabled.  Then the access check and form kwargs builder can both use that maybe-modified QS.

Disable Creating Jobs

---

staff/forms.py
tests/unit/staff/test_forms.py

While working on something else I realised this field was required in the Staff Area form, but Project numbers are still nullable while we port data into the system.

Ensure Project.number isn't required in the Staff Area

---

.github/workflows/main.yml

`check` used to a requirement of `test` which was a requirement of deploy.  We removed that requirement to improve the feedback loop of running tests in CI in #1780 but missed this part.

Make check a requirement for deploy

---

docker-compose.yml
dotenv-sample
jobserver/github.py
pyproject.toml

We no longer limit the registration based on membership in a list of
GitHub orgs.

Remove unused AUTHORIZATION_ORGS variable

---

jobserver/api/jobs.py

This should give developers an easy way to get from the error to the
docs on how to investigate and fix the error.

Add our playbook docs as a tag to sentry messages

---

jobserver/forms.py
jobserver/middleware.py
jobserver/settings.py
jobserver/templates/settings.html
jobserver/views/users.py
tests/unit/jobserver/test_middleware.py
tests/unit/jobserver/views/test_users.py

This redirects all users with an empty `fullname` value to their settings page where they will see an alert saying they need to fill in their fullname.
I'm always wary of adding more middleware but since we have so many (~50%) users who need to fill it in this is the easiest way to force them to the page where they can do so.  It also shouldn't result in more db requests since `request.user` is set on the request by a preceeding middleware (`AuthenticationMiddleware`).
I considered using Social Auth's partial pipeline machinery to kick a user out of the pipeline if they didn't have a name set on GitHub, so they could fill it in on a job-server page before returning to the pipeline.  However that seemed like more work and wouldn't cover our existing user base.
Fixes #1900 
Fixes #1903

Require User.fullname is set

---

jobserver/views/orgs.py
staff/views/orgs.py

Fix this in a couple more places.
We can't order on `title` since it's a property which combines number and name.  I'm always wary of `Model.Meta.ordering` but if we find this continues to be an issue we should probably just use that.

Order Projects of an Org by number then lowercase name

---

staff/forms.py
staff/templates/staff/project_edit.html
staff/views/projects.py
staff/views/workspaces.py
tests/unit/staff/test_forms.py
tests/unit/staff/views/test_projects.py

To handle #1878 I need to change several Workspace's Project, and the slug of a Project.  These changes streamline both of those.

Easier redirects

---

jobserver/templates/index.html
tests/unit/jobserver/views/test_index.py

Standardise button naming across both home page and Project page.
Part of opensafely/documentation#858

Match project page nomenclature

---

assets/src/js/tablesorter.js
services/logging.py
staff/templates/staff/repo_list.html
staff/views/repos.py
tests/fakes.py
tests/unit/staff/views/test_repos.py

This reworks the logic for the view, keeping repos as the object we get and filter, but enhancing them with workspaces and related derived data (first job run etc).
h/t to @bloodearnest for helping me get the Workspace query to work without massively duplicating the number of Workspaces!

Fix Private Repos report page

---

.github/dependabot.yml

We think this config is slightly broken and it's not clear if all dependencies are getting updated.  Since we're auto-merging Python dependabot PRs there's no benefit from having the two sections here either.
Fixes #1852

Merge pip sections of Dependabot Config

---

staff/views/repos.py
tests/unit/staff/views/test_repos.py

These are being tracked separately

fix: do not consider legacy pre-jobrunner repos in repos page

---

jobserver/github.py

This flips the way in which we filter repos to present to the User when creating a Workspace.
We currently get repos from the `researchers` team  relying on our permissions script to ensure repos are in that.  There's a lag time for that script running (every 15 minutes) and it causes some amount of support overhead to ask Users to wait for that to update.
This change removes the team check in favour of relying on our recent use of tagging non-research repos with the `non-research` topic.

Filter out non research repos

---

.github/workflows/main.yml
justfile

This copies our python stack in flow, where each target compares some
file modification times, and only runs the target if the check file is
older than the source.

Wrap up asset creation in skipable just targets

---

jobserver/api/jobs.py
services/logging.py

The threadlocal bind() function has been deprecated.
I followed this guide to do the upgrade:
https://github.com/jrobichaud/django-structlog/#upgrading-to-30

Switch to contextvars based structlog usage

---

.flake8

This switches us to `extend-exclude` so we get the base flake8 excludes for free and adds various project and tooling-related directories to the ignore.  Locally this dropped flake8 runtime from ~6.5 to ~4.5s for me.

extend base exclude with various project and tool directories

---

tests/unit/jobserver/views/test_jobs.py
tests/unit/jobserver/views/test_workspaces.py

Workspace.name is a factory boy sequence so we can't rely on a hardcoded
value since other tests will change this value.

dynamically look up workspace names in tests

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

We want to be explicit that both review fields are None | dict where the
dict is either free form (in Release) or specified for ReleaseFile
(because we generate ReleaseFileReviews from it).

Set Release.review & ReleaseFile.review (via FileSerializer) as nullable

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

The tests changes here are quite clunky.  They've mostly been ripped from the `new-style-release-factories` branch where I'm abstracting them away from most tests and my hope is to get that landed very quickly after this.

Build releases with the new format of requested_files

---

jobserver/releases.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/test_releases.py

When a ReleaseFile has been created but no file uploaded we don't have a
path for it, so ReleaseFile.absolute_path() will return a valid path to
the releases directory, which will exist.  However a file being on disk
isn't the most correct check here since a file could have also been
deleted from disk, so lets check to see if we think we've uploaded it
previously.

check for existance of files using uploaded_at

---

TESTING.md
jobserver/api/releases.py
jobserver/releases.py
tests/conftest.py
tests/factories/__init__.py
tests/factories/jobserver.py
tests/factories/releases.py
tests/integration/test_release_api_access.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/models/test_outputs.py
tests/unit/jobserver/test_releases.py
tests/unit/jobserver/views/test_releases.py
tests/unit/jobserver/views/test_workspaces.py

This switches all our tests which touch Release and/or ReleaseFile objects to use some combination of FactoryBoy factories and fixtures which wrap up the logic necessary for combining them.
The goal here was to support our recent full use of the two-legged upload process whereby we can have ReleaseFiles without files on disk.  This means many of our tests can have greatly reduced setup (as little as a bare factory invocation) or have the creation of the appropriate objects abstracted to a fixture.
The fixtures are made up of a few layers of functions with low level ones like `file_content` generating random byte strings and high level ones like `release` which generates all the pieces required to have a Release, a related ReleaseFile, and a file on-disk.
I've laid out how this all works …

Build a testing onion for Release[File]s

---

jobserver/api/releases.py
jobserver/models/outputs.py
jobserver/releases.py
jobserver/views/releases.py
tests/unit/jobserver/test_releases.py
tests/unit/jobserver/views/test_releases.py

Now that ReleaseFiles are created without a file on-disk we want ReleaseFile.is_deleted to use one of the two deleted_* fields we explicity set when deleting.  Since those fields are required to both be filled _or_ empty by the db check constraint I've picked `deleted_at` since it's a cheaper field to look up.

Use deleted_at to drive is_deleted

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

Use FileSerializer to validate the output of generate_index to ensure we match the incoming payloads for various APIs.
I've avoided using the serializer to pull the field data since this feels a lot more readable.
Small drive-by fix on getting file size from the db as I was there too.
Fixes #2049

Validate file list apis

---

assets/src/scripts/outputs-viewer/App.jsx
assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
assets/src/scripts/outputs-viewer/utils/props.js
jobserver/api/releases.py
jobserver/templates/release_detail.html
tests/unit/jobserver/api/test_releases.py

Add per-Release and per-ReleaseFile metadata
**Release**
We're just saving raw data to the metadata for Release currently so this isn't the most useful but we can at least show that we've captured parts of it?
**ReleaseFile**

Display review data

---

jobserver/api/releases.py
jobserver/github.py
jobserver/releases.py
tests/fakes.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/test_releases.py
tests/verification/test_github.py

This creates an issue on GitHub for the release when it's created via the API.  It uses the templates from the output reviewing repo.
There's one open question around how we decide if a user is considered internal but the rest can be reviewed now.
Fixes #2027

Create GitHub issue on release

---

.flake8
.gitignore
justfile
pyproject.toml
scripts/local-release-hatch.sh

`just release-hatch` will ensure a local-dev backend exists, and set up
a local checkout of release-hatch to use it, and run the release-hatch
server. Its purpose is to ease development against the release-hatch api

chore: add tooling to run local release-hatch for testing

---

jobserver/api/releases.py
pyproject.toml
tests/unit/jobserver/api/test_releases.py

osrelease requires it.
Also, allow github issue creation to be skipped if needed, as osrelease
does not want one to be created.
There doesn't seem to be a fixture for github messages, so I'm going to add that and a test in a follow up PR, but this fix need to get out quickly

fix: re add the release-id header that was accidentally removed.

---

jobserver/api/releases.py
tests/unit/jobserver/api/test_releases.py

Headers were proving problematic with CORS requests

fix: return data via json from the create release rather than headers

---

assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
jobserver/releases.py
jobserver/views/releases.py
tests/unit/jobserver/api/test_releases.py
tests/unit/jobserver/test_releases.py

Currently, there is no way to via a release with files from
release-hatch. All the release metadata is stored in jobserver, but the
contents are stored in release-hatch, so the SPA really needs data from
both sources.
This change is a quick hack to redirect to release-hatch for the file
contents if the file has not been uploaded. This will only work on level
4, but provides a basic view of the pending release for an OutputChecker
to look at.
It works by returning an empty 200 with some headers, including auth,
which the output-viewer manually fetches.
It would be better to add support for this mode of viewing to the
output-viewer itself, and launched in a specific manner different to the
current method. But this will work for the purposes of a demo.

fix: view not-yet-uploaded files for a release

---

jobserver/templates/index.html
jobserver/templates/project_detail.html
jobserver/templates/workspace_detail.html

The wording around why a repository may be private is being updated in the Principles of OpenSAFELY. This change keeps job-server up-to-date with that, while moving the text to the most relevant place for users of the site.
Refs: https://github.com/opensafely/documentation/issues/892

Update wording around private repos

---

jobserver/api/releases.py
tests/fakes.py

The supression isn't working, and it's spaming users with issues

fix: remove the GH issue creation trigger for releases

---

jobserver/api/jobs.py
tests/unit/jobserver/api/test_jobs.py

The purpose of this is to allow metrics emitted by job-runner to be
tagged by org/project so we can aggregate by them by those values. e.g.
how much CPU has this org used in the last month?

fix: expose project and org name in JobRequest API

---

staff/templates/staff/repo_detail.html
staff/templates/staff/repo_list.html
staff/urls.py
staff/views/repos.py
tests/fakes.py
tests/unit/staff/views/test_repos.py

This adds a detail page for Repos to the Staff Area so we can display more info about repos without compressing it into the list page.

Add RepoDetail page to Staff Area

---

jobserver/views/releases.py
jobserver/views/workspaces.py

Modify CSP rules for the SPA, due to the number of errors coming through to Sentry.
#2004

Remove CSP from Outputs SPA view

---

justfile

This saves us running collectstatic on ever pytest invocation.

Base tests on assets target so the frontend stack is conditionally run

---

jobserver/api/releases.py

So that we stop receiving CSP errors on these pages.
Linked to #2004

Add CSP exemption to ReleaseFileAPI content

---

jobserver/signing.py
pyproject.toml
requirements.prod.txt
tests/factories/applications.py
tests/factories/jobserver.py
tests/fakes.py
tests/unit/jobserver/models/test_stats.py
tests/unit/jobserver/test_signing.py
tests/unit/jobserver/views/test_status.py

Blocked on ~encode/django-rest-framework#8588 or https://github.com/encode/django-rest-framework/pull/8591~ https://github.com/encode/django-rest-framework/pull/8599 getting merged and released.
Fixes #1998

Bump django to 4.1

---

jobserver/templates/status.html
jobserver/views/status.py
tests/unit/jobserver/views/test_status.py

Display the number of running and queued jobs on the job-server [status page](https://jobs.opensafely.org/status/) for each backend. This should allow us to set researchers' expectations around how long their jobs might be queued for and allow anyone on tech support to more easily identify if there are potential problems with a particular backend.
Fixes #2090

Display number of running and queued jobs

---

jobserver/models/core.py

We use the string repr in the Staff Area's search so it's useful to be consistent with how Users are displayed in various other places.

Use our User.name property for string representations of a User

---

jobserver/templates/index.html
jobserver/templates/job_request_create.html
jobserver/templates/workspace_detail.html
staff/templates/staff/workspace_detail.html

This fixes all the missed used of `workspace.repo`, `workspace.repo_name`, and `workspace.repo_owner` to use the equivalent on the Repo object.

Fix all uses of workspace.repo to use attributes of the Repo instance

---

assets/src/styles/main.scss

This expands the backend column to account for the graphnet-test backend:
**before:**
**after:**

Handle longer backend names on log pages

---

staff/views/repos.py

as the jQuery code used on the page is throwing inline styling errors.

Remove CSP from Private Repos Staff Area page

---

jobserver/api/releases.py
jobserver/settings.py

This exempts the API from our CSP via a URL prefix match.  Having found DRF adds in more violations we felt that the API shouldn't need to deal with the CSP at all.

Exempt entire API from CSP

---

jobserver/context_processors.py
staff/templates/staff/dashboards/index.html
staff/templates/staff/dashboards/repos.html
staff/templates/staff/index.html
staff/templates/staff/repo_list.html
staff/urls.py
staff/views/dashboards.py
staff/views/repos.py
tests/unit/staff/views/test_repos.py

This pulls the existing repos page into a new dashboards menu and adds a "normal" repos page, which only lists repos that job-server knows about.
I've added orgs as a filter in leiu of anything more obvious.
Fixes #2156

Add a normal ReposList page

---

jobserver/templates/project_release_list.html
jobserver/templates/workspace_release_list.html

This adds explainer text to both the project and workspace release list pages.  While we don't link to the project releases page (which I think might just be a bug?) I've updated it since it's still live.
The workspace releases page looks like this:
Fixes #2162

Explain disabled release buttons

---

jobserver/templates/job_detail_tw.html

Don't convert the identifier to uppercase.

Show case sensitive Job ID

---

static/robots.txt

This is an ever growing list of jobs which have run on the platform, all of which have detail pages which are still crawled.  We're seeing a lot of bot traffic to the page which isn't ideal so this aims to stop that.

Remove bot access to the event log page

---

jobserver/management/commands/delete_project.py
tests/unit/jobserver/management/commands/test_delete_project.py

We've been asked to [delete a project](https://github.com/opensafely-core/job-server/issues/1991) that no longer has any workspaces associated with it, as part of a data tidying exercise for older work in job server.
There is currently no way to do this in the UI (e.g via the staff area), so this management command adds a quick way for admins to do this without manually editing the database.

Django management command to delete empty projects

---

jobserver/honeycomb.py
jobserver/templates/job_request_detail.html
jobserver/views/job_requests.py
tests/unit/jobserver/test_honeycomb.py

* [example visualisation](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner?query=%7B%22start_time%22%3A1665410183%2C%22end_time%22%3A1665492336%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22name%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22CONCURRENCY%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22enter_state%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3Atrue%7D%2C%7B%22column%22%3A%22name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22RUN%22%7D%2C%7B%22column%22%3A%22name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22JOB%22%7D%2C%7B%22column%22%3A%22name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22job%22%7D%2C%7B%22column%22%3A%22job_request%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22rfhiav5zj4bizh2v%22%7D%5D%2C%22f …

feat: add link to honeycomb concurrency visualisation for a job_request

---

.github/workflows/main.yml

I'm not sure why dependabot hasn't caught the checkout upgrades yet.
This should fix the deprecations flagged in #2204, except the `set-output` one in the `tests` job because it comes from `actions/download-artifact` which hasn't fixed this yet.

Remove deprecations from CI

---

staff/templates/staff/user_detail.html

This adds an email address to the UserDetail page in the staff area.  It picks their manually set notifications address if they've set one (since their GitHub address might not be ideal), and falls back to the email we get from GitHub if not.
Fixes #2205

Add a User's email address to their staff area page

---

jobserver/templates/project_detail.html
jobserver/views/projects.py
tests/unit/jobserver/views/test_projects.py

This switches the Created card to "Timeline" (matching the idea of the timeline in the revamped JobDetail page), adding in the date and time the first job for a project was run.
I've added a details section to explain why a Project might be younger than its first job:
And for projects without any jobs yet kept it succinct:
Fixes #2145

Add first job run datetime to Project pages

---

jobserver/templates/job_detail_tw.html

Fix Honeycomb link styling

---

jobserver/models/core.py

Depending on which code path you take, `tracecontext` will have been imported in the `propagation` namesapce or not - this fixes that and explicitly imports it.

Fix OpenTelemetry incorrect import location

---

jobserver/templates/project_repo_list.html
jobserver/urls.py
jobserver/views/repos.py
tests/unit/jobserver/views/test_repos.py

This adds a view to handle incoming requests of the form `/repo/<quoted GitHub repo URL>/`.
Fixes #2194

Add the repo handler view

---

jobserver/views/releases.py
jobserver/views/workspaces.py
tests/unit/jobserver/views/test_workspaces.py

We've moved all the views which use this method of header update to be CSP exempt so we no longer need this code.

Remove our custom uses of response._csp_update

---

jobserver/templates/sign_off_repo.html

This doesn't change any text on the page since we still need to double check READMEs until the majority of them have been updated, so I've left the changes at just setting the docs link now that we know it.
Fixes #2238

Fix link to publishing repos guidance

---

jobserver/emails.py
jobserver/templates/emails/notify_repo_signed_off.txt
jobserver/views/repos.py
tests/unit/jobserver/test_emails.py
tests/unit/jobserver/views/test_repos.py

This adds an email for workspace creators once a repo has been completely signed off, notifying them of the change in repo state.  I've used `bcc` here so as not to leak email addresses between workspace creators.
Fixes #2261

Email workspace creators after final researcher sign off

---

staff/templates/staff/repo_detail.html
staff/views/repos.py

This displays the email addresses of workspace contacts on a RepoDetail page.  It uses the format `name <email>` for users with email addresses.
Fixes #2245

Display contacts for workspaces as email addresses

---

jobserver/templates/_components/pill.html
jobserver/templates/project_detail.html

After checking all the projects, the following styling changes were required.
`project.title` contains the _"Project Number"_ which is used for internal communication. For this reason, we should only display the `project.name` in the meta title and breadcrumbs.
> ![](https://user-images.githubusercontent.com/24863179/199524104-6d7adf5c-7fbd-49b8-861e-dccb919f7fd2.png)
As we have removed the _"Project Number"_ from the breadcrumbs and meta title, we should display this Project Number to logged in users on the Project Detail page.
> ![](https://user-images.githubusercontent.com/24863179/199531199-65d0dfeb-b10e-44bb-91f3-b2ecd020a30a.png)
Google Lighthouse was (correctly) complaining about the nesting of the definition list items.
> …

Styling tweaks for Project Details

---

jobserver/auth_pipeline.py
jobserver/settings.py
tests/unit/jobserver/test_auth_pipeline.py

This fixes the issue where changing/setting your name on job-server got overwritten with the data from GitHub the next time you logged into job-server.  This was particularly annoying when a user had no name set on GitHub, set one on job-server, then was prompted to set it again the next time they logged into job-server.
Ref #1962

Only set fullname from GitHub if not already set

---

staff/views/repos.py

In testing with Catherine we found the comma form ended up malformed in Windows Mail.  Some googling suggests that semi-colon is the correct form.
Ref #2245

Separate emails with semi-colons instead of commas

---

staff/views/dashboards/copiloting.py
tests/unit/staff/views/dashboards/test_copiloting.py

In production this page is hitting the 30s timeout for gunicorn and the worker is being killed.
When annotating the number of files for a project the query projects query jumps from ~120ms to ~20s locally.  I can't see anything obviously wrong from the query planner and it seems to specifically be the files annotation causing this slow down.  So instead this does a separate query, grouping in memory by project and coverting to a dict of
project_pk: number_of_files, which is merged with the project data.
With this change I'm seeing page load times of ~160ms.
Refs #2256

Look up file counts for copilot dashboard in a second query

---

staff/views/dashboards/copiloting.py

Copilots only want to know about projects from orgs which get assigned copilots.

Ignore orgs who are not copiloted

---

assets/src/js/projects-tablesorter.js
staff/templates/staff/dashboards/index.html
staff/templates/staff/dashboards/projects.html
staff/urls.py
staff/views/dashboards/projects.py
tests/unit/staff/views/dashboards/test_projects.py

This is ostensibly identical to the copilots dashboard but doesn't exclude the Datalab or LSHTM orgs.  We expect these dashboards to diverge over time, hence putting them on separate pages.

Add a projects dashboard

---

.gitignore
pyproject.toml

By default (according to --help as of v22.8.0) black is already ignoring this list of directories:
/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist|__pypackages__)/
We were using --exclude which overwrote this list.  Black supports --extend-exclude which builds upon this list and also makes use of the repos .gitignore [1].  Since we we want both git and black to ignore the files for this repo can drop all black config here.
1: https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore

Merge ignored directories into gitignore
